packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  core-js: set this to true or false
  esbuild: true
  msgpackr-extract: true
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
  - msgpackr-extract
