/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `DeliverySnapshot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DeliverySnapshot
 *
 */
export type DeliverySnapshotModel =
  runtime.Types.Result.DefaultSelection<Prisma.$DeliverySnapshotPayload>

export type AggregateDeliverySnapshot = {
  _count: DeliverySnapshotCountAggregateOutputType | null
  _min: DeliverySnapshotMinAggregateOutputType | null
  _max: DeliverySnapshotMaxAggregateOutputType | null
}

export type DeliverySnapshotMinAggregateOutputType = {
  id: string | null
  deliveryVersionId: string | null
  htmlObjectKey: string | null
  screenshotObjectKey: string | null
  createdAt: Date | null
}

export type DeliverySnapshotMaxAggregateOutputType = {
  id: string | null
  deliveryVersionId: string | null
  htmlObjectKey: string | null
  screenshotObjectKey: string | null
  createdAt: Date | null
}

export type DeliverySnapshotCountAggregateOutputType = {
  id: number
  deliveryVersionId: number
  htmlObjectKey: number
  screenshotObjectKey: number
  responseHeaders: number
  createdAt: number
  _all: number
}

export type DeliverySnapshotMinAggregateInputType = {
  id?: true
  deliveryVersionId?: true
  htmlObjectKey?: true
  screenshotObjectKey?: true
  createdAt?: true
}

export type DeliverySnapshotMaxAggregateInputType = {
  id?: true
  deliveryVersionId?: true
  htmlObjectKey?: true
  screenshotObjectKey?: true
  createdAt?: true
}

export type DeliverySnapshotCountAggregateInputType = {
  id?: true
  deliveryVersionId?: true
  htmlObjectKey?: true
  screenshotObjectKey?: true
  responseHeaders?: true
  createdAt?: true
  _all?: true
}

export type DeliverySnapshotAggregateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which DeliverySnapshot to aggregate.
   */
  where?: Prisma.DeliverySnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of DeliverySnapshots to fetch.
   */
  orderBy?:
    | Prisma.DeliverySnapshotOrderByWithRelationInput
    | Prisma.DeliverySnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.DeliverySnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` DeliverySnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` DeliverySnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned DeliverySnapshots
   **/
  _count?: true | DeliverySnapshotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: DeliverySnapshotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: DeliverySnapshotMaxAggregateInputType
}

export type GetDeliverySnapshotAggregateType<
  T extends DeliverySnapshotAggregateArgs,
> = {
  [P in keyof T & keyof AggregateDeliverySnapshot]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDeliverySnapshot[P]>
    : Prisma.GetScalarType<T[P], AggregateDeliverySnapshot[P]>
}

export type DeliverySnapshotGroupByArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.DeliverySnapshotWhereInput
  orderBy?:
    | Prisma.DeliverySnapshotOrderByWithAggregationInput
    | Prisma.DeliverySnapshotOrderByWithAggregationInput[]
  by:
    | Prisma.DeliverySnapshotScalarFieldEnum[]
    | Prisma.DeliverySnapshotScalarFieldEnum
  having?: Prisma.DeliverySnapshotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DeliverySnapshotCountAggregateInputType | true
  _min?: DeliverySnapshotMinAggregateInputType
  _max?: DeliverySnapshotMaxAggregateInputType
}

export type DeliverySnapshotGroupByOutputType = {
  id: string
  deliveryVersionId: string
  htmlObjectKey: string
  screenshotObjectKey: string | null
  responseHeaders: runtime.JsonValue | null
  createdAt: Date
  _count: DeliverySnapshotCountAggregateOutputType | null
  _min: DeliverySnapshotMinAggregateOutputType | null
  _max: DeliverySnapshotMaxAggregateOutputType | null
}

export type GetDeliverySnapshotGroupByPayload<
  T extends DeliverySnapshotGroupByArgs,
> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DeliverySnapshotGroupByOutputType, T["by"]> & {
      [P in keyof T &
        keyof DeliverySnapshotGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], DeliverySnapshotGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], DeliverySnapshotGroupByOutputType[P]>
    }
  >
>

export type DeliverySnapshotWhereInput = {
  AND?: Prisma.DeliverySnapshotWhereInput | Prisma.DeliverySnapshotWhereInput[]
  OR?: Prisma.DeliverySnapshotWhereInput[]
  NOT?: Prisma.DeliverySnapshotWhereInput | Prisma.DeliverySnapshotWhereInput[]
  id?: Prisma.StringFilter<"DeliverySnapshot"> | string
  deliveryVersionId?: Prisma.StringFilter<"DeliverySnapshot"> | string
  htmlObjectKey?: Prisma.StringFilter<"DeliverySnapshot"> | string
  screenshotObjectKey?:
    | Prisma.StringNullableFilter<"DeliverySnapshot">
    | string
    | null
  responseHeaders?: Prisma.JsonNullableFilter<"DeliverySnapshot">
  createdAt?: Prisma.DateTimeFilter<"DeliverySnapshot"> | Date | string
  deliveryVersion?: Prisma.XOR<
    Prisma.OrderDeliveryVersionScalarRelationFilter,
    Prisma.OrderDeliveryVersionWhereInput
  >
}

export type DeliverySnapshotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  deliveryVersionId?: Prisma.SortOrder
  htmlObjectKey?: Prisma.SortOrder
  screenshotObjectKey?: Prisma.SortOrderInput | Prisma.SortOrder
  responseHeaders?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deliveryVersion?: Prisma.OrderDeliveryVersionOrderByWithRelationInput
}

export type DeliverySnapshotWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?:
      | Prisma.DeliverySnapshotWhereInput
      | Prisma.DeliverySnapshotWhereInput[]
    OR?: Prisma.DeliverySnapshotWhereInput[]
    NOT?:
      | Prisma.DeliverySnapshotWhereInput
      | Prisma.DeliverySnapshotWhereInput[]
    deliveryVersionId?: Prisma.StringFilter<"DeliverySnapshot"> | string
    htmlObjectKey?: Prisma.StringFilter<"DeliverySnapshot"> | string
    screenshotObjectKey?:
      | Prisma.StringNullableFilter<"DeliverySnapshot">
      | string
      | null
    responseHeaders?: Prisma.JsonNullableFilter<"DeliverySnapshot">
    createdAt?: Prisma.DateTimeFilter<"DeliverySnapshot"> | Date | string
    deliveryVersion?: Prisma.XOR<
      Prisma.OrderDeliveryVersionScalarRelationFilter,
      Prisma.OrderDeliveryVersionWhereInput
    >
  },
  "id"
>

export type DeliverySnapshotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  deliveryVersionId?: Prisma.SortOrder
  htmlObjectKey?: Prisma.SortOrder
  screenshotObjectKey?: Prisma.SortOrderInput | Prisma.SortOrder
  responseHeaders?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.DeliverySnapshotCountOrderByAggregateInput
  _max?: Prisma.DeliverySnapshotMaxOrderByAggregateInput
  _min?: Prisma.DeliverySnapshotMinOrderByAggregateInput
}

export type DeliverySnapshotScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.DeliverySnapshotScalarWhereWithAggregatesInput
    | Prisma.DeliverySnapshotScalarWhereWithAggregatesInput[]
  OR?: Prisma.DeliverySnapshotScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.DeliverySnapshotScalarWhereWithAggregatesInput
    | Prisma.DeliverySnapshotScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DeliverySnapshot"> | string
  deliveryVersionId?:
    | Prisma.StringWithAggregatesFilter<"DeliverySnapshot">
    | string
  htmlObjectKey?: Prisma.StringWithAggregatesFilter<"DeliverySnapshot"> | string
  screenshotObjectKey?:
    | Prisma.StringNullableWithAggregatesFilter<"DeliverySnapshot">
    | string
    | null
  responseHeaders?: Prisma.JsonNullableWithAggregatesFilter<"DeliverySnapshot">
  createdAt?:
    | Prisma.DateTimeWithAggregatesFilter<"DeliverySnapshot">
    | Date
    | string
}

export type DeliverySnapshotCreateInput = {
  id?: string
  htmlObjectKey: string
  screenshotObjectKey?: string | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  deliveryVersion: Prisma.OrderDeliveryVersionCreateNestedOneWithoutSnapshotsInput
}

export type DeliverySnapshotUncheckedCreateInput = {
  id?: string
  deliveryVersionId: string
  htmlObjectKey: string
  screenshotObjectKey?: string | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type DeliverySnapshotUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  htmlObjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  screenshotObjectKey?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deliveryVersion?: Prisma.OrderDeliveryVersionUpdateOneRequiredWithoutSnapshotsNestedInput
}

export type DeliverySnapshotUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deliveryVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  htmlObjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  screenshotObjectKey?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeliverySnapshotCreateManyInput = {
  id?: string
  deliveryVersionId: string
  htmlObjectKey: string
  screenshotObjectKey?: string | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type DeliverySnapshotUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  htmlObjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  screenshotObjectKey?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeliverySnapshotUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  deliveryVersionId?: Prisma.StringFieldUpdateOperationsInput | string
  htmlObjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  screenshotObjectKey?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeliverySnapshotListRelationFilter = {
  every?: Prisma.DeliverySnapshotWhereInput
  some?: Prisma.DeliverySnapshotWhereInput
  none?: Prisma.DeliverySnapshotWhereInput
}

export type DeliverySnapshotOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DeliverySnapshotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deliveryVersionId?: Prisma.SortOrder
  htmlObjectKey?: Prisma.SortOrder
  screenshotObjectKey?: Prisma.SortOrder
  responseHeaders?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DeliverySnapshotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deliveryVersionId?: Prisma.SortOrder
  htmlObjectKey?: Prisma.SortOrder
  screenshotObjectKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DeliverySnapshotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  deliveryVersionId?: Prisma.SortOrder
  htmlObjectKey?: Prisma.SortOrder
  screenshotObjectKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type DeliverySnapshotCreateNestedManyWithoutDeliveryVersionInput = {
  create?:
    | Prisma.XOR<
        Prisma.DeliverySnapshotCreateWithoutDeliveryVersionInput,
        Prisma.DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput
      >
    | Prisma.DeliverySnapshotCreateWithoutDeliveryVersionInput[]
    | Prisma.DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput[]
  connectOrCreate?:
    | Prisma.DeliverySnapshotCreateOrConnectWithoutDeliveryVersionInput
    | Prisma.DeliverySnapshotCreateOrConnectWithoutDeliveryVersionInput[]
  createMany?: Prisma.DeliverySnapshotCreateManyDeliveryVersionInputEnvelope
  connect?:
    | Prisma.DeliverySnapshotWhereUniqueInput
    | Prisma.DeliverySnapshotWhereUniqueInput[]
}

export type DeliverySnapshotUncheckedCreateNestedManyWithoutDeliveryVersionInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.DeliverySnapshotCreateWithoutDeliveryVersionInput,
          Prisma.DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput
        >
      | Prisma.DeliverySnapshotCreateWithoutDeliveryVersionInput[]
      | Prisma.DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput[]
    connectOrCreate?:
      | Prisma.DeliverySnapshotCreateOrConnectWithoutDeliveryVersionInput
      | Prisma.DeliverySnapshotCreateOrConnectWithoutDeliveryVersionInput[]
    createMany?: Prisma.DeliverySnapshotCreateManyDeliveryVersionInputEnvelope
    connect?:
      | Prisma.DeliverySnapshotWhereUniqueInput
      | Prisma.DeliverySnapshotWhereUniqueInput[]
  }

export type DeliverySnapshotUpdateManyWithoutDeliveryVersionNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.DeliverySnapshotCreateWithoutDeliveryVersionInput,
        Prisma.DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput
      >
    | Prisma.DeliverySnapshotCreateWithoutDeliveryVersionInput[]
    | Prisma.DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput[]
  connectOrCreate?:
    | Prisma.DeliverySnapshotCreateOrConnectWithoutDeliveryVersionInput
    | Prisma.DeliverySnapshotCreateOrConnectWithoutDeliveryVersionInput[]
  upsert?:
    | Prisma.DeliverySnapshotUpsertWithWhereUniqueWithoutDeliveryVersionInput
    | Prisma.DeliverySnapshotUpsertWithWhereUniqueWithoutDeliveryVersionInput[]
  createMany?: Prisma.DeliverySnapshotCreateManyDeliveryVersionInputEnvelope
  set?:
    | Prisma.DeliverySnapshotWhereUniqueInput
    | Prisma.DeliverySnapshotWhereUniqueInput[]
  disconnect?:
    | Prisma.DeliverySnapshotWhereUniqueInput
    | Prisma.DeliverySnapshotWhereUniqueInput[]
  delete?:
    | Prisma.DeliverySnapshotWhereUniqueInput
    | Prisma.DeliverySnapshotWhereUniqueInput[]
  connect?:
    | Prisma.DeliverySnapshotWhereUniqueInput
    | Prisma.DeliverySnapshotWhereUniqueInput[]
  update?:
    | Prisma.DeliverySnapshotUpdateWithWhereUniqueWithoutDeliveryVersionInput
    | Prisma.DeliverySnapshotUpdateWithWhereUniqueWithoutDeliveryVersionInput[]
  updateMany?:
    | Prisma.DeliverySnapshotUpdateManyWithWhereWithoutDeliveryVersionInput
    | Prisma.DeliverySnapshotUpdateManyWithWhereWithoutDeliveryVersionInput[]
  deleteMany?:
    | Prisma.DeliverySnapshotScalarWhereInput
    | Prisma.DeliverySnapshotScalarWhereInput[]
}

export type DeliverySnapshotUncheckedUpdateManyWithoutDeliveryVersionNestedInput =
  {
    create?:
      | Prisma.XOR<
          Prisma.DeliverySnapshotCreateWithoutDeliveryVersionInput,
          Prisma.DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput
        >
      | Prisma.DeliverySnapshotCreateWithoutDeliveryVersionInput[]
      | Prisma.DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput[]
    connectOrCreate?:
      | Prisma.DeliverySnapshotCreateOrConnectWithoutDeliveryVersionInput
      | Prisma.DeliverySnapshotCreateOrConnectWithoutDeliveryVersionInput[]
    upsert?:
      | Prisma.DeliverySnapshotUpsertWithWhereUniqueWithoutDeliveryVersionInput
      | Prisma.DeliverySnapshotUpsertWithWhereUniqueWithoutDeliveryVersionInput[]
    createMany?: Prisma.DeliverySnapshotCreateManyDeliveryVersionInputEnvelope
    set?:
      | Prisma.DeliverySnapshotWhereUniqueInput
      | Prisma.DeliverySnapshotWhereUniqueInput[]
    disconnect?:
      | Prisma.DeliverySnapshotWhereUniqueInput
      | Prisma.DeliverySnapshotWhereUniqueInput[]
    delete?:
      | Prisma.DeliverySnapshotWhereUniqueInput
      | Prisma.DeliverySnapshotWhereUniqueInput[]
    connect?:
      | Prisma.DeliverySnapshotWhereUniqueInput
      | Prisma.DeliverySnapshotWhereUniqueInput[]
    update?:
      | Prisma.DeliverySnapshotUpdateWithWhereUniqueWithoutDeliveryVersionInput
      | Prisma.DeliverySnapshotUpdateWithWhereUniqueWithoutDeliveryVersionInput[]
    updateMany?:
      | Prisma.DeliverySnapshotUpdateManyWithWhereWithoutDeliveryVersionInput
      | Prisma.DeliverySnapshotUpdateManyWithWhereWithoutDeliveryVersionInput[]
    deleteMany?:
      | Prisma.DeliverySnapshotScalarWhereInput
      | Prisma.DeliverySnapshotScalarWhereInput[]
  }

export type DeliverySnapshotCreateWithoutDeliveryVersionInput = {
  id?: string
  htmlObjectKey: string
  screenshotObjectKey?: string | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput = {
  id?: string
  htmlObjectKey: string
  screenshotObjectKey?: string | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type DeliverySnapshotCreateOrConnectWithoutDeliveryVersionInput = {
  where: Prisma.DeliverySnapshotWhereUniqueInput
  create: Prisma.XOR<
    Prisma.DeliverySnapshotCreateWithoutDeliveryVersionInput,
    Prisma.DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput
  >
}

export type DeliverySnapshotCreateManyDeliveryVersionInputEnvelope = {
  data:
    | Prisma.DeliverySnapshotCreateManyDeliveryVersionInput
    | Prisma.DeliverySnapshotCreateManyDeliveryVersionInput[]
  skipDuplicates?: boolean
}

export type DeliverySnapshotUpsertWithWhereUniqueWithoutDeliveryVersionInput = {
  where: Prisma.DeliverySnapshotWhereUniqueInput
  update: Prisma.XOR<
    Prisma.DeliverySnapshotUpdateWithoutDeliveryVersionInput,
    Prisma.DeliverySnapshotUncheckedUpdateWithoutDeliveryVersionInput
  >
  create: Prisma.XOR<
    Prisma.DeliverySnapshotCreateWithoutDeliveryVersionInput,
    Prisma.DeliverySnapshotUncheckedCreateWithoutDeliveryVersionInput
  >
}

export type DeliverySnapshotUpdateWithWhereUniqueWithoutDeliveryVersionInput = {
  where: Prisma.DeliverySnapshotWhereUniqueInput
  data: Prisma.XOR<
    Prisma.DeliverySnapshotUpdateWithoutDeliveryVersionInput,
    Prisma.DeliverySnapshotUncheckedUpdateWithoutDeliveryVersionInput
  >
}

export type DeliverySnapshotUpdateManyWithWhereWithoutDeliveryVersionInput = {
  where: Prisma.DeliverySnapshotScalarWhereInput
  data: Prisma.XOR<
    Prisma.DeliverySnapshotUpdateManyMutationInput,
    Prisma.DeliverySnapshotUncheckedUpdateManyWithoutDeliveryVersionInput
  >
}

export type DeliverySnapshotScalarWhereInput = {
  AND?:
    | Prisma.DeliverySnapshotScalarWhereInput
    | Prisma.DeliverySnapshotScalarWhereInput[]
  OR?: Prisma.DeliverySnapshotScalarWhereInput[]
  NOT?:
    | Prisma.DeliverySnapshotScalarWhereInput
    | Prisma.DeliverySnapshotScalarWhereInput[]
  id?: Prisma.StringFilter<"DeliverySnapshot"> | string
  deliveryVersionId?: Prisma.StringFilter<"DeliverySnapshot"> | string
  htmlObjectKey?: Prisma.StringFilter<"DeliverySnapshot"> | string
  screenshotObjectKey?:
    | Prisma.StringNullableFilter<"DeliverySnapshot">
    | string
    | null
  responseHeaders?: Prisma.JsonNullableFilter<"DeliverySnapshot">
  createdAt?: Prisma.DateTimeFilter<"DeliverySnapshot"> | Date | string
}

export type DeliverySnapshotCreateManyDeliveryVersionInput = {
  id?: string
  htmlObjectKey: string
  screenshotObjectKey?: string | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type DeliverySnapshotUpdateWithoutDeliveryVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  htmlObjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  screenshotObjectKey?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeliverySnapshotUncheckedUpdateWithoutDeliveryVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  htmlObjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  screenshotObjectKey?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeliverySnapshotUncheckedUpdateManyWithoutDeliveryVersionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  htmlObjectKey?: Prisma.StringFieldUpdateOperationsInput | string
  screenshotObjectKey?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  responseHeaders?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type DeliverySnapshotSelect<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    deliveryVersionId?: boolean
    htmlObjectKey?: boolean
    screenshotObjectKey?: boolean
    responseHeaders?: boolean
    createdAt?: boolean
    deliveryVersion?: boolean | Prisma.OrderDeliveryVersionDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["deliverySnapshot"]
>

export type DeliverySnapshotSelectCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    deliveryVersionId?: boolean
    htmlObjectKey?: boolean
    screenshotObjectKey?: boolean
    responseHeaders?: boolean
    createdAt?: boolean
    deliveryVersion?: boolean | Prisma.OrderDeliveryVersionDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["deliverySnapshot"]
>

export type DeliverySnapshotSelectUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    deliveryVersionId?: boolean
    htmlObjectKey?: boolean
    screenshotObjectKey?: boolean
    responseHeaders?: boolean
    createdAt?: boolean
    deliveryVersion?: boolean | Prisma.OrderDeliveryVersionDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["deliverySnapshot"]
>

export type DeliverySnapshotSelectScalar = {
  id?: boolean
  deliveryVersionId?: boolean
  htmlObjectKey?: boolean
  screenshotObjectKey?: boolean
  responseHeaders?: boolean
  createdAt?: boolean
}

export type DeliverySnapshotOmit<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | "id"
  | "deliveryVersionId"
  | "htmlObjectKey"
  | "screenshotObjectKey"
  | "responseHeaders"
  | "createdAt",
  ExtArgs["result"]["deliverySnapshot"]
>
export type DeliverySnapshotInclude<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  deliveryVersion?: boolean | Prisma.OrderDeliveryVersionDefaultArgs<ExtArgs>
}
export type DeliverySnapshotIncludeCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  deliveryVersion?: boolean | Prisma.OrderDeliveryVersionDefaultArgs<ExtArgs>
}
export type DeliverySnapshotIncludeUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  deliveryVersion?: boolean | Prisma.OrderDeliveryVersionDefaultArgs<ExtArgs>
}

export type $DeliverySnapshotPayload<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: "DeliverySnapshot"
  objects: {
    deliveryVersion: Prisma.$OrderDeliveryVersionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      deliveryVersionId: string
      htmlObjectKey: string
      screenshotObjectKey: string | null
      responseHeaders: runtime.JsonValue | null
      createdAt: Date
    },
    ExtArgs["result"]["deliverySnapshot"]
  >
  composites: {}
}

export type DeliverySnapshotGetPayload<
  S extends boolean | null | undefined | DeliverySnapshotDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$DeliverySnapshotPayload, S>

export type DeliverySnapshotCountArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<
  DeliverySnapshotFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: DeliverySnapshotCountAggregateInputType | true
}

export interface DeliverySnapshotDelegate<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["DeliverySnapshot"]
    meta: { name: "DeliverySnapshot" }
  }
  /**
   * Find zero or one DeliverySnapshot that matches the filter.
   * @param {DeliverySnapshotFindUniqueArgs} args - Arguments to find a DeliverySnapshot
   * @example
   * // Get one DeliverySnapshot
   * const deliverySnapshot = await prisma.deliverySnapshot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DeliverySnapshotFindUniqueArgs>(
    args: Prisma.SelectSubset<T, DeliverySnapshotFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__DeliverySnapshotClient<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one DeliverySnapshot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DeliverySnapshotFindUniqueOrThrowArgs} args - Arguments to find a DeliverySnapshot
   * @example
   * // Get one DeliverySnapshot
   * const deliverySnapshot = await prisma.deliverySnapshot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DeliverySnapshotFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<
      T,
      DeliverySnapshotFindUniqueOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__DeliverySnapshotClient<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first DeliverySnapshot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeliverySnapshotFindFirstArgs} args - Arguments to find a DeliverySnapshot
   * @example
   * // Get one DeliverySnapshot
   * const deliverySnapshot = await prisma.deliverySnapshot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DeliverySnapshotFindFirstArgs>(
    args?: Prisma.SelectSubset<T, DeliverySnapshotFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__DeliverySnapshotClient<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first DeliverySnapshot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeliverySnapshotFindFirstOrThrowArgs} args - Arguments to find a DeliverySnapshot
   * @example
   * // Get one DeliverySnapshot
   * const deliverySnapshot = await prisma.deliverySnapshot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DeliverySnapshotFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<
      T,
      DeliverySnapshotFindFirstOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__DeliverySnapshotClient<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more DeliverySnapshots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeliverySnapshotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DeliverySnapshots
   * const deliverySnapshots = await prisma.deliverySnapshot.findMany()
   *
   * // Get first 10 DeliverySnapshots
   * const deliverySnapshots = await prisma.deliverySnapshot.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const deliverySnapshotWithIdOnly = await prisma.deliverySnapshot.findMany({ select: { id: true } })
   *
   */
  findMany<T extends DeliverySnapshotFindManyArgs>(
    args?: Prisma.SelectSubset<T, DeliverySnapshotFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >

  /**
   * Create a DeliverySnapshot.
   * @param {DeliverySnapshotCreateArgs} args - Arguments to create a DeliverySnapshot.
   * @example
   * // Create one DeliverySnapshot
   * const DeliverySnapshot = await prisma.deliverySnapshot.create({
   *   data: {
   *     // ... data to create a DeliverySnapshot
   *   }
   * })
   *
   */
  create<T extends DeliverySnapshotCreateArgs>(
    args: Prisma.SelectSubset<T, DeliverySnapshotCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__DeliverySnapshotClient<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many DeliverySnapshots.
   * @param {DeliverySnapshotCreateManyArgs} args - Arguments to create many DeliverySnapshots.
   * @example
   * // Create many DeliverySnapshots
   * const deliverySnapshot = await prisma.deliverySnapshot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends DeliverySnapshotCreateManyArgs>(
    args?: Prisma.SelectSubset<T, DeliverySnapshotCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DeliverySnapshots and returns the data saved in the database.
   * @param {DeliverySnapshotCreateManyAndReturnArgs} args - Arguments to create many DeliverySnapshots.
   * @example
   * // Create many DeliverySnapshots
   * const deliverySnapshot = await prisma.deliverySnapshot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many DeliverySnapshots and only return the `id`
   * const deliverySnapshotWithIdOnly = await prisma.deliverySnapshot.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends DeliverySnapshotCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      DeliverySnapshotCreateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Delete a DeliverySnapshot.
   * @param {DeliverySnapshotDeleteArgs} args - Arguments to delete one DeliverySnapshot.
   * @example
   * // Delete one DeliverySnapshot
   * const DeliverySnapshot = await prisma.deliverySnapshot.delete({
   *   where: {
   *     // ... filter to delete one DeliverySnapshot
   *   }
   * })
   *
   */
  delete<T extends DeliverySnapshotDeleteArgs>(
    args: Prisma.SelectSubset<T, DeliverySnapshotDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__DeliverySnapshotClient<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one DeliverySnapshot.
   * @param {DeliverySnapshotUpdateArgs} args - Arguments to update one DeliverySnapshot.
   * @example
   * // Update one DeliverySnapshot
   * const deliverySnapshot = await prisma.deliverySnapshot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends DeliverySnapshotUpdateArgs>(
    args: Prisma.SelectSubset<T, DeliverySnapshotUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__DeliverySnapshotClient<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more DeliverySnapshots.
   * @param {DeliverySnapshotDeleteManyArgs} args - Arguments to filter DeliverySnapshots to delete.
   * @example
   * // Delete a few DeliverySnapshots
   * const { count } = await prisma.deliverySnapshot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends DeliverySnapshotDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, DeliverySnapshotDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DeliverySnapshots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeliverySnapshotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DeliverySnapshots
   * const deliverySnapshot = await prisma.deliverySnapshot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends DeliverySnapshotUpdateManyArgs>(
    args: Prisma.SelectSubset<T, DeliverySnapshotUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DeliverySnapshots and returns the data updated in the database.
   * @param {DeliverySnapshotUpdateManyAndReturnArgs} args - Arguments to update many DeliverySnapshots.
   * @example
   * // Update many DeliverySnapshots
   * const deliverySnapshot = await prisma.deliverySnapshot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more DeliverySnapshots and only return the `id`
   * const deliverySnapshotWithIdOnly = await prisma.deliverySnapshot.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends DeliverySnapshotUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      DeliverySnapshotUpdateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one DeliverySnapshot.
   * @param {DeliverySnapshotUpsertArgs} args - Arguments to update or create a DeliverySnapshot.
   * @example
   * // Update or create a DeliverySnapshot
   * const deliverySnapshot = await prisma.deliverySnapshot.upsert({
   *   create: {
   *     // ... data to create a DeliverySnapshot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DeliverySnapshot we want to update
   *   }
   * })
   */
  upsert<T extends DeliverySnapshotUpsertArgs>(
    args: Prisma.SelectSubset<T, DeliverySnapshotUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__DeliverySnapshotClient<
    runtime.Types.Result.GetResult<
      Prisma.$DeliverySnapshotPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of DeliverySnapshots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeliverySnapshotCountArgs} args - Arguments to filter DeliverySnapshots to count.
   * @example
   * // Count the number of DeliverySnapshots
   * const count = await prisma.deliverySnapshot.count({
   *   where: {
   *     // ... the filter for the DeliverySnapshots we want to count
   *   }
   * })
   **/
  count<T extends DeliverySnapshotCountArgs>(
    args?: Prisma.Subset<T, DeliverySnapshotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<
            T["select"],
            DeliverySnapshotCountAggregateOutputType
          >
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DeliverySnapshot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeliverySnapshotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends DeliverySnapshotAggregateArgs>(
    args: Prisma.Subset<T, DeliverySnapshotAggregateArgs>,
  ): Prisma.PrismaPromise<GetDeliverySnapshotAggregateType<T>>

  /**
   * Group by DeliverySnapshot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DeliverySnapshotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends DeliverySnapshotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DeliverySnapshotGroupByArgs["orderBy"] }
      : { orderBy?: DeliverySnapshotGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ]
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<
      T,
      DeliverySnapshotGroupByArgs,
      OrderByArg
    > &
      InputErrors,
  ): {} extends InputErrors
    ? GetDeliverySnapshotGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the DeliverySnapshot model
   */
  readonly fields: DeliverySnapshotFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for DeliverySnapshot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DeliverySnapshotClient<
  T,
  Null = never,
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  deliveryVersion<
    T extends Prisma.OrderDeliveryVersionDefaultArgs<ExtArgs> = {},
  >(
    args?: Prisma.Subset<T, Prisma.OrderDeliveryVersionDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__OrderDeliveryVersionClient<
    | runtime.Types.Result.GetResult<
        Prisma.$OrderDeliveryVersionPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the DeliverySnapshot model
 */
export interface DeliverySnapshotFieldRefs {
  readonly id: Prisma.FieldRef<"DeliverySnapshot", "String">
  readonly deliveryVersionId: Prisma.FieldRef<"DeliverySnapshot", "String">
  readonly htmlObjectKey: Prisma.FieldRef<"DeliverySnapshot", "String">
  readonly screenshotObjectKey: Prisma.FieldRef<"DeliverySnapshot", "String">
  readonly responseHeaders: Prisma.FieldRef<"DeliverySnapshot", "Json">
  readonly createdAt: Prisma.FieldRef<"DeliverySnapshot", "DateTime">
}

// Custom InputTypes
/**
 * DeliverySnapshot findUnique
 */
export type DeliverySnapshotFindUniqueArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotInclude<ExtArgs> | null
  /**
   * Filter, which DeliverySnapshot to fetch.
   */
  where: Prisma.DeliverySnapshotWhereUniqueInput
}

/**
 * DeliverySnapshot findUniqueOrThrow
 */
export type DeliverySnapshotFindUniqueOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotInclude<ExtArgs> | null
  /**
   * Filter, which DeliverySnapshot to fetch.
   */
  where: Prisma.DeliverySnapshotWhereUniqueInput
}

/**
 * DeliverySnapshot findFirst
 */
export type DeliverySnapshotFindFirstArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotInclude<ExtArgs> | null
  /**
   * Filter, which DeliverySnapshot to fetch.
   */
  where?: Prisma.DeliverySnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of DeliverySnapshots to fetch.
   */
  orderBy?:
    | Prisma.DeliverySnapshotOrderByWithRelationInput
    | Prisma.DeliverySnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for DeliverySnapshots.
   */
  cursor?: Prisma.DeliverySnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` DeliverySnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` DeliverySnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of DeliverySnapshots.
   */
  distinct?:
    | Prisma.DeliverySnapshotScalarFieldEnum
    | Prisma.DeliverySnapshotScalarFieldEnum[]
}

/**
 * DeliverySnapshot findFirstOrThrow
 */
export type DeliverySnapshotFindFirstOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotInclude<ExtArgs> | null
  /**
   * Filter, which DeliverySnapshot to fetch.
   */
  where?: Prisma.DeliverySnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of DeliverySnapshots to fetch.
   */
  orderBy?:
    | Prisma.DeliverySnapshotOrderByWithRelationInput
    | Prisma.DeliverySnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for DeliverySnapshots.
   */
  cursor?: Prisma.DeliverySnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` DeliverySnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` DeliverySnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of DeliverySnapshots.
   */
  distinct?:
    | Prisma.DeliverySnapshotScalarFieldEnum
    | Prisma.DeliverySnapshotScalarFieldEnum[]
}

/**
 * DeliverySnapshot findMany
 */
export type DeliverySnapshotFindManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotInclude<ExtArgs> | null
  /**
   * Filter, which DeliverySnapshots to fetch.
   */
  where?: Prisma.DeliverySnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of DeliverySnapshots to fetch.
   */
  orderBy?:
    | Prisma.DeliverySnapshotOrderByWithRelationInput
    | Prisma.DeliverySnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing DeliverySnapshots.
   */
  cursor?: Prisma.DeliverySnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` DeliverySnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` DeliverySnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of DeliverySnapshots.
   */
  distinct?:
    | Prisma.DeliverySnapshotScalarFieldEnum
    | Prisma.DeliverySnapshotScalarFieldEnum[]
}

/**
 * DeliverySnapshot create
 */
export type DeliverySnapshotCreateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotInclude<ExtArgs> | null
  /**
   * The data needed to create a DeliverySnapshot.
   */
  data: Prisma.XOR<
    Prisma.DeliverySnapshotCreateInput,
    Prisma.DeliverySnapshotUncheckedCreateInput
  >
}

/**
 * DeliverySnapshot createMany
 */
export type DeliverySnapshotCreateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many DeliverySnapshots.
   */
  data:
    | Prisma.DeliverySnapshotCreateManyInput
    | Prisma.DeliverySnapshotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DeliverySnapshot createManyAndReturn
 */
export type DeliverySnapshotCreateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * The data used to create many DeliverySnapshots.
   */
  data:
    | Prisma.DeliverySnapshotCreateManyInput
    | Prisma.DeliverySnapshotCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * DeliverySnapshot update
 */
export type DeliverySnapshotUpdateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotInclude<ExtArgs> | null
  /**
   * The data needed to update a DeliverySnapshot.
   */
  data: Prisma.XOR<
    Prisma.DeliverySnapshotUpdateInput,
    Prisma.DeliverySnapshotUncheckedUpdateInput
  >
  /**
   * Choose, which DeliverySnapshot to update.
   */
  where: Prisma.DeliverySnapshotWhereUniqueInput
}

/**
 * DeliverySnapshot updateMany
 */
export type DeliverySnapshotUpdateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update DeliverySnapshots.
   */
  data: Prisma.XOR<
    Prisma.DeliverySnapshotUpdateManyMutationInput,
    Prisma.DeliverySnapshotUncheckedUpdateManyInput
  >
  /**
   * Filter which DeliverySnapshots to update
   */
  where?: Prisma.DeliverySnapshotWhereInput
  /**
   * Limit how many DeliverySnapshots to update.
   */
  limit?: number
}

/**
 * DeliverySnapshot updateManyAndReturn
 */
export type DeliverySnapshotUpdateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * The data used to update DeliverySnapshots.
   */
  data: Prisma.XOR<
    Prisma.DeliverySnapshotUpdateManyMutationInput,
    Prisma.DeliverySnapshotUncheckedUpdateManyInput
  >
  /**
   * Filter which DeliverySnapshots to update
   */
  where?: Prisma.DeliverySnapshotWhereInput
  /**
   * Limit how many DeliverySnapshots to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * DeliverySnapshot upsert
 */
export type DeliverySnapshotUpsertArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotInclude<ExtArgs> | null
  /**
   * The filter to search for the DeliverySnapshot to update in case it exists.
   */
  where: Prisma.DeliverySnapshotWhereUniqueInput
  /**
   * In case the DeliverySnapshot found by the `where` argument doesn't exist, create a new DeliverySnapshot with this data.
   */
  create: Prisma.XOR<
    Prisma.DeliverySnapshotCreateInput,
    Prisma.DeliverySnapshotUncheckedCreateInput
  >
  /**
   * In case the DeliverySnapshot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.DeliverySnapshotUpdateInput,
    Prisma.DeliverySnapshotUncheckedUpdateInput
  >
}

/**
 * DeliverySnapshot delete
 */
export type DeliverySnapshotDeleteArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotInclude<ExtArgs> | null
  /**
   * Filter which DeliverySnapshot to delete.
   */
  where: Prisma.DeliverySnapshotWhereUniqueInput
}

/**
 * DeliverySnapshot deleteMany
 */
export type DeliverySnapshotDeleteManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which DeliverySnapshots to delete
   */
  where?: Prisma.DeliverySnapshotWhereInput
  /**
   * Limit how many DeliverySnapshots to delete.
   */
  limit?: number
}

/**
 * DeliverySnapshot without action
 */
export type DeliverySnapshotDefaultArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DeliverySnapshot
   */
  select?: Prisma.DeliverySnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliverySnapshot
   */
  omit?: Prisma.DeliverySnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DeliverySnapshotInclude<ExtArgs> | null
}
