/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `FulfillmentAssignment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FulfillmentAssignment
 *
 */
export type FulfillmentAssignmentModel =
  runtime.Types.Result.DefaultSelection<Prisma.$FulfillmentAssignmentPayload>

export type AggregateFulfillmentAssignment = {
  _count: FulfillmentAssignmentCountAggregateOutputType | null
  _avg: FulfillmentAssignmentAvgAggregateOutputType | null
  _sum: FulfillmentAssignmentSumAggregateOutputType | null
  _min: FulfillmentAssignmentMinAggregateOutputType | null
  _max: FulfillmentAssignmentMaxAggregateOutputType | null
}

export type FulfillmentAssignmentAvgAggregateOutputType = {
  version: number | null
}

export type FulfillmentAssignmentSumAggregateOutputType = {
  version: number | null
}

export type FulfillmentAssignmentMinAggregateOutputType = {
  id: string | null
  orderId: string | null
  assignedToUserId: string | null
  assignedByUserId: string | null
  assignedAt: Date | null
  completedAt: Date | null
  status: $Enums.FulfillmentAssignmentStatus | null
  version: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FulfillmentAssignmentMaxAggregateOutputType = {
  id: string | null
  orderId: string | null
  assignedToUserId: string | null
  assignedByUserId: string | null
  assignedAt: Date | null
  completedAt: Date | null
  status: $Enums.FulfillmentAssignmentStatus | null
  version: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FulfillmentAssignmentCountAggregateOutputType = {
  id: number
  orderId: number
  assignedToUserId: number
  assignedByUserId: number
  assignedAt: number
  completedAt: number
  status: number
  version: number
  createdAt: number
  updatedAt: number
  _all: number
}

export type FulfillmentAssignmentAvgAggregateInputType = {
  version?: true
}

export type FulfillmentAssignmentSumAggregateInputType = {
  version?: true
}

export type FulfillmentAssignmentMinAggregateInputType = {
  id?: true
  orderId?: true
  assignedToUserId?: true
  assignedByUserId?: true
  assignedAt?: true
  completedAt?: true
  status?: true
  version?: true
  createdAt?: true
  updatedAt?: true
}

export type FulfillmentAssignmentMaxAggregateInputType = {
  id?: true
  orderId?: true
  assignedToUserId?: true
  assignedByUserId?: true
  assignedAt?: true
  completedAt?: true
  status?: true
  version?: true
  createdAt?: true
  updatedAt?: true
}

export type FulfillmentAssignmentCountAggregateInputType = {
  id?: true
  orderId?: true
  assignedToUserId?: true
  assignedByUserId?: true
  assignedAt?: true
  completedAt?: true
  status?: true
  version?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FulfillmentAssignmentAggregateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which FulfillmentAssignment to aggregate.
   */
  where?: Prisma.FulfillmentAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of FulfillmentAssignments to fetch.
   */
  orderBy?:
    | Prisma.FulfillmentAssignmentOrderByWithRelationInput
    | Prisma.FulfillmentAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.FulfillmentAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` FulfillmentAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` FulfillmentAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned FulfillmentAssignments
   **/
  _count?: true | FulfillmentAssignmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: FulfillmentAssignmentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: FulfillmentAssignmentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: FulfillmentAssignmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: FulfillmentAssignmentMaxAggregateInputType
}

export type GetFulfillmentAssignmentAggregateType<
  T extends FulfillmentAssignmentAggregateArgs,
> = {
  [P in keyof T & keyof AggregateFulfillmentAssignment]: P extends
    | "_count"
    | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFulfillmentAssignment[P]>
    : Prisma.GetScalarType<T[P], AggregateFulfillmentAssignment[P]>
}

export type FulfillmentAssignmentGroupByArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.FulfillmentAssignmentWhereInput
  orderBy?:
    | Prisma.FulfillmentAssignmentOrderByWithAggregationInput
    | Prisma.FulfillmentAssignmentOrderByWithAggregationInput[]
  by:
    | Prisma.FulfillmentAssignmentScalarFieldEnum[]
    | Prisma.FulfillmentAssignmentScalarFieldEnum
  having?: Prisma.FulfillmentAssignmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FulfillmentAssignmentCountAggregateInputType | true
  _avg?: FulfillmentAssignmentAvgAggregateInputType
  _sum?: FulfillmentAssignmentSumAggregateInputType
  _min?: FulfillmentAssignmentMinAggregateInputType
  _max?: FulfillmentAssignmentMaxAggregateInputType
}

export type FulfillmentAssignmentGroupByOutputType = {
  id: string
  orderId: string
  assignedToUserId: string
  assignedByUserId: string
  assignedAt: Date
  completedAt: Date | null
  status: $Enums.FulfillmentAssignmentStatus
  version: number
  createdAt: Date
  updatedAt: Date
  _count: FulfillmentAssignmentCountAggregateOutputType | null
  _avg: FulfillmentAssignmentAvgAggregateOutputType | null
  _sum: FulfillmentAssignmentSumAggregateOutputType | null
  _min: FulfillmentAssignmentMinAggregateOutputType | null
  _max: FulfillmentAssignmentMaxAggregateOutputType | null
}

export type GetFulfillmentAssignmentGroupByPayload<
  T extends FulfillmentAssignmentGroupByArgs,
> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FulfillmentAssignmentGroupByOutputType, T["by"]> & {
      [P in keyof T &
        keyof FulfillmentAssignmentGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<
              T[P],
              FulfillmentAssignmentGroupByOutputType[P]
            >
        : Prisma.GetScalarType<T[P], FulfillmentAssignmentGroupByOutputType[P]>
    }
  >
>

export type FulfillmentAssignmentWhereInput = {
  AND?:
    | Prisma.FulfillmentAssignmentWhereInput
    | Prisma.FulfillmentAssignmentWhereInput[]
  OR?: Prisma.FulfillmentAssignmentWhereInput[]
  NOT?:
    | Prisma.FulfillmentAssignmentWhereInput
    | Prisma.FulfillmentAssignmentWhereInput[]
  id?: Prisma.StringFilter<"FulfillmentAssignment"> | string
  orderId?: Prisma.StringFilter<"FulfillmentAssignment"> | string
  assignedToUserId?: Prisma.StringFilter<"FulfillmentAssignment"> | string
  assignedByUserId?: Prisma.StringFilter<"FulfillmentAssignment"> | string
  assignedAt?: Prisma.DateTimeFilter<"FulfillmentAssignment"> | Date | string
  completedAt?:
    | Prisma.DateTimeNullableFilter<"FulfillmentAssignment">
    | Date
    | string
    | null
  status?:
    | Prisma.EnumFulfillmentAssignmentStatusFilter<"FulfillmentAssignment">
    | $Enums.FulfillmentAssignmentStatus
  version?: Prisma.IntFilter<"FulfillmentAssignment"> | number
  createdAt?: Prisma.DateTimeFilter<"FulfillmentAssignment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FulfillmentAssignment"> | Date | string
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
}

export type FulfillmentAssignmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  assignedToUserId?: Prisma.SortOrder
  assignedByUserId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  order?: Prisma.OrderOrderByWithRelationInput
}

export type FulfillmentAssignmentWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?:
      | Prisma.FulfillmentAssignmentWhereInput
      | Prisma.FulfillmentAssignmentWhereInput[]
    OR?: Prisma.FulfillmentAssignmentWhereInput[]
    NOT?:
      | Prisma.FulfillmentAssignmentWhereInput
      | Prisma.FulfillmentAssignmentWhereInput[]
    orderId?: Prisma.StringFilter<"FulfillmentAssignment"> | string
    assignedToUserId?: Prisma.StringFilter<"FulfillmentAssignment"> | string
    assignedByUserId?: Prisma.StringFilter<"FulfillmentAssignment"> | string
    assignedAt?: Prisma.DateTimeFilter<"FulfillmentAssignment"> | Date | string
    completedAt?:
      | Prisma.DateTimeNullableFilter<"FulfillmentAssignment">
      | Date
      | string
      | null
    status?:
      | Prisma.EnumFulfillmentAssignmentStatusFilter<"FulfillmentAssignment">
      | $Enums.FulfillmentAssignmentStatus
    version?: Prisma.IntFilter<"FulfillmentAssignment"> | number
    createdAt?: Prisma.DateTimeFilter<"FulfillmentAssignment"> | Date | string
    updatedAt?: Prisma.DateTimeFilter<"FulfillmentAssignment"> | Date | string
    order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
  },
  "id"
>

export type FulfillmentAssignmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  assignedToUserId?: Prisma.SortOrder
  assignedByUserId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FulfillmentAssignmentCountOrderByAggregateInput
  _avg?: Prisma.FulfillmentAssignmentAvgOrderByAggregateInput
  _max?: Prisma.FulfillmentAssignmentMaxOrderByAggregateInput
  _min?: Prisma.FulfillmentAssignmentMinOrderByAggregateInput
  _sum?: Prisma.FulfillmentAssignmentSumOrderByAggregateInput
}

export type FulfillmentAssignmentScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.FulfillmentAssignmentScalarWhereWithAggregatesInput
    | Prisma.FulfillmentAssignmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.FulfillmentAssignmentScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.FulfillmentAssignmentScalarWhereWithAggregatesInput
    | Prisma.FulfillmentAssignmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FulfillmentAssignment"> | string
  orderId?: Prisma.StringWithAggregatesFilter<"FulfillmentAssignment"> | string
  assignedToUserId?:
    | Prisma.StringWithAggregatesFilter<"FulfillmentAssignment">
    | string
  assignedByUserId?:
    | Prisma.StringWithAggregatesFilter<"FulfillmentAssignment">
    | string
  assignedAt?:
    | Prisma.DateTimeWithAggregatesFilter<"FulfillmentAssignment">
    | Date
    | string
  completedAt?:
    | Prisma.DateTimeNullableWithAggregatesFilter<"FulfillmentAssignment">
    | Date
    | string
    | null
  status?:
    | Prisma.EnumFulfillmentAssignmentStatusWithAggregatesFilter<"FulfillmentAssignment">
    | $Enums.FulfillmentAssignmentStatus
  version?: Prisma.IntWithAggregatesFilter<"FulfillmentAssignment"> | number
  createdAt?:
    | Prisma.DateTimeWithAggregatesFilter<"FulfillmentAssignment">
    | Date
    | string
  updatedAt?:
    | Prisma.DateTimeWithAggregatesFilter<"FulfillmentAssignment">
    | Date
    | string
}

export type FulfillmentAssignmentCreateInput = {
  id?: string
  assignedToUserId: string
  assignedByUserId: string
  assignedAt?: Date | string
  completedAt?: Date | string | null
  status?: $Enums.FulfillmentAssignmentStatus
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  order: Prisma.OrderCreateNestedOneWithoutFulfillmentAssignmentsInput
}

export type FulfillmentAssignmentUncheckedCreateInput = {
  id?: string
  orderId: string
  assignedToUserId: string
  assignedByUserId: string
  assignedAt?: Date | string
  completedAt?: Date | string | null
  status?: $Enums.FulfillmentAssignmentStatus
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FulfillmentAssignmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedToUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null
  status?:
    | Prisma.EnumFulfillmentAssignmentStatusFieldUpdateOperationsInput
    | $Enums.FulfillmentAssignmentStatus
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  order?: Prisma.OrderUpdateOneRequiredWithoutFulfillmentAssignmentsNestedInput
}

export type FulfillmentAssignmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedToUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null
  status?:
    | Prisma.EnumFulfillmentAssignmentStatusFieldUpdateOperationsInput
    | $Enums.FulfillmentAssignmentStatus
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FulfillmentAssignmentCreateManyInput = {
  id?: string
  orderId: string
  assignedToUserId: string
  assignedByUserId: string
  assignedAt?: Date | string
  completedAt?: Date | string | null
  status?: $Enums.FulfillmentAssignmentStatus
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FulfillmentAssignmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedToUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null
  status?:
    | Prisma.EnumFulfillmentAssignmentStatusFieldUpdateOperationsInput
    | $Enums.FulfillmentAssignmentStatus
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FulfillmentAssignmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedToUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null
  status?:
    | Prisma.EnumFulfillmentAssignmentStatusFieldUpdateOperationsInput
    | $Enums.FulfillmentAssignmentStatus
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FulfillmentAssignmentListRelationFilter = {
  every?: Prisma.FulfillmentAssignmentWhereInput
  some?: Prisma.FulfillmentAssignmentWhereInput
  none?: Prisma.FulfillmentAssignmentWhereInput
}

export type FulfillmentAssignmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FulfillmentAssignmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  assignedToUserId?: Prisma.SortOrder
  assignedByUserId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FulfillmentAssignmentAvgOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type FulfillmentAssignmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  assignedToUserId?: Prisma.SortOrder
  assignedByUserId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FulfillmentAssignmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  assignedToUserId?: Prisma.SortOrder
  assignedByUserId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  version?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FulfillmentAssignmentSumOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type FulfillmentAssignmentCreateNestedManyWithoutOrderInput = {
  create?:
    | Prisma.XOR<
        Prisma.FulfillmentAssignmentCreateWithoutOrderInput,
        Prisma.FulfillmentAssignmentUncheckedCreateWithoutOrderInput
      >
    | Prisma.FulfillmentAssignmentCreateWithoutOrderInput[]
    | Prisma.FulfillmentAssignmentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?:
    | Prisma.FulfillmentAssignmentCreateOrConnectWithoutOrderInput
    | Prisma.FulfillmentAssignmentCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.FulfillmentAssignmentCreateManyOrderInputEnvelope
  connect?:
    | Prisma.FulfillmentAssignmentWhereUniqueInput
    | Prisma.FulfillmentAssignmentWhereUniqueInput[]
}

export type FulfillmentAssignmentUncheckedCreateNestedManyWithoutOrderInput = {
  create?:
    | Prisma.XOR<
        Prisma.FulfillmentAssignmentCreateWithoutOrderInput,
        Prisma.FulfillmentAssignmentUncheckedCreateWithoutOrderInput
      >
    | Prisma.FulfillmentAssignmentCreateWithoutOrderInput[]
    | Prisma.FulfillmentAssignmentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?:
    | Prisma.FulfillmentAssignmentCreateOrConnectWithoutOrderInput
    | Prisma.FulfillmentAssignmentCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.FulfillmentAssignmentCreateManyOrderInputEnvelope
  connect?:
    | Prisma.FulfillmentAssignmentWhereUniqueInput
    | Prisma.FulfillmentAssignmentWhereUniqueInput[]
}

export type FulfillmentAssignmentUpdateManyWithoutOrderNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.FulfillmentAssignmentCreateWithoutOrderInput,
        Prisma.FulfillmentAssignmentUncheckedCreateWithoutOrderInput
      >
    | Prisma.FulfillmentAssignmentCreateWithoutOrderInput[]
    | Prisma.FulfillmentAssignmentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?:
    | Prisma.FulfillmentAssignmentCreateOrConnectWithoutOrderInput
    | Prisma.FulfillmentAssignmentCreateOrConnectWithoutOrderInput[]
  upsert?:
    | Prisma.FulfillmentAssignmentUpsertWithWhereUniqueWithoutOrderInput
    | Prisma.FulfillmentAssignmentUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.FulfillmentAssignmentCreateManyOrderInputEnvelope
  set?:
    | Prisma.FulfillmentAssignmentWhereUniqueInput
    | Prisma.FulfillmentAssignmentWhereUniqueInput[]
  disconnect?:
    | Prisma.FulfillmentAssignmentWhereUniqueInput
    | Prisma.FulfillmentAssignmentWhereUniqueInput[]
  delete?:
    | Prisma.FulfillmentAssignmentWhereUniqueInput
    | Prisma.FulfillmentAssignmentWhereUniqueInput[]
  connect?:
    | Prisma.FulfillmentAssignmentWhereUniqueInput
    | Prisma.FulfillmentAssignmentWhereUniqueInput[]
  update?:
    | Prisma.FulfillmentAssignmentUpdateWithWhereUniqueWithoutOrderInput
    | Prisma.FulfillmentAssignmentUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?:
    | Prisma.FulfillmentAssignmentUpdateManyWithWhereWithoutOrderInput
    | Prisma.FulfillmentAssignmentUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?:
    | Prisma.FulfillmentAssignmentScalarWhereInput
    | Prisma.FulfillmentAssignmentScalarWhereInput[]
}

export type FulfillmentAssignmentUncheckedUpdateManyWithoutOrderNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.FulfillmentAssignmentCreateWithoutOrderInput,
        Prisma.FulfillmentAssignmentUncheckedCreateWithoutOrderInput
      >
    | Prisma.FulfillmentAssignmentCreateWithoutOrderInput[]
    | Prisma.FulfillmentAssignmentUncheckedCreateWithoutOrderInput[]
  connectOrCreate?:
    | Prisma.FulfillmentAssignmentCreateOrConnectWithoutOrderInput
    | Prisma.FulfillmentAssignmentCreateOrConnectWithoutOrderInput[]
  upsert?:
    | Prisma.FulfillmentAssignmentUpsertWithWhereUniqueWithoutOrderInput
    | Prisma.FulfillmentAssignmentUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.FulfillmentAssignmentCreateManyOrderInputEnvelope
  set?:
    | Prisma.FulfillmentAssignmentWhereUniqueInput
    | Prisma.FulfillmentAssignmentWhereUniqueInput[]
  disconnect?:
    | Prisma.FulfillmentAssignmentWhereUniqueInput
    | Prisma.FulfillmentAssignmentWhereUniqueInput[]
  delete?:
    | Prisma.FulfillmentAssignmentWhereUniqueInput
    | Prisma.FulfillmentAssignmentWhereUniqueInput[]
  connect?:
    | Prisma.FulfillmentAssignmentWhereUniqueInput
    | Prisma.FulfillmentAssignmentWhereUniqueInput[]
  update?:
    | Prisma.FulfillmentAssignmentUpdateWithWhereUniqueWithoutOrderInput
    | Prisma.FulfillmentAssignmentUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?:
    | Prisma.FulfillmentAssignmentUpdateManyWithWhereWithoutOrderInput
    | Prisma.FulfillmentAssignmentUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?:
    | Prisma.FulfillmentAssignmentScalarWhereInput
    | Prisma.FulfillmentAssignmentScalarWhereInput[]
}

export type EnumFulfillmentAssignmentStatusFieldUpdateOperationsInput = {
  set?: $Enums.FulfillmentAssignmentStatus
}

export type FulfillmentAssignmentCreateWithoutOrderInput = {
  id?: string
  assignedToUserId: string
  assignedByUserId: string
  assignedAt?: Date | string
  completedAt?: Date | string | null
  status?: $Enums.FulfillmentAssignmentStatus
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FulfillmentAssignmentUncheckedCreateWithoutOrderInput = {
  id?: string
  assignedToUserId: string
  assignedByUserId: string
  assignedAt?: Date | string
  completedAt?: Date | string | null
  status?: $Enums.FulfillmentAssignmentStatus
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FulfillmentAssignmentCreateOrConnectWithoutOrderInput = {
  where: Prisma.FulfillmentAssignmentWhereUniqueInput
  create: Prisma.XOR<
    Prisma.FulfillmentAssignmentCreateWithoutOrderInput,
    Prisma.FulfillmentAssignmentUncheckedCreateWithoutOrderInput
  >
}

export type FulfillmentAssignmentCreateManyOrderInputEnvelope = {
  data:
    | Prisma.FulfillmentAssignmentCreateManyOrderInput
    | Prisma.FulfillmentAssignmentCreateManyOrderInput[]
  skipDuplicates?: boolean
}

export type FulfillmentAssignmentUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.FulfillmentAssignmentWhereUniqueInput
  update: Prisma.XOR<
    Prisma.FulfillmentAssignmentUpdateWithoutOrderInput,
    Prisma.FulfillmentAssignmentUncheckedUpdateWithoutOrderInput
  >
  create: Prisma.XOR<
    Prisma.FulfillmentAssignmentCreateWithoutOrderInput,
    Prisma.FulfillmentAssignmentUncheckedCreateWithoutOrderInput
  >
}

export type FulfillmentAssignmentUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.FulfillmentAssignmentWhereUniqueInput
  data: Prisma.XOR<
    Prisma.FulfillmentAssignmentUpdateWithoutOrderInput,
    Prisma.FulfillmentAssignmentUncheckedUpdateWithoutOrderInput
  >
}

export type FulfillmentAssignmentUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.FulfillmentAssignmentScalarWhereInput
  data: Prisma.XOR<
    Prisma.FulfillmentAssignmentUpdateManyMutationInput,
    Prisma.FulfillmentAssignmentUncheckedUpdateManyWithoutOrderInput
  >
}

export type FulfillmentAssignmentScalarWhereInput = {
  AND?:
    | Prisma.FulfillmentAssignmentScalarWhereInput
    | Prisma.FulfillmentAssignmentScalarWhereInput[]
  OR?: Prisma.FulfillmentAssignmentScalarWhereInput[]
  NOT?:
    | Prisma.FulfillmentAssignmentScalarWhereInput
    | Prisma.FulfillmentAssignmentScalarWhereInput[]
  id?: Prisma.StringFilter<"FulfillmentAssignment"> | string
  orderId?: Prisma.StringFilter<"FulfillmentAssignment"> | string
  assignedToUserId?: Prisma.StringFilter<"FulfillmentAssignment"> | string
  assignedByUserId?: Prisma.StringFilter<"FulfillmentAssignment"> | string
  assignedAt?: Prisma.DateTimeFilter<"FulfillmentAssignment"> | Date | string
  completedAt?:
    | Prisma.DateTimeNullableFilter<"FulfillmentAssignment">
    | Date
    | string
    | null
  status?:
    | Prisma.EnumFulfillmentAssignmentStatusFilter<"FulfillmentAssignment">
    | $Enums.FulfillmentAssignmentStatus
  version?: Prisma.IntFilter<"FulfillmentAssignment"> | number
  createdAt?: Prisma.DateTimeFilter<"FulfillmentAssignment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FulfillmentAssignment"> | Date | string
}

export type FulfillmentAssignmentCreateManyOrderInput = {
  id?: string
  assignedToUserId: string
  assignedByUserId: string
  assignedAt?: Date | string
  completedAt?: Date | string | null
  status?: $Enums.FulfillmentAssignmentStatus
  version?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FulfillmentAssignmentUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedToUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null
  status?:
    | Prisma.EnumFulfillmentAssignmentStatusFieldUpdateOperationsInput
    | $Enums.FulfillmentAssignmentStatus
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FulfillmentAssignmentUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedToUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null
  status?:
    | Prisma.EnumFulfillmentAssignmentStatusFieldUpdateOperationsInput
    | $Enums.FulfillmentAssignmentStatus
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FulfillmentAssignmentUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedToUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedByUserId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  completedAt?:
    | Prisma.NullableDateTimeFieldUpdateOperationsInput
    | Date
    | string
    | null
  status?:
    | Prisma.EnumFulfillmentAssignmentStatusFieldUpdateOperationsInput
    | $Enums.FulfillmentAssignmentStatus
  version?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FulfillmentAssignmentSelect<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    orderId?: boolean
    assignedToUserId?: boolean
    assignedByUserId?: boolean
    assignedAt?: boolean
    completedAt?: boolean
    status?: boolean
    version?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["fulfillmentAssignment"]
>

export type FulfillmentAssignmentSelectCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    orderId?: boolean
    assignedToUserId?: boolean
    assignedByUserId?: boolean
    assignedAt?: boolean
    completedAt?: boolean
    status?: boolean
    version?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["fulfillmentAssignment"]
>

export type FulfillmentAssignmentSelectUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    orderId?: boolean
    assignedToUserId?: boolean
    assignedByUserId?: boolean
    assignedAt?: boolean
    completedAt?: boolean
    status?: boolean
    version?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["fulfillmentAssignment"]
>

export type FulfillmentAssignmentSelectScalar = {
  id?: boolean
  orderId?: boolean
  assignedToUserId?: boolean
  assignedByUserId?: boolean
  assignedAt?: boolean
  completedAt?: boolean
  status?: boolean
  version?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FulfillmentAssignmentOmit<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | "id"
  | "orderId"
  | "assignedToUserId"
  | "assignedByUserId"
  | "assignedAt"
  | "completedAt"
  | "status"
  | "version"
  | "createdAt"
  | "updatedAt",
  ExtArgs["result"]["fulfillmentAssignment"]
>
export type FulfillmentAssignmentInclude<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}
export type FulfillmentAssignmentIncludeCreateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}
export type FulfillmentAssignmentIncludeUpdateManyAndReturn<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}

export type $FulfillmentAssignmentPayload<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: "FulfillmentAssignment"
  objects: {
    order: Prisma.$OrderPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      orderId: string
      assignedToUserId: string
      assignedByUserId: string
      assignedAt: Date
      completedAt: Date | null
      status: $Enums.FulfillmentAssignmentStatus
      version: number
      createdAt: Date
      updatedAt: Date
    },
    ExtArgs["result"]["fulfillmentAssignment"]
  >
  composites: {}
}

export type FulfillmentAssignmentGetPayload<
  S extends boolean | null | undefined | FulfillmentAssignmentDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$FulfillmentAssignmentPayload, S>

export type FulfillmentAssignmentCountArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<
  FulfillmentAssignmentFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: FulfillmentAssignmentCountAggregateInputType | true
}

export interface FulfillmentAssignmentDelegate<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["FulfillmentAssignment"]
    meta: { name: "FulfillmentAssignment" }
  }
  /**
   * Find zero or one FulfillmentAssignment that matches the filter.
   * @param {FulfillmentAssignmentFindUniqueArgs} args - Arguments to find a FulfillmentAssignment
   * @example
   * // Get one FulfillmentAssignment
   * const fulfillmentAssignment = await prisma.fulfillmentAssignment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FulfillmentAssignmentFindUniqueArgs>(
    args: Prisma.SelectSubset<T, FulfillmentAssignmentFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__FulfillmentAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one FulfillmentAssignment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FulfillmentAssignmentFindUniqueOrThrowArgs} args - Arguments to find a FulfillmentAssignment
   * @example
   * // Get one FulfillmentAssignment
   * const fulfillmentAssignment = await prisma.fulfillmentAssignment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FulfillmentAssignmentFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<
      T,
      FulfillmentAssignmentFindUniqueOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__FulfillmentAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first FulfillmentAssignment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FulfillmentAssignmentFindFirstArgs} args - Arguments to find a FulfillmentAssignment
   * @example
   * // Get one FulfillmentAssignment
   * const fulfillmentAssignment = await prisma.fulfillmentAssignment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FulfillmentAssignmentFindFirstArgs>(
    args?: Prisma.SelectSubset<T, FulfillmentAssignmentFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__FulfillmentAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first FulfillmentAssignment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FulfillmentAssignmentFindFirstOrThrowArgs} args - Arguments to find a FulfillmentAssignment
   * @example
   * // Get one FulfillmentAssignment
   * const fulfillmentAssignment = await prisma.fulfillmentAssignment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FulfillmentAssignmentFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<
      T,
      FulfillmentAssignmentFindFirstOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__FulfillmentAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more FulfillmentAssignments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FulfillmentAssignmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FulfillmentAssignments
   * const fulfillmentAssignments = await prisma.fulfillmentAssignment.findMany()
   *
   * // Get first 10 FulfillmentAssignments
   * const fulfillmentAssignments = await prisma.fulfillmentAssignment.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const fulfillmentAssignmentWithIdOnly = await prisma.fulfillmentAssignment.findMany({ select: { id: true } })
   *
   */
  findMany<T extends FulfillmentAssignmentFindManyArgs>(
    args?: Prisma.SelectSubset<T, FulfillmentAssignmentFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >

  /**
   * Create a FulfillmentAssignment.
   * @param {FulfillmentAssignmentCreateArgs} args - Arguments to create a FulfillmentAssignment.
   * @example
   * // Create one FulfillmentAssignment
   * const FulfillmentAssignment = await prisma.fulfillmentAssignment.create({
   *   data: {
   *     // ... data to create a FulfillmentAssignment
   *   }
   * })
   *
   */
  create<T extends FulfillmentAssignmentCreateArgs>(
    args: Prisma.SelectSubset<T, FulfillmentAssignmentCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__FulfillmentAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many FulfillmentAssignments.
   * @param {FulfillmentAssignmentCreateManyArgs} args - Arguments to create many FulfillmentAssignments.
   * @example
   * // Create many FulfillmentAssignments
   * const fulfillmentAssignment = await prisma.fulfillmentAssignment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends FulfillmentAssignmentCreateManyArgs>(
    args?: Prisma.SelectSubset<T, FulfillmentAssignmentCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FulfillmentAssignments and returns the data saved in the database.
   * @param {FulfillmentAssignmentCreateManyAndReturnArgs} args - Arguments to create many FulfillmentAssignments.
   * @example
   * // Create many FulfillmentAssignments
   * const fulfillmentAssignment = await prisma.fulfillmentAssignment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many FulfillmentAssignments and only return the `id`
   * const fulfillmentAssignmentWithIdOnly = await prisma.fulfillmentAssignment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends FulfillmentAssignmentCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      FulfillmentAssignmentCreateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Delete a FulfillmentAssignment.
   * @param {FulfillmentAssignmentDeleteArgs} args - Arguments to delete one FulfillmentAssignment.
   * @example
   * // Delete one FulfillmentAssignment
   * const FulfillmentAssignment = await prisma.fulfillmentAssignment.delete({
   *   where: {
   *     // ... filter to delete one FulfillmentAssignment
   *   }
   * })
   *
   */
  delete<T extends FulfillmentAssignmentDeleteArgs>(
    args: Prisma.SelectSubset<T, FulfillmentAssignmentDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__FulfillmentAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one FulfillmentAssignment.
   * @param {FulfillmentAssignmentUpdateArgs} args - Arguments to update one FulfillmentAssignment.
   * @example
   * // Update one FulfillmentAssignment
   * const fulfillmentAssignment = await prisma.fulfillmentAssignment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends FulfillmentAssignmentUpdateArgs>(
    args: Prisma.SelectSubset<T, FulfillmentAssignmentUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__FulfillmentAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more FulfillmentAssignments.
   * @param {FulfillmentAssignmentDeleteManyArgs} args - Arguments to filter FulfillmentAssignments to delete.
   * @example
   * // Delete a few FulfillmentAssignments
   * const { count } = await prisma.fulfillmentAssignment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends FulfillmentAssignmentDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, FulfillmentAssignmentDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FulfillmentAssignments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FulfillmentAssignmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FulfillmentAssignments
   * const fulfillmentAssignment = await prisma.fulfillmentAssignment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends FulfillmentAssignmentUpdateManyArgs>(
    args: Prisma.SelectSubset<T, FulfillmentAssignmentUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FulfillmentAssignments and returns the data updated in the database.
   * @param {FulfillmentAssignmentUpdateManyAndReturnArgs} args - Arguments to update many FulfillmentAssignments.
   * @example
   * // Update many FulfillmentAssignments
   * const fulfillmentAssignment = await prisma.fulfillmentAssignment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more FulfillmentAssignments and only return the `id`
   * const fulfillmentAssignmentWithIdOnly = await prisma.fulfillmentAssignment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends FulfillmentAssignmentUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      FulfillmentAssignmentUpdateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one FulfillmentAssignment.
   * @param {FulfillmentAssignmentUpsertArgs} args - Arguments to update or create a FulfillmentAssignment.
   * @example
   * // Update or create a FulfillmentAssignment
   * const fulfillmentAssignment = await prisma.fulfillmentAssignment.upsert({
   *   create: {
   *     // ... data to create a FulfillmentAssignment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FulfillmentAssignment we want to update
   *   }
   * })
   */
  upsert<T extends FulfillmentAssignmentUpsertArgs>(
    args: Prisma.SelectSubset<T, FulfillmentAssignmentUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__FulfillmentAssignmentClient<
    runtime.Types.Result.GetResult<
      Prisma.$FulfillmentAssignmentPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of FulfillmentAssignments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FulfillmentAssignmentCountArgs} args - Arguments to filter FulfillmentAssignments to count.
   * @example
   * // Count the number of FulfillmentAssignments
   * const count = await prisma.fulfillmentAssignment.count({
   *   where: {
   *     // ... the filter for the FulfillmentAssignments we want to count
   *   }
   * })
   **/
  count<T extends FulfillmentAssignmentCountArgs>(
    args?: Prisma.Subset<T, FulfillmentAssignmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<
            T["select"],
            FulfillmentAssignmentCountAggregateOutputType
          >
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FulfillmentAssignment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FulfillmentAssignmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends FulfillmentAssignmentAggregateArgs>(
    args: Prisma.Subset<T, FulfillmentAssignmentAggregateArgs>,
  ): Prisma.PrismaPromise<GetFulfillmentAssignmentAggregateType<T>>

  /**
   * Group by FulfillmentAssignment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FulfillmentAssignmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends FulfillmentAssignmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FulfillmentAssignmentGroupByArgs["orderBy"] }
      : { orderBy?: FulfillmentAssignmentGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ]
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<
      T,
      FulfillmentAssignmentGroupByArgs,
      OrderByArg
    > &
      InputErrors,
  ): {} extends InputErrors
    ? GetFulfillmentAssignmentGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the FulfillmentAssignment model
   */
  readonly fields: FulfillmentAssignmentFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for FulfillmentAssignment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FulfillmentAssignmentClient<
  T,
  Null = never,
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order<T extends Prisma.OrderDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.OrderDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__OrderClient<
    | runtime.Types.Result.GetResult<
        Prisma.$OrderPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the FulfillmentAssignment model
 */
export interface FulfillmentAssignmentFieldRefs {
  readonly id: Prisma.FieldRef<"FulfillmentAssignment", "String">
  readonly orderId: Prisma.FieldRef<"FulfillmentAssignment", "String">
  readonly assignedToUserId: Prisma.FieldRef<"FulfillmentAssignment", "String">
  readonly assignedByUserId: Prisma.FieldRef<"FulfillmentAssignment", "String">
  readonly assignedAt: Prisma.FieldRef<"FulfillmentAssignment", "DateTime">
  readonly completedAt: Prisma.FieldRef<"FulfillmentAssignment", "DateTime">
  readonly status: Prisma.FieldRef<
    "FulfillmentAssignment",
    "FulfillmentAssignmentStatus"
  >
  readonly version: Prisma.FieldRef<"FulfillmentAssignment", "Int">
  readonly createdAt: Prisma.FieldRef<"FulfillmentAssignment", "DateTime">
  readonly updatedAt: Prisma.FieldRef<"FulfillmentAssignment", "DateTime">
}

// Custom InputTypes
/**
 * FulfillmentAssignment findUnique
 */
export type FulfillmentAssignmentFindUniqueArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which FulfillmentAssignment to fetch.
   */
  where: Prisma.FulfillmentAssignmentWhereUniqueInput
}

/**
 * FulfillmentAssignment findUniqueOrThrow
 */
export type FulfillmentAssignmentFindUniqueOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which FulfillmentAssignment to fetch.
   */
  where: Prisma.FulfillmentAssignmentWhereUniqueInput
}

/**
 * FulfillmentAssignment findFirst
 */
export type FulfillmentAssignmentFindFirstArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which FulfillmentAssignment to fetch.
   */
  where?: Prisma.FulfillmentAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of FulfillmentAssignments to fetch.
   */
  orderBy?:
    | Prisma.FulfillmentAssignmentOrderByWithRelationInput
    | Prisma.FulfillmentAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for FulfillmentAssignments.
   */
  cursor?: Prisma.FulfillmentAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` FulfillmentAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` FulfillmentAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of FulfillmentAssignments.
   */
  distinct?:
    | Prisma.FulfillmentAssignmentScalarFieldEnum
    | Prisma.FulfillmentAssignmentScalarFieldEnum[]
}

/**
 * FulfillmentAssignment findFirstOrThrow
 */
export type FulfillmentAssignmentFindFirstOrThrowArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which FulfillmentAssignment to fetch.
   */
  where?: Prisma.FulfillmentAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of FulfillmentAssignments to fetch.
   */
  orderBy?:
    | Prisma.FulfillmentAssignmentOrderByWithRelationInput
    | Prisma.FulfillmentAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for FulfillmentAssignments.
   */
  cursor?: Prisma.FulfillmentAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` FulfillmentAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` FulfillmentAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of FulfillmentAssignments.
   */
  distinct?:
    | Prisma.FulfillmentAssignmentScalarFieldEnum
    | Prisma.FulfillmentAssignmentScalarFieldEnum[]
}

/**
 * FulfillmentAssignment findMany
 */
export type FulfillmentAssignmentFindManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentInclude<ExtArgs> | null
  /**
   * Filter, which FulfillmentAssignments to fetch.
   */
  where?: Prisma.FulfillmentAssignmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of FulfillmentAssignments to fetch.
   */
  orderBy?:
    | Prisma.FulfillmentAssignmentOrderByWithRelationInput
    | Prisma.FulfillmentAssignmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing FulfillmentAssignments.
   */
  cursor?: Prisma.FulfillmentAssignmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` FulfillmentAssignments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` FulfillmentAssignments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of FulfillmentAssignments.
   */
  distinct?:
    | Prisma.FulfillmentAssignmentScalarFieldEnum
    | Prisma.FulfillmentAssignmentScalarFieldEnum[]
}

/**
 * FulfillmentAssignment create
 */
export type FulfillmentAssignmentCreateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentInclude<ExtArgs> | null
  /**
   * The data needed to create a FulfillmentAssignment.
   */
  data: Prisma.XOR<
    Prisma.FulfillmentAssignmentCreateInput,
    Prisma.FulfillmentAssignmentUncheckedCreateInput
  >
}

/**
 * FulfillmentAssignment createMany
 */
export type FulfillmentAssignmentCreateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many FulfillmentAssignments.
   */
  data:
    | Prisma.FulfillmentAssignmentCreateManyInput
    | Prisma.FulfillmentAssignmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FulfillmentAssignment createManyAndReturn
 */
export type FulfillmentAssignmentCreateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * The data used to create many FulfillmentAssignments.
   */
  data:
    | Prisma.FulfillmentAssignmentCreateManyInput
    | Prisma.FulfillmentAssignmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FulfillmentAssignment update
 */
export type FulfillmentAssignmentUpdateArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentInclude<ExtArgs> | null
  /**
   * The data needed to update a FulfillmentAssignment.
   */
  data: Prisma.XOR<
    Prisma.FulfillmentAssignmentUpdateInput,
    Prisma.FulfillmentAssignmentUncheckedUpdateInput
  >
  /**
   * Choose, which FulfillmentAssignment to update.
   */
  where: Prisma.FulfillmentAssignmentWhereUniqueInput
}

/**
 * FulfillmentAssignment updateMany
 */
export type FulfillmentAssignmentUpdateManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update FulfillmentAssignments.
   */
  data: Prisma.XOR<
    Prisma.FulfillmentAssignmentUpdateManyMutationInput,
    Prisma.FulfillmentAssignmentUncheckedUpdateManyInput
  >
  /**
   * Filter which FulfillmentAssignments to update
   */
  where?: Prisma.FulfillmentAssignmentWhereInput
  /**
   * Limit how many FulfillmentAssignments to update.
   */
  limit?: number
}

/**
 * FulfillmentAssignment updateManyAndReturn
 */
export type FulfillmentAssignmentUpdateManyAndReturnArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * The data used to update FulfillmentAssignments.
   */
  data: Prisma.XOR<
    Prisma.FulfillmentAssignmentUpdateManyMutationInput,
    Prisma.FulfillmentAssignmentUncheckedUpdateManyInput
  >
  /**
   * Filter which FulfillmentAssignments to update
   */
  where?: Prisma.FulfillmentAssignmentWhereInput
  /**
   * Limit how many FulfillmentAssignments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FulfillmentAssignment upsert
 */
export type FulfillmentAssignmentUpsertArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentInclude<ExtArgs> | null
  /**
   * The filter to search for the FulfillmentAssignment to update in case it exists.
   */
  where: Prisma.FulfillmentAssignmentWhereUniqueInput
  /**
   * In case the FulfillmentAssignment found by the `where` argument doesn't exist, create a new FulfillmentAssignment with this data.
   */
  create: Prisma.XOR<
    Prisma.FulfillmentAssignmentCreateInput,
    Prisma.FulfillmentAssignmentUncheckedCreateInput
  >
  /**
   * In case the FulfillmentAssignment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.FulfillmentAssignmentUpdateInput,
    Prisma.FulfillmentAssignmentUncheckedUpdateInput
  >
}

/**
 * FulfillmentAssignment delete
 */
export type FulfillmentAssignmentDeleteArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentInclude<ExtArgs> | null
  /**
   * Filter which FulfillmentAssignment to delete.
   */
  where: Prisma.FulfillmentAssignmentWhereUniqueInput
}

/**
 * FulfillmentAssignment deleteMany
 */
export type FulfillmentAssignmentDeleteManyArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which FulfillmentAssignments to delete
   */
  where?: Prisma.FulfillmentAssignmentWhereInput
  /**
   * Limit how many FulfillmentAssignments to delete.
   */
  limit?: number
}

/**
 * FulfillmentAssignment without action
 */
export type FulfillmentAssignmentDefaultArgs<
  ExtArgs extends
    runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the FulfillmentAssignment
   */
  select?: Prisma.FulfillmentAssignmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FulfillmentAssignment
   */
  omit?: Prisma.FulfillmentAssignmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FulfillmentAssignmentInclude<ExtArgs> | null
}
