
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ListingFulfillmentRule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ListingFulfillmentRule
 * 
 */
export type ListingFulfillmentRuleModel = runtime.Types.Result.DefaultSelection<Prisma.$ListingFulfillmentRulePayload>

export type AggregateListingFulfillmentRule = {
  _count: ListingFulfillmentRuleCountAggregateOutputType | null
  _min: ListingFulfillmentRuleMinAggregateOutputType | null
  _max: ListingFulfillmentRuleMaxAggregateOutputType | null
}

export type ListingFulfillmentRuleMinAggregateOutputType = {
  id: string | null
  listingId: string | null
  type: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ListingFulfillmentRuleMaxAggregateOutputType = {
  id: string | null
  listingId: string | null
  type: string | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ListingFulfillmentRuleCountAggregateOutputType = {
  id: number
  listingId: number
  type: number
  config: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ListingFulfillmentRuleMinAggregateInputType = {
  id?: true
  listingId?: true
  type?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type ListingFulfillmentRuleMaxAggregateInputType = {
  id?: true
  listingId?: true
  type?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type ListingFulfillmentRuleCountAggregateInputType = {
  id?: true
  listingId?: true
  type?: true
  config?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ListingFulfillmentRuleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingFulfillmentRule to aggregate.
   */
  where?: Prisma.ListingFulfillmentRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingFulfillmentRules to fetch.
   */
  orderBy?: Prisma.ListingFulfillmentRuleOrderByWithRelationInput | Prisma.ListingFulfillmentRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ListingFulfillmentRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingFulfillmentRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingFulfillmentRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ListingFulfillmentRules
  **/
  _count?: true | ListingFulfillmentRuleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ListingFulfillmentRuleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ListingFulfillmentRuleMaxAggregateInputType
}

export type GetListingFulfillmentRuleAggregateType<T extends ListingFulfillmentRuleAggregateArgs> = {
      [P in keyof T & keyof AggregateListingFulfillmentRule]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateListingFulfillmentRule[P]>
    : Prisma.GetScalarType<T[P], AggregateListingFulfillmentRule[P]>
}




export type ListingFulfillmentRuleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ListingFulfillmentRuleWhereInput
  orderBy?: Prisma.ListingFulfillmentRuleOrderByWithAggregationInput | Prisma.ListingFulfillmentRuleOrderByWithAggregationInput[]
  by: Prisma.ListingFulfillmentRuleScalarFieldEnum[] | Prisma.ListingFulfillmentRuleScalarFieldEnum
  having?: Prisma.ListingFulfillmentRuleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ListingFulfillmentRuleCountAggregateInputType | true
  _min?: ListingFulfillmentRuleMinAggregateInputType
  _max?: ListingFulfillmentRuleMaxAggregateInputType
}

export type ListingFulfillmentRuleGroupByOutputType = {
  id: string
  listingId: string
  type: string
  config: runtime.JsonValue
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: ListingFulfillmentRuleCountAggregateOutputType | null
  _min: ListingFulfillmentRuleMinAggregateOutputType | null
  _max: ListingFulfillmentRuleMaxAggregateOutputType | null
}

export type GetListingFulfillmentRuleGroupByPayload<T extends ListingFulfillmentRuleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ListingFulfillmentRuleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ListingFulfillmentRuleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ListingFulfillmentRuleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ListingFulfillmentRuleGroupByOutputType[P]>
      }
    >
  >



export type ListingFulfillmentRuleWhereInput = {
  AND?: Prisma.ListingFulfillmentRuleWhereInput | Prisma.ListingFulfillmentRuleWhereInput[]
  OR?: Prisma.ListingFulfillmentRuleWhereInput[]
  NOT?: Prisma.ListingFulfillmentRuleWhereInput | Prisma.ListingFulfillmentRuleWhereInput[]
  id?: Prisma.StringFilter<"ListingFulfillmentRule"> | string
  listingId?: Prisma.StringFilter<"ListingFulfillmentRule"> | string
  type?: Prisma.StringFilter<"ListingFulfillmentRule"> | string
  config?: Prisma.JsonFilter<"ListingFulfillmentRule">
  isActive?: Prisma.BoolFilter<"ListingFulfillmentRule"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ListingFulfillmentRule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ListingFulfillmentRule"> | Date | string
}

export type ListingFulfillmentRuleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ListingFulfillmentRuleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ListingFulfillmentRuleWhereInput | Prisma.ListingFulfillmentRuleWhereInput[]
  OR?: Prisma.ListingFulfillmentRuleWhereInput[]
  NOT?: Prisma.ListingFulfillmentRuleWhereInput | Prisma.ListingFulfillmentRuleWhereInput[]
  listingId?: Prisma.StringFilter<"ListingFulfillmentRule"> | string
  type?: Prisma.StringFilter<"ListingFulfillmentRule"> | string
  config?: Prisma.JsonFilter<"ListingFulfillmentRule">
  isActive?: Prisma.BoolFilter<"ListingFulfillmentRule"> | boolean
  createdAt?: Prisma.DateTimeFilter<"ListingFulfillmentRule"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ListingFulfillmentRule"> | Date | string
}, "id">

export type ListingFulfillmentRuleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ListingFulfillmentRuleCountOrderByAggregateInput
  _max?: Prisma.ListingFulfillmentRuleMaxOrderByAggregateInput
  _min?: Prisma.ListingFulfillmentRuleMinOrderByAggregateInput
}

export type ListingFulfillmentRuleScalarWhereWithAggregatesInput = {
  AND?: Prisma.ListingFulfillmentRuleScalarWhereWithAggregatesInput | Prisma.ListingFulfillmentRuleScalarWhereWithAggregatesInput[]
  OR?: Prisma.ListingFulfillmentRuleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ListingFulfillmentRuleScalarWhereWithAggregatesInput | Prisma.ListingFulfillmentRuleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ListingFulfillmentRule"> | string
  listingId?: Prisma.StringWithAggregatesFilter<"ListingFulfillmentRule"> | string
  type?: Prisma.StringWithAggregatesFilter<"ListingFulfillmentRule"> | string
  config?: Prisma.JsonWithAggregatesFilter<"ListingFulfillmentRule">
  isActive?: Prisma.BoolWithAggregatesFilter<"ListingFulfillmentRule"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ListingFulfillmentRule"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ListingFulfillmentRule"> | Date | string
}

export type ListingFulfillmentRuleCreateInput = {
  id?: string
  listingId: string
  type: string
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ListingFulfillmentRuleUncheckedCreateInput = {
  id?: string
  listingId: string
  type: string
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ListingFulfillmentRuleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ListingFulfillmentRuleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ListingFulfillmentRuleCreateManyInput = {
  id?: string
  listingId: string
  type: string
  config: Prisma.JsonNullValueInput | runtime.InputJsonValue
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ListingFulfillmentRuleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ListingFulfillmentRuleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ListingFulfillmentRuleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  config?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ListingFulfillmentRuleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ListingFulfillmentRuleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type ListingFulfillmentRuleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  listingId?: boolean
  type?: boolean
  config?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["listingFulfillmentRule"]>

export type ListingFulfillmentRuleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  listingId?: boolean
  type?: boolean
  config?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["listingFulfillmentRule"]>

export type ListingFulfillmentRuleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  listingId?: boolean
  type?: boolean
  config?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["listingFulfillmentRule"]>

export type ListingFulfillmentRuleSelectScalar = {
  id?: boolean
  listingId?: boolean
  type?: boolean
  config?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ListingFulfillmentRuleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "listingId" | "type" | "config" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["listingFulfillmentRule"]>

export type $ListingFulfillmentRulePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ListingFulfillmentRule"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    listingId: string
    type: string
    config: runtime.JsonValue
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["listingFulfillmentRule"]>
  composites: {}
}

export type ListingFulfillmentRuleGetPayload<S extends boolean | null | undefined | ListingFulfillmentRuleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload, S>

export type ListingFulfillmentRuleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ListingFulfillmentRuleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ListingFulfillmentRuleCountAggregateInputType | true
  }

export interface ListingFulfillmentRuleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ListingFulfillmentRule'], meta: { name: 'ListingFulfillmentRule' } }
  /**
   * Find zero or one ListingFulfillmentRule that matches the filter.
   * @param {ListingFulfillmentRuleFindUniqueArgs} args - Arguments to find a ListingFulfillmentRule
   * @example
   * // Get one ListingFulfillmentRule
   * const listingFulfillmentRule = await prisma.listingFulfillmentRule.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ListingFulfillmentRuleFindUniqueArgs>(args: Prisma.SelectSubset<T, ListingFulfillmentRuleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ListingFulfillmentRuleClient<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ListingFulfillmentRule that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ListingFulfillmentRuleFindUniqueOrThrowArgs} args - Arguments to find a ListingFulfillmentRule
   * @example
   * // Get one ListingFulfillmentRule
   * const listingFulfillmentRule = await prisma.listingFulfillmentRule.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ListingFulfillmentRuleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ListingFulfillmentRuleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingFulfillmentRuleClient<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingFulfillmentRule that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingFulfillmentRuleFindFirstArgs} args - Arguments to find a ListingFulfillmentRule
   * @example
   * // Get one ListingFulfillmentRule
   * const listingFulfillmentRule = await prisma.listingFulfillmentRule.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ListingFulfillmentRuleFindFirstArgs>(args?: Prisma.SelectSubset<T, ListingFulfillmentRuleFindFirstArgs<ExtArgs>>): Prisma.Prisma__ListingFulfillmentRuleClient<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ListingFulfillmentRule that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingFulfillmentRuleFindFirstOrThrowArgs} args - Arguments to find a ListingFulfillmentRule
   * @example
   * // Get one ListingFulfillmentRule
   * const listingFulfillmentRule = await prisma.listingFulfillmentRule.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ListingFulfillmentRuleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ListingFulfillmentRuleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ListingFulfillmentRuleClient<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ListingFulfillmentRules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingFulfillmentRuleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ListingFulfillmentRules
   * const listingFulfillmentRules = await prisma.listingFulfillmentRule.findMany()
   * 
   * // Get first 10 ListingFulfillmentRules
   * const listingFulfillmentRules = await prisma.listingFulfillmentRule.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const listingFulfillmentRuleWithIdOnly = await prisma.listingFulfillmentRule.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ListingFulfillmentRuleFindManyArgs>(args?: Prisma.SelectSubset<T, ListingFulfillmentRuleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ListingFulfillmentRule.
   * @param {ListingFulfillmentRuleCreateArgs} args - Arguments to create a ListingFulfillmentRule.
   * @example
   * // Create one ListingFulfillmentRule
   * const ListingFulfillmentRule = await prisma.listingFulfillmentRule.create({
   *   data: {
   *     // ... data to create a ListingFulfillmentRule
   *   }
   * })
   * 
   */
  create<T extends ListingFulfillmentRuleCreateArgs>(args: Prisma.SelectSubset<T, ListingFulfillmentRuleCreateArgs<ExtArgs>>): Prisma.Prisma__ListingFulfillmentRuleClient<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ListingFulfillmentRules.
   * @param {ListingFulfillmentRuleCreateManyArgs} args - Arguments to create many ListingFulfillmentRules.
   * @example
   * // Create many ListingFulfillmentRules
   * const listingFulfillmentRule = await prisma.listingFulfillmentRule.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ListingFulfillmentRuleCreateManyArgs>(args?: Prisma.SelectSubset<T, ListingFulfillmentRuleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ListingFulfillmentRules and returns the data saved in the database.
   * @param {ListingFulfillmentRuleCreateManyAndReturnArgs} args - Arguments to create many ListingFulfillmentRules.
   * @example
   * // Create many ListingFulfillmentRules
   * const listingFulfillmentRule = await prisma.listingFulfillmentRule.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ListingFulfillmentRules and only return the `id`
   * const listingFulfillmentRuleWithIdOnly = await prisma.listingFulfillmentRule.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ListingFulfillmentRuleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ListingFulfillmentRuleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ListingFulfillmentRule.
   * @param {ListingFulfillmentRuleDeleteArgs} args - Arguments to delete one ListingFulfillmentRule.
   * @example
   * // Delete one ListingFulfillmentRule
   * const ListingFulfillmentRule = await prisma.listingFulfillmentRule.delete({
   *   where: {
   *     // ... filter to delete one ListingFulfillmentRule
   *   }
   * })
   * 
   */
  delete<T extends ListingFulfillmentRuleDeleteArgs>(args: Prisma.SelectSubset<T, ListingFulfillmentRuleDeleteArgs<ExtArgs>>): Prisma.Prisma__ListingFulfillmentRuleClient<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ListingFulfillmentRule.
   * @param {ListingFulfillmentRuleUpdateArgs} args - Arguments to update one ListingFulfillmentRule.
   * @example
   * // Update one ListingFulfillmentRule
   * const listingFulfillmentRule = await prisma.listingFulfillmentRule.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ListingFulfillmentRuleUpdateArgs>(args: Prisma.SelectSubset<T, ListingFulfillmentRuleUpdateArgs<ExtArgs>>): Prisma.Prisma__ListingFulfillmentRuleClient<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ListingFulfillmentRules.
   * @param {ListingFulfillmentRuleDeleteManyArgs} args - Arguments to filter ListingFulfillmentRules to delete.
   * @example
   * // Delete a few ListingFulfillmentRules
   * const { count } = await prisma.listingFulfillmentRule.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ListingFulfillmentRuleDeleteManyArgs>(args?: Prisma.SelectSubset<T, ListingFulfillmentRuleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingFulfillmentRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingFulfillmentRuleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ListingFulfillmentRules
   * const listingFulfillmentRule = await prisma.listingFulfillmentRule.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ListingFulfillmentRuleUpdateManyArgs>(args: Prisma.SelectSubset<T, ListingFulfillmentRuleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ListingFulfillmentRules and returns the data updated in the database.
   * @param {ListingFulfillmentRuleUpdateManyAndReturnArgs} args - Arguments to update many ListingFulfillmentRules.
   * @example
   * // Update many ListingFulfillmentRules
   * const listingFulfillmentRule = await prisma.listingFulfillmentRule.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ListingFulfillmentRules and only return the `id`
   * const listingFulfillmentRuleWithIdOnly = await prisma.listingFulfillmentRule.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ListingFulfillmentRuleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ListingFulfillmentRuleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ListingFulfillmentRule.
   * @param {ListingFulfillmentRuleUpsertArgs} args - Arguments to update or create a ListingFulfillmentRule.
   * @example
   * // Update or create a ListingFulfillmentRule
   * const listingFulfillmentRule = await prisma.listingFulfillmentRule.upsert({
   *   create: {
   *     // ... data to create a ListingFulfillmentRule
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ListingFulfillmentRule we want to update
   *   }
   * })
   */
  upsert<T extends ListingFulfillmentRuleUpsertArgs>(args: Prisma.SelectSubset<T, ListingFulfillmentRuleUpsertArgs<ExtArgs>>): Prisma.Prisma__ListingFulfillmentRuleClient<runtime.Types.Result.GetResult<Prisma.$ListingFulfillmentRulePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ListingFulfillmentRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingFulfillmentRuleCountArgs} args - Arguments to filter ListingFulfillmentRules to count.
   * @example
   * // Count the number of ListingFulfillmentRules
   * const count = await prisma.listingFulfillmentRule.count({
   *   where: {
   *     // ... the filter for the ListingFulfillmentRules we want to count
   *   }
   * })
  **/
  count<T extends ListingFulfillmentRuleCountArgs>(
    args?: Prisma.Subset<T, ListingFulfillmentRuleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ListingFulfillmentRuleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ListingFulfillmentRule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingFulfillmentRuleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ListingFulfillmentRuleAggregateArgs>(args: Prisma.Subset<T, ListingFulfillmentRuleAggregateArgs>): Prisma.PrismaPromise<GetListingFulfillmentRuleAggregateType<T>>

  /**
   * Group by ListingFulfillmentRule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ListingFulfillmentRuleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ListingFulfillmentRuleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ListingFulfillmentRuleGroupByArgs['orderBy'] }
      : { orderBy?: ListingFulfillmentRuleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ListingFulfillmentRuleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetListingFulfillmentRuleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ListingFulfillmentRule model
 */
readonly fields: ListingFulfillmentRuleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ListingFulfillmentRule.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ListingFulfillmentRuleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ListingFulfillmentRule model
 */
export interface ListingFulfillmentRuleFieldRefs {
  readonly id: Prisma.FieldRef<"ListingFulfillmentRule", 'String'>
  readonly listingId: Prisma.FieldRef<"ListingFulfillmentRule", 'String'>
  readonly type: Prisma.FieldRef<"ListingFulfillmentRule", 'String'>
  readonly config: Prisma.FieldRef<"ListingFulfillmentRule", 'Json'>
  readonly isActive: Prisma.FieldRef<"ListingFulfillmentRule", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"ListingFulfillmentRule", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ListingFulfillmentRule", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ListingFulfillmentRule findUnique
 */
export type ListingFulfillmentRuleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * Filter, which ListingFulfillmentRule to fetch.
   */
  where: Prisma.ListingFulfillmentRuleWhereUniqueInput
}

/**
 * ListingFulfillmentRule findUniqueOrThrow
 */
export type ListingFulfillmentRuleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * Filter, which ListingFulfillmentRule to fetch.
   */
  where: Prisma.ListingFulfillmentRuleWhereUniqueInput
}

/**
 * ListingFulfillmentRule findFirst
 */
export type ListingFulfillmentRuleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * Filter, which ListingFulfillmentRule to fetch.
   */
  where?: Prisma.ListingFulfillmentRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingFulfillmentRules to fetch.
   */
  orderBy?: Prisma.ListingFulfillmentRuleOrderByWithRelationInput | Prisma.ListingFulfillmentRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingFulfillmentRules.
   */
  cursor?: Prisma.ListingFulfillmentRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingFulfillmentRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingFulfillmentRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingFulfillmentRules.
   */
  distinct?: Prisma.ListingFulfillmentRuleScalarFieldEnum | Prisma.ListingFulfillmentRuleScalarFieldEnum[]
}

/**
 * ListingFulfillmentRule findFirstOrThrow
 */
export type ListingFulfillmentRuleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * Filter, which ListingFulfillmentRule to fetch.
   */
  where?: Prisma.ListingFulfillmentRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingFulfillmentRules to fetch.
   */
  orderBy?: Prisma.ListingFulfillmentRuleOrderByWithRelationInput | Prisma.ListingFulfillmentRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ListingFulfillmentRules.
   */
  cursor?: Prisma.ListingFulfillmentRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingFulfillmentRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingFulfillmentRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingFulfillmentRules.
   */
  distinct?: Prisma.ListingFulfillmentRuleScalarFieldEnum | Prisma.ListingFulfillmentRuleScalarFieldEnum[]
}

/**
 * ListingFulfillmentRule findMany
 */
export type ListingFulfillmentRuleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * Filter, which ListingFulfillmentRules to fetch.
   */
  where?: Prisma.ListingFulfillmentRuleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ListingFulfillmentRules to fetch.
   */
  orderBy?: Prisma.ListingFulfillmentRuleOrderByWithRelationInput | Prisma.ListingFulfillmentRuleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ListingFulfillmentRules.
   */
  cursor?: Prisma.ListingFulfillmentRuleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ListingFulfillmentRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ListingFulfillmentRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ListingFulfillmentRules.
   */
  distinct?: Prisma.ListingFulfillmentRuleScalarFieldEnum | Prisma.ListingFulfillmentRuleScalarFieldEnum[]
}

/**
 * ListingFulfillmentRule create
 */
export type ListingFulfillmentRuleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * The data needed to create a ListingFulfillmentRule.
   */
  data: Prisma.XOR<Prisma.ListingFulfillmentRuleCreateInput, Prisma.ListingFulfillmentRuleUncheckedCreateInput>
}

/**
 * ListingFulfillmentRule createMany
 */
export type ListingFulfillmentRuleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ListingFulfillmentRules.
   */
  data: Prisma.ListingFulfillmentRuleCreateManyInput | Prisma.ListingFulfillmentRuleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ListingFulfillmentRule createManyAndReturn
 */
export type ListingFulfillmentRuleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * The data used to create many ListingFulfillmentRules.
   */
  data: Prisma.ListingFulfillmentRuleCreateManyInput | Prisma.ListingFulfillmentRuleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ListingFulfillmentRule update
 */
export type ListingFulfillmentRuleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * The data needed to update a ListingFulfillmentRule.
   */
  data: Prisma.XOR<Prisma.ListingFulfillmentRuleUpdateInput, Prisma.ListingFulfillmentRuleUncheckedUpdateInput>
  /**
   * Choose, which ListingFulfillmentRule to update.
   */
  where: Prisma.ListingFulfillmentRuleWhereUniqueInput
}

/**
 * ListingFulfillmentRule updateMany
 */
export type ListingFulfillmentRuleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ListingFulfillmentRules.
   */
  data: Prisma.XOR<Prisma.ListingFulfillmentRuleUpdateManyMutationInput, Prisma.ListingFulfillmentRuleUncheckedUpdateManyInput>
  /**
   * Filter which ListingFulfillmentRules to update
   */
  where?: Prisma.ListingFulfillmentRuleWhereInput
  /**
   * Limit how many ListingFulfillmentRules to update.
   */
  limit?: number
}

/**
 * ListingFulfillmentRule updateManyAndReturn
 */
export type ListingFulfillmentRuleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * The data used to update ListingFulfillmentRules.
   */
  data: Prisma.XOR<Prisma.ListingFulfillmentRuleUpdateManyMutationInput, Prisma.ListingFulfillmentRuleUncheckedUpdateManyInput>
  /**
   * Filter which ListingFulfillmentRules to update
   */
  where?: Prisma.ListingFulfillmentRuleWhereInput
  /**
   * Limit how many ListingFulfillmentRules to update.
   */
  limit?: number
}

/**
 * ListingFulfillmentRule upsert
 */
export type ListingFulfillmentRuleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * The filter to search for the ListingFulfillmentRule to update in case it exists.
   */
  where: Prisma.ListingFulfillmentRuleWhereUniqueInput
  /**
   * In case the ListingFulfillmentRule found by the `where` argument doesn't exist, create a new ListingFulfillmentRule with this data.
   */
  create: Prisma.XOR<Prisma.ListingFulfillmentRuleCreateInput, Prisma.ListingFulfillmentRuleUncheckedCreateInput>
  /**
   * In case the ListingFulfillmentRule was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ListingFulfillmentRuleUpdateInput, Prisma.ListingFulfillmentRuleUncheckedUpdateInput>
}

/**
 * ListingFulfillmentRule delete
 */
export type ListingFulfillmentRuleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
  /**
   * Filter which ListingFulfillmentRule to delete.
   */
  where: Prisma.ListingFulfillmentRuleWhereUniqueInput
}

/**
 * ListingFulfillmentRule deleteMany
 */
export type ListingFulfillmentRuleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ListingFulfillmentRules to delete
   */
  where?: Prisma.ListingFulfillmentRuleWhereInput
  /**
   * Limit how many ListingFulfillmentRules to delete.
   */
  limit?: number
}

/**
 * ListingFulfillmentRule without action
 */
export type ListingFulfillmentRuleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ListingFulfillmentRule
   */
  select?: Prisma.ListingFulfillmentRuleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ListingFulfillmentRule
   */
  omit?: Prisma.ListingFulfillmentRuleOmit<ExtArgs> | null
}
