
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MarketplaceRecommendation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MarketplaceRecommendation
 * 
 */
export type MarketplaceRecommendationModel = runtime.Types.Result.DefaultSelection<Prisma.$MarketplaceRecommendationPayload>

export type AggregateMarketplaceRecommendation = {
  _count: MarketplaceRecommendationCountAggregateOutputType | null
  _avg: MarketplaceRecommendationAvgAggregateOutputType | null
  _sum: MarketplaceRecommendationSumAggregateOutputType | null
  _min: MarketplaceRecommendationMinAggregateOutputType | null
  _max: MarketplaceRecommendationMaxAggregateOutputType | null
}

export type MarketplaceRecommendationAvgAggregateOutputType = {
  score: number | null
}

export type MarketplaceRecommendationSumAggregateOutputType = {
  score: number | null
}

export type MarketplaceRecommendationMinAggregateOutputType = {
  id: string | null
  userId: string | null
  listingId: string | null
  type: string | null
  score: number | null
  reason: string | null
  createdAt: Date | null
}

export type MarketplaceRecommendationMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  listingId: string | null
  type: string | null
  score: number | null
  reason: string | null
  createdAt: Date | null
}

export type MarketplaceRecommendationCountAggregateOutputType = {
  id: number
  userId: number
  listingId: number
  type: number
  score: number
  reason: number
  metadata: number
  createdAt: number
  _all: number
}


export type MarketplaceRecommendationAvgAggregateInputType = {
  score?: true
}

export type MarketplaceRecommendationSumAggregateInputType = {
  score?: true
}

export type MarketplaceRecommendationMinAggregateInputType = {
  id?: true
  userId?: true
  listingId?: true
  type?: true
  score?: true
  reason?: true
  createdAt?: true
}

export type MarketplaceRecommendationMaxAggregateInputType = {
  id?: true
  userId?: true
  listingId?: true
  type?: true
  score?: true
  reason?: true
  createdAt?: true
}

export type MarketplaceRecommendationCountAggregateInputType = {
  id?: true
  userId?: true
  listingId?: true
  type?: true
  score?: true
  reason?: true
  metadata?: true
  createdAt?: true
  _all?: true
}

export type MarketplaceRecommendationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarketplaceRecommendation to aggregate.
   */
  where?: Prisma.MarketplaceRecommendationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketplaceRecommendations to fetch.
   */
  orderBy?: Prisma.MarketplaceRecommendationOrderByWithRelationInput | Prisma.MarketplaceRecommendationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MarketplaceRecommendationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketplaceRecommendations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketplaceRecommendations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MarketplaceRecommendations
  **/
  _count?: true | MarketplaceRecommendationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MarketplaceRecommendationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MarketplaceRecommendationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MarketplaceRecommendationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MarketplaceRecommendationMaxAggregateInputType
}

export type GetMarketplaceRecommendationAggregateType<T extends MarketplaceRecommendationAggregateArgs> = {
      [P in keyof T & keyof AggregateMarketplaceRecommendation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMarketplaceRecommendation[P]>
    : Prisma.GetScalarType<T[P], AggregateMarketplaceRecommendation[P]>
}




export type MarketplaceRecommendationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MarketplaceRecommendationWhereInput
  orderBy?: Prisma.MarketplaceRecommendationOrderByWithAggregationInput | Prisma.MarketplaceRecommendationOrderByWithAggregationInput[]
  by: Prisma.MarketplaceRecommendationScalarFieldEnum[] | Prisma.MarketplaceRecommendationScalarFieldEnum
  having?: Prisma.MarketplaceRecommendationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MarketplaceRecommendationCountAggregateInputType | true
  _avg?: MarketplaceRecommendationAvgAggregateInputType
  _sum?: MarketplaceRecommendationSumAggregateInputType
  _min?: MarketplaceRecommendationMinAggregateInputType
  _max?: MarketplaceRecommendationMaxAggregateInputType
}

export type MarketplaceRecommendationGroupByOutputType = {
  id: string
  userId: string
  listingId: string
  type: string
  score: number
  reason: string | null
  metadata: runtime.JsonValue | null
  createdAt: Date
  _count: MarketplaceRecommendationCountAggregateOutputType | null
  _avg: MarketplaceRecommendationAvgAggregateOutputType | null
  _sum: MarketplaceRecommendationSumAggregateOutputType | null
  _min: MarketplaceRecommendationMinAggregateOutputType | null
  _max: MarketplaceRecommendationMaxAggregateOutputType | null
}

type GetMarketplaceRecommendationGroupByPayload<T extends MarketplaceRecommendationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MarketplaceRecommendationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MarketplaceRecommendationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MarketplaceRecommendationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MarketplaceRecommendationGroupByOutputType[P]>
      }
    >
  >



export type MarketplaceRecommendationWhereInput = {
  AND?: Prisma.MarketplaceRecommendationWhereInput | Prisma.MarketplaceRecommendationWhereInput[]
  OR?: Prisma.MarketplaceRecommendationWhereInput[]
  NOT?: Prisma.MarketplaceRecommendationWhereInput | Prisma.MarketplaceRecommendationWhereInput[]
  id?: Prisma.StringFilter<"MarketplaceRecommendation"> | string
  userId?: Prisma.StringFilter<"MarketplaceRecommendation"> | string
  listingId?: Prisma.StringFilter<"MarketplaceRecommendation"> | string
  type?: Prisma.StringFilter<"MarketplaceRecommendation"> | string
  score?: Prisma.FloatFilter<"MarketplaceRecommendation"> | number
  reason?: Prisma.StringNullableFilter<"MarketplaceRecommendation"> | string | null
  metadata?: Prisma.JsonNullableFilter<"MarketplaceRecommendation">
  createdAt?: Prisma.DateTimeFilter<"MarketplaceRecommendation"> | Date | string
}

export type MarketplaceRecommendationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  score?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MarketplaceRecommendationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MarketplaceRecommendationWhereInput | Prisma.MarketplaceRecommendationWhereInput[]
  OR?: Prisma.MarketplaceRecommendationWhereInput[]
  NOT?: Prisma.MarketplaceRecommendationWhereInput | Prisma.MarketplaceRecommendationWhereInput[]
  userId?: Prisma.StringFilter<"MarketplaceRecommendation"> | string
  listingId?: Prisma.StringFilter<"MarketplaceRecommendation"> | string
  type?: Prisma.StringFilter<"MarketplaceRecommendation"> | string
  score?: Prisma.FloatFilter<"MarketplaceRecommendation"> | number
  reason?: Prisma.StringNullableFilter<"MarketplaceRecommendation"> | string | null
  metadata?: Prisma.JsonNullableFilter<"MarketplaceRecommendation">
  createdAt?: Prisma.DateTimeFilter<"MarketplaceRecommendation"> | Date | string
}, "id">

export type MarketplaceRecommendationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  score?: Prisma.SortOrder
  reason?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MarketplaceRecommendationCountOrderByAggregateInput
  _avg?: Prisma.MarketplaceRecommendationAvgOrderByAggregateInput
  _max?: Prisma.MarketplaceRecommendationMaxOrderByAggregateInput
  _min?: Prisma.MarketplaceRecommendationMinOrderByAggregateInput
  _sum?: Prisma.MarketplaceRecommendationSumOrderByAggregateInput
}

export type MarketplaceRecommendationScalarWhereWithAggregatesInput = {
  AND?: Prisma.MarketplaceRecommendationScalarWhereWithAggregatesInput | Prisma.MarketplaceRecommendationScalarWhereWithAggregatesInput[]
  OR?: Prisma.MarketplaceRecommendationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MarketplaceRecommendationScalarWhereWithAggregatesInput | Prisma.MarketplaceRecommendationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MarketplaceRecommendation"> | string
  userId?: Prisma.StringWithAggregatesFilter<"MarketplaceRecommendation"> | string
  listingId?: Prisma.StringWithAggregatesFilter<"MarketplaceRecommendation"> | string
  type?: Prisma.StringWithAggregatesFilter<"MarketplaceRecommendation"> | string
  score?: Prisma.FloatWithAggregatesFilter<"MarketplaceRecommendation"> | number
  reason?: Prisma.StringNullableWithAggregatesFilter<"MarketplaceRecommendation"> | string | null
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"MarketplaceRecommendation">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MarketplaceRecommendation"> | Date | string
}

export type MarketplaceRecommendationCreateInput = {
  id?: string
  userId: string
  listingId: string
  type: string
  score: number
  reason?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type MarketplaceRecommendationUncheckedCreateInput = {
  id?: string
  userId: string
  listingId: string
  type: string
  score: number
  reason?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type MarketplaceRecommendationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketplaceRecommendationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketplaceRecommendationCreateManyInput = {
  id?: string
  userId: string
  listingId: string
  type: string
  score: number
  reason?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
}

export type MarketplaceRecommendationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketplaceRecommendationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.FloatFieldUpdateOperationsInput | number
  reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketplaceRecommendationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  score?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MarketplaceRecommendationAvgOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type MarketplaceRecommendationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  score?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MarketplaceRecommendationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  score?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MarketplaceRecommendationSumOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type MarketplaceRecommendationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  listingId?: boolean
  type?: boolean
  score?: boolean
  reason?: boolean
  metadata?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["marketplaceRecommendation"]>

export type MarketplaceRecommendationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  listingId?: boolean
  type?: boolean
  score?: boolean
  reason?: boolean
  metadata?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["marketplaceRecommendation"]>

export type MarketplaceRecommendationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  listingId?: boolean
  type?: boolean
  score?: boolean
  reason?: boolean
  metadata?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["marketplaceRecommendation"]>

export type MarketplaceRecommendationSelectScalar = {
  id?: boolean
  userId?: boolean
  listingId?: boolean
  type?: boolean
  score?: boolean
  reason?: boolean
  metadata?: boolean
  createdAt?: boolean
}

export type MarketplaceRecommendationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "listingId" | "type" | "score" | "reason" | "metadata" | "createdAt", ExtArgs["result"]["marketplaceRecommendation"]>

export type $MarketplaceRecommendationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MarketplaceRecommendation"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    listingId: string
    type: string
    score: number
    reason: string | null
    metadata: runtime.JsonValue | null
    createdAt: Date
  }, ExtArgs["result"]["marketplaceRecommendation"]>
  composites: {}
}

export type MarketplaceRecommendationGetPayload<S extends boolean | null | undefined | MarketplaceRecommendationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload, S>

export type MarketplaceRecommendationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MarketplaceRecommendationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MarketplaceRecommendationCountAggregateInputType | true
  }

export interface MarketplaceRecommendationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MarketplaceRecommendation'], meta: { name: 'MarketplaceRecommendation' } }
  /**
   * Find zero or one MarketplaceRecommendation that matches the filter.
   * @param {MarketplaceRecommendationFindUniqueArgs} args - Arguments to find a MarketplaceRecommendation
   * @example
   * // Get one MarketplaceRecommendation
   * const marketplaceRecommendation = await prisma.marketplaceRecommendation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MarketplaceRecommendationFindUniqueArgs>(args: Prisma.SelectSubset<T, MarketplaceRecommendationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MarketplaceRecommendationClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MarketplaceRecommendation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MarketplaceRecommendationFindUniqueOrThrowArgs} args - Arguments to find a MarketplaceRecommendation
   * @example
   * // Get one MarketplaceRecommendation
   * const marketplaceRecommendation = await prisma.marketplaceRecommendation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MarketplaceRecommendationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MarketplaceRecommendationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarketplaceRecommendationClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarketplaceRecommendation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceRecommendationFindFirstArgs} args - Arguments to find a MarketplaceRecommendation
   * @example
   * // Get one MarketplaceRecommendation
   * const marketplaceRecommendation = await prisma.marketplaceRecommendation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MarketplaceRecommendationFindFirstArgs>(args?: Prisma.SelectSubset<T, MarketplaceRecommendationFindFirstArgs<ExtArgs>>): Prisma.Prisma__MarketplaceRecommendationClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarketplaceRecommendation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceRecommendationFindFirstOrThrowArgs} args - Arguments to find a MarketplaceRecommendation
   * @example
   * // Get one MarketplaceRecommendation
   * const marketplaceRecommendation = await prisma.marketplaceRecommendation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MarketplaceRecommendationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MarketplaceRecommendationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarketplaceRecommendationClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MarketplaceRecommendations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceRecommendationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MarketplaceRecommendations
   * const marketplaceRecommendations = await prisma.marketplaceRecommendation.findMany()
   * 
   * // Get first 10 MarketplaceRecommendations
   * const marketplaceRecommendations = await prisma.marketplaceRecommendation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const marketplaceRecommendationWithIdOnly = await prisma.marketplaceRecommendation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MarketplaceRecommendationFindManyArgs>(args?: Prisma.SelectSubset<T, MarketplaceRecommendationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MarketplaceRecommendation.
   * @param {MarketplaceRecommendationCreateArgs} args - Arguments to create a MarketplaceRecommendation.
   * @example
   * // Create one MarketplaceRecommendation
   * const MarketplaceRecommendation = await prisma.marketplaceRecommendation.create({
   *   data: {
   *     // ... data to create a MarketplaceRecommendation
   *   }
   * })
   * 
   */
  create<T extends MarketplaceRecommendationCreateArgs>(args: Prisma.SelectSubset<T, MarketplaceRecommendationCreateArgs<ExtArgs>>): Prisma.Prisma__MarketplaceRecommendationClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MarketplaceRecommendations.
   * @param {MarketplaceRecommendationCreateManyArgs} args - Arguments to create many MarketplaceRecommendations.
   * @example
   * // Create many MarketplaceRecommendations
   * const marketplaceRecommendation = await prisma.marketplaceRecommendation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MarketplaceRecommendationCreateManyArgs>(args?: Prisma.SelectSubset<T, MarketplaceRecommendationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MarketplaceRecommendations and returns the data saved in the database.
   * @param {MarketplaceRecommendationCreateManyAndReturnArgs} args - Arguments to create many MarketplaceRecommendations.
   * @example
   * // Create many MarketplaceRecommendations
   * const marketplaceRecommendation = await prisma.marketplaceRecommendation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MarketplaceRecommendations and only return the `id`
   * const marketplaceRecommendationWithIdOnly = await prisma.marketplaceRecommendation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MarketplaceRecommendationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MarketplaceRecommendationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MarketplaceRecommendation.
   * @param {MarketplaceRecommendationDeleteArgs} args - Arguments to delete one MarketplaceRecommendation.
   * @example
   * // Delete one MarketplaceRecommendation
   * const MarketplaceRecommendation = await prisma.marketplaceRecommendation.delete({
   *   where: {
   *     // ... filter to delete one MarketplaceRecommendation
   *   }
   * })
   * 
   */
  delete<T extends MarketplaceRecommendationDeleteArgs>(args: Prisma.SelectSubset<T, MarketplaceRecommendationDeleteArgs<ExtArgs>>): Prisma.Prisma__MarketplaceRecommendationClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MarketplaceRecommendation.
   * @param {MarketplaceRecommendationUpdateArgs} args - Arguments to update one MarketplaceRecommendation.
   * @example
   * // Update one MarketplaceRecommendation
   * const marketplaceRecommendation = await prisma.marketplaceRecommendation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MarketplaceRecommendationUpdateArgs>(args: Prisma.SelectSubset<T, MarketplaceRecommendationUpdateArgs<ExtArgs>>): Prisma.Prisma__MarketplaceRecommendationClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MarketplaceRecommendations.
   * @param {MarketplaceRecommendationDeleteManyArgs} args - Arguments to filter MarketplaceRecommendations to delete.
   * @example
   * // Delete a few MarketplaceRecommendations
   * const { count } = await prisma.marketplaceRecommendation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MarketplaceRecommendationDeleteManyArgs>(args?: Prisma.SelectSubset<T, MarketplaceRecommendationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarketplaceRecommendations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceRecommendationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MarketplaceRecommendations
   * const marketplaceRecommendation = await prisma.marketplaceRecommendation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MarketplaceRecommendationUpdateManyArgs>(args: Prisma.SelectSubset<T, MarketplaceRecommendationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarketplaceRecommendations and returns the data updated in the database.
   * @param {MarketplaceRecommendationUpdateManyAndReturnArgs} args - Arguments to update many MarketplaceRecommendations.
   * @example
   * // Update many MarketplaceRecommendations
   * const marketplaceRecommendation = await prisma.marketplaceRecommendation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MarketplaceRecommendations and only return the `id`
   * const marketplaceRecommendationWithIdOnly = await prisma.marketplaceRecommendation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MarketplaceRecommendationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MarketplaceRecommendationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MarketplaceRecommendation.
   * @param {MarketplaceRecommendationUpsertArgs} args - Arguments to update or create a MarketplaceRecommendation.
   * @example
   * // Update or create a MarketplaceRecommendation
   * const marketplaceRecommendation = await prisma.marketplaceRecommendation.upsert({
   *   create: {
   *     // ... data to create a MarketplaceRecommendation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MarketplaceRecommendation we want to update
   *   }
   * })
   */
  upsert<T extends MarketplaceRecommendationUpsertArgs>(args: Prisma.SelectSubset<T, MarketplaceRecommendationUpsertArgs<ExtArgs>>): Prisma.Prisma__MarketplaceRecommendationClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceRecommendationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MarketplaceRecommendations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceRecommendationCountArgs} args - Arguments to filter MarketplaceRecommendations to count.
   * @example
   * // Count the number of MarketplaceRecommendations
   * const count = await prisma.marketplaceRecommendation.count({
   *   where: {
   *     // ... the filter for the MarketplaceRecommendations we want to count
   *   }
   * })
  **/
  count<T extends MarketplaceRecommendationCountArgs>(
    args?: Prisma.Subset<T, MarketplaceRecommendationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MarketplaceRecommendationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MarketplaceRecommendation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceRecommendationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MarketplaceRecommendationAggregateArgs>(args: Prisma.Subset<T, MarketplaceRecommendationAggregateArgs>): Prisma.PrismaPromise<GetMarketplaceRecommendationAggregateType<T>>

  /**
   * Group by MarketplaceRecommendation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceRecommendationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MarketplaceRecommendationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MarketplaceRecommendationGroupByArgs['orderBy'] }
      : { orderBy?: MarketplaceRecommendationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MarketplaceRecommendationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMarketplaceRecommendationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MarketplaceRecommendation model
 */
readonly fields: MarketplaceRecommendationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MarketplaceRecommendation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MarketplaceRecommendationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MarketplaceRecommendation model
 */
export interface MarketplaceRecommendationFieldRefs {
  readonly id: Prisma.FieldRef<"MarketplaceRecommendation", 'String'>
  readonly userId: Prisma.FieldRef<"MarketplaceRecommendation", 'String'>
  readonly listingId: Prisma.FieldRef<"MarketplaceRecommendation", 'String'>
  readonly type: Prisma.FieldRef<"MarketplaceRecommendation", 'String'>
  readonly score: Prisma.FieldRef<"MarketplaceRecommendation", 'Float'>
  readonly reason: Prisma.FieldRef<"MarketplaceRecommendation", 'String'>
  readonly metadata: Prisma.FieldRef<"MarketplaceRecommendation", 'Json'>
  readonly createdAt: Prisma.FieldRef<"MarketplaceRecommendation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MarketplaceRecommendation findUnique
 */
export type MarketplaceRecommendationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * Filter, which MarketplaceRecommendation to fetch.
   */
  where: Prisma.MarketplaceRecommendationWhereUniqueInput
}

/**
 * MarketplaceRecommendation findUniqueOrThrow
 */
export type MarketplaceRecommendationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * Filter, which MarketplaceRecommendation to fetch.
   */
  where: Prisma.MarketplaceRecommendationWhereUniqueInput
}

/**
 * MarketplaceRecommendation findFirst
 */
export type MarketplaceRecommendationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * Filter, which MarketplaceRecommendation to fetch.
   */
  where?: Prisma.MarketplaceRecommendationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketplaceRecommendations to fetch.
   */
  orderBy?: Prisma.MarketplaceRecommendationOrderByWithRelationInput | Prisma.MarketplaceRecommendationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarketplaceRecommendations.
   */
  cursor?: Prisma.MarketplaceRecommendationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketplaceRecommendations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketplaceRecommendations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketplaceRecommendations.
   */
  distinct?: Prisma.MarketplaceRecommendationScalarFieldEnum | Prisma.MarketplaceRecommendationScalarFieldEnum[]
}

/**
 * MarketplaceRecommendation findFirstOrThrow
 */
export type MarketplaceRecommendationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * Filter, which MarketplaceRecommendation to fetch.
   */
  where?: Prisma.MarketplaceRecommendationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketplaceRecommendations to fetch.
   */
  orderBy?: Prisma.MarketplaceRecommendationOrderByWithRelationInput | Prisma.MarketplaceRecommendationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarketplaceRecommendations.
   */
  cursor?: Prisma.MarketplaceRecommendationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketplaceRecommendations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketplaceRecommendations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketplaceRecommendations.
   */
  distinct?: Prisma.MarketplaceRecommendationScalarFieldEnum | Prisma.MarketplaceRecommendationScalarFieldEnum[]
}

/**
 * MarketplaceRecommendation findMany
 */
export type MarketplaceRecommendationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * Filter, which MarketplaceRecommendations to fetch.
   */
  where?: Prisma.MarketplaceRecommendationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketplaceRecommendations to fetch.
   */
  orderBy?: Prisma.MarketplaceRecommendationOrderByWithRelationInput | Prisma.MarketplaceRecommendationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MarketplaceRecommendations.
   */
  cursor?: Prisma.MarketplaceRecommendationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketplaceRecommendations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketplaceRecommendations.
   */
  skip?: number
  distinct?: Prisma.MarketplaceRecommendationScalarFieldEnum | Prisma.MarketplaceRecommendationScalarFieldEnum[]
}

/**
 * MarketplaceRecommendation create
 */
export type MarketplaceRecommendationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * The data needed to create a MarketplaceRecommendation.
   */
  data: Prisma.XOR<Prisma.MarketplaceRecommendationCreateInput, Prisma.MarketplaceRecommendationUncheckedCreateInput>
}

/**
 * MarketplaceRecommendation createMany
 */
export type MarketplaceRecommendationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MarketplaceRecommendations.
   */
  data: Prisma.MarketplaceRecommendationCreateManyInput | Prisma.MarketplaceRecommendationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MarketplaceRecommendation createManyAndReturn
 */
export type MarketplaceRecommendationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * The data used to create many MarketplaceRecommendations.
   */
  data: Prisma.MarketplaceRecommendationCreateManyInput | Prisma.MarketplaceRecommendationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MarketplaceRecommendation update
 */
export type MarketplaceRecommendationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * The data needed to update a MarketplaceRecommendation.
   */
  data: Prisma.XOR<Prisma.MarketplaceRecommendationUpdateInput, Prisma.MarketplaceRecommendationUncheckedUpdateInput>
  /**
   * Choose, which MarketplaceRecommendation to update.
   */
  where: Prisma.MarketplaceRecommendationWhereUniqueInput
}

/**
 * MarketplaceRecommendation updateMany
 */
export type MarketplaceRecommendationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MarketplaceRecommendations.
   */
  data: Prisma.XOR<Prisma.MarketplaceRecommendationUpdateManyMutationInput, Prisma.MarketplaceRecommendationUncheckedUpdateManyInput>
  /**
   * Filter which MarketplaceRecommendations to update
   */
  where?: Prisma.MarketplaceRecommendationWhereInput
  /**
   * Limit how many MarketplaceRecommendations to update.
   */
  limit?: number
}

/**
 * MarketplaceRecommendation updateManyAndReturn
 */
export type MarketplaceRecommendationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * The data used to update MarketplaceRecommendations.
   */
  data: Prisma.XOR<Prisma.MarketplaceRecommendationUpdateManyMutationInput, Prisma.MarketplaceRecommendationUncheckedUpdateManyInput>
  /**
   * Filter which MarketplaceRecommendations to update
   */
  where?: Prisma.MarketplaceRecommendationWhereInput
  /**
   * Limit how many MarketplaceRecommendations to update.
   */
  limit?: number
}

/**
 * MarketplaceRecommendation upsert
 */
export type MarketplaceRecommendationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * The filter to search for the MarketplaceRecommendation to update in case it exists.
   */
  where: Prisma.MarketplaceRecommendationWhereUniqueInput
  /**
   * In case the MarketplaceRecommendation found by the `where` argument doesn't exist, create a new MarketplaceRecommendation with this data.
   */
  create: Prisma.XOR<Prisma.MarketplaceRecommendationCreateInput, Prisma.MarketplaceRecommendationUncheckedCreateInput>
  /**
   * In case the MarketplaceRecommendation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MarketplaceRecommendationUpdateInput, Prisma.MarketplaceRecommendationUncheckedUpdateInput>
}

/**
 * MarketplaceRecommendation delete
 */
export type MarketplaceRecommendationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
  /**
   * Filter which MarketplaceRecommendation to delete.
   */
  where: Prisma.MarketplaceRecommendationWhereUniqueInput
}

/**
 * MarketplaceRecommendation deleteMany
 */
export type MarketplaceRecommendationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarketplaceRecommendations to delete
   */
  where?: Prisma.MarketplaceRecommendationWhereInput
  /**
   * Limit how many MarketplaceRecommendations to delete.
   */
  limit?: number
}

/**
 * MarketplaceRecommendation without action
 */
export type MarketplaceRecommendationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceRecommendation
   */
  select?: Prisma.MarketplaceRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceRecommendation
   */
  omit?: Prisma.MarketplaceRecommendationOmit<ExtArgs> | null
}
