
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MarketplaceSearchHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MarketplaceSearchHistory
 * 
 */
export type MarketplaceSearchHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$MarketplaceSearchHistoryPayload>

export type AggregateMarketplaceSearchHistory = {
  _count: MarketplaceSearchHistoryCountAggregateOutputType | null
  _avg: MarketplaceSearchHistoryAvgAggregateOutputType | null
  _sum: MarketplaceSearchHistorySumAggregateOutputType | null
  _min: MarketplaceSearchHistoryMinAggregateOutputType | null
  _max: MarketplaceSearchHistoryMaxAggregateOutputType | null
}

export type MarketplaceSearchHistoryAvgAggregateOutputType = {
  resultCount: number | null
}

export type MarketplaceSearchHistorySumAggregateOutputType = {
  resultCount: number | null
}

export type MarketplaceSearchHistoryMinAggregateOutputType = {
  id: string | null
  userId: string | null
  query: string | null
  resultCount: number | null
  clickedId: string | null
  createdAt: Date | null
}

export type MarketplaceSearchHistoryMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  query: string | null
  resultCount: number | null
  clickedId: string | null
  createdAt: Date | null
}

export type MarketplaceSearchHistoryCountAggregateOutputType = {
  id: number
  userId: number
  query: number
  filters: number
  resultCount: number
  clickedId: number
  createdAt: number
  _all: number
}


export type MarketplaceSearchHistoryAvgAggregateInputType = {
  resultCount?: true
}

export type MarketplaceSearchHistorySumAggregateInputType = {
  resultCount?: true
}

export type MarketplaceSearchHistoryMinAggregateInputType = {
  id?: true
  userId?: true
  query?: true
  resultCount?: true
  clickedId?: true
  createdAt?: true
}

export type MarketplaceSearchHistoryMaxAggregateInputType = {
  id?: true
  userId?: true
  query?: true
  resultCount?: true
  clickedId?: true
  createdAt?: true
}

export type MarketplaceSearchHistoryCountAggregateInputType = {
  id?: true
  userId?: true
  query?: true
  filters?: true
  resultCount?: true
  clickedId?: true
  createdAt?: true
  _all?: true
}

export type MarketplaceSearchHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarketplaceSearchHistory to aggregate.
   */
  where?: Prisma.MarketplaceSearchHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketplaceSearchHistories to fetch.
   */
  orderBy?: Prisma.MarketplaceSearchHistoryOrderByWithRelationInput | Prisma.MarketplaceSearchHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MarketplaceSearchHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketplaceSearchHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketplaceSearchHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MarketplaceSearchHistories
  **/
  _count?: true | MarketplaceSearchHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MarketplaceSearchHistoryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MarketplaceSearchHistorySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MarketplaceSearchHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MarketplaceSearchHistoryMaxAggregateInputType
}

export type GetMarketplaceSearchHistoryAggregateType<T extends MarketplaceSearchHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateMarketplaceSearchHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMarketplaceSearchHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateMarketplaceSearchHistory[P]>
}




export type MarketplaceSearchHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MarketplaceSearchHistoryWhereInput
  orderBy?: Prisma.MarketplaceSearchHistoryOrderByWithAggregationInput | Prisma.MarketplaceSearchHistoryOrderByWithAggregationInput[]
  by: Prisma.MarketplaceSearchHistoryScalarFieldEnum[] | Prisma.MarketplaceSearchHistoryScalarFieldEnum
  having?: Prisma.MarketplaceSearchHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MarketplaceSearchHistoryCountAggregateInputType | true
  _avg?: MarketplaceSearchHistoryAvgAggregateInputType
  _sum?: MarketplaceSearchHistorySumAggregateInputType
  _min?: MarketplaceSearchHistoryMinAggregateInputType
  _max?: MarketplaceSearchHistoryMaxAggregateInputType
}

export type MarketplaceSearchHistoryGroupByOutputType = {
  id: string
  userId: string | null
  query: string
  filters: runtime.JsonValue | null
  resultCount: number | null
  clickedId: string | null
  createdAt: Date
  _count: MarketplaceSearchHistoryCountAggregateOutputType | null
  _avg: MarketplaceSearchHistoryAvgAggregateOutputType | null
  _sum: MarketplaceSearchHistorySumAggregateOutputType | null
  _min: MarketplaceSearchHistoryMinAggregateOutputType | null
  _max: MarketplaceSearchHistoryMaxAggregateOutputType | null
}

type GetMarketplaceSearchHistoryGroupByPayload<T extends MarketplaceSearchHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MarketplaceSearchHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MarketplaceSearchHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MarketplaceSearchHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MarketplaceSearchHistoryGroupByOutputType[P]>
      }
    >
  >



export type MarketplaceSearchHistoryWhereInput = {
  AND?: Prisma.MarketplaceSearchHistoryWhereInput | Prisma.MarketplaceSearchHistoryWhereInput[]
  OR?: Prisma.MarketplaceSearchHistoryWhereInput[]
  NOT?: Prisma.MarketplaceSearchHistoryWhereInput | Prisma.MarketplaceSearchHistoryWhereInput[]
  id?: Prisma.StringFilter<"MarketplaceSearchHistory"> | string
  userId?: Prisma.StringNullableFilter<"MarketplaceSearchHistory"> | string | null
  query?: Prisma.StringFilter<"MarketplaceSearchHistory"> | string
  filters?: Prisma.JsonNullableFilter<"MarketplaceSearchHistory">
  resultCount?: Prisma.IntNullableFilter<"MarketplaceSearchHistory"> | number | null
  clickedId?: Prisma.StringNullableFilter<"MarketplaceSearchHistory"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MarketplaceSearchHistory"> | Date | string
}

export type MarketplaceSearchHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  query?: Prisma.SortOrder
  filters?: Prisma.SortOrderInput | Prisma.SortOrder
  resultCount?: Prisma.SortOrderInput | Prisma.SortOrder
  clickedId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MarketplaceSearchHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.MarketplaceSearchHistoryWhereInput | Prisma.MarketplaceSearchHistoryWhereInput[]
  OR?: Prisma.MarketplaceSearchHistoryWhereInput[]
  NOT?: Prisma.MarketplaceSearchHistoryWhereInput | Prisma.MarketplaceSearchHistoryWhereInput[]
  userId?: Prisma.StringNullableFilter<"MarketplaceSearchHistory"> | string | null
  query?: Prisma.StringFilter<"MarketplaceSearchHistory"> | string
  filters?: Prisma.JsonNullableFilter<"MarketplaceSearchHistory">
  resultCount?: Prisma.IntNullableFilter<"MarketplaceSearchHistory"> | number | null
  clickedId?: Prisma.StringNullableFilter<"MarketplaceSearchHistory"> | string | null
  createdAt?: Prisma.DateTimeFilter<"MarketplaceSearchHistory"> | Date | string
}, "id">

export type MarketplaceSearchHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  query?: Prisma.SortOrder
  filters?: Prisma.SortOrderInput | Prisma.SortOrder
  resultCount?: Prisma.SortOrderInput | Prisma.SortOrder
  clickedId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MarketplaceSearchHistoryCountOrderByAggregateInput
  _avg?: Prisma.MarketplaceSearchHistoryAvgOrderByAggregateInput
  _max?: Prisma.MarketplaceSearchHistoryMaxOrderByAggregateInput
  _min?: Prisma.MarketplaceSearchHistoryMinOrderByAggregateInput
  _sum?: Prisma.MarketplaceSearchHistorySumOrderByAggregateInput
}

export type MarketplaceSearchHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.MarketplaceSearchHistoryScalarWhereWithAggregatesInput | Prisma.MarketplaceSearchHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.MarketplaceSearchHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MarketplaceSearchHistoryScalarWhereWithAggregatesInput | Prisma.MarketplaceSearchHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MarketplaceSearchHistory"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"MarketplaceSearchHistory"> | string | null
  query?: Prisma.StringWithAggregatesFilter<"MarketplaceSearchHistory"> | string
  filters?: Prisma.JsonNullableWithAggregatesFilter<"MarketplaceSearchHistory">
  resultCount?: Prisma.IntNullableWithAggregatesFilter<"MarketplaceSearchHistory"> | number | null
  clickedId?: Prisma.StringNullableWithAggregatesFilter<"MarketplaceSearchHistory"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MarketplaceSearchHistory"> | Date | string
}

export type MarketplaceSearchHistoryCreateInput = {
  id?: string
  userId?: string | null
  query: string
  filters?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resultCount?: number | null
  clickedId?: string | null
  createdAt?: Date | string
}

export type MarketplaceSearchHistoryUncheckedCreateInput = {
  id?: string
  userId?: string | null
  query: string
  filters?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resultCount?: number | null
  clickedId?: string | null
  createdAt?: Date | string
}

export type MarketplaceSearchHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  query?: Prisma.StringFieldUpdateOperationsInput | string
  filters?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resultCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  clickedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketplaceSearchHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  query?: Prisma.StringFieldUpdateOperationsInput | string
  filters?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resultCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  clickedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketplaceSearchHistoryCreateManyInput = {
  id?: string
  userId?: string | null
  query: string
  filters?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resultCount?: number | null
  clickedId?: string | null
  createdAt?: Date | string
}

export type MarketplaceSearchHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  query?: Prisma.StringFieldUpdateOperationsInput | string
  filters?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resultCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  clickedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketplaceSearchHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  query?: Prisma.StringFieldUpdateOperationsInput | string
  filters?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  resultCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  clickedId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MarketplaceSearchHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  filters?: Prisma.SortOrder
  resultCount?: Prisma.SortOrder
  clickedId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MarketplaceSearchHistoryAvgOrderByAggregateInput = {
  resultCount?: Prisma.SortOrder
}

export type MarketplaceSearchHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  resultCount?: Prisma.SortOrder
  clickedId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MarketplaceSearchHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  query?: Prisma.SortOrder
  resultCount?: Prisma.SortOrder
  clickedId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MarketplaceSearchHistorySumOrderByAggregateInput = {
  resultCount?: Prisma.SortOrder
}



export type MarketplaceSearchHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  query?: boolean
  filters?: boolean
  resultCount?: boolean
  clickedId?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["marketplaceSearchHistory"]>

export type MarketplaceSearchHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  query?: boolean
  filters?: boolean
  resultCount?: boolean
  clickedId?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["marketplaceSearchHistory"]>

export type MarketplaceSearchHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  query?: boolean
  filters?: boolean
  resultCount?: boolean
  clickedId?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["marketplaceSearchHistory"]>

export type MarketplaceSearchHistorySelectScalar = {
  id?: boolean
  userId?: boolean
  query?: boolean
  filters?: boolean
  resultCount?: boolean
  clickedId?: boolean
  createdAt?: boolean
}

export type MarketplaceSearchHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "query" | "filters" | "resultCount" | "clickedId" | "createdAt", ExtArgs["result"]["marketplaceSearchHistory"]>

export type $MarketplaceSearchHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MarketplaceSearchHistory"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string | null
    query: string
    filters: runtime.JsonValue | null
    resultCount: number | null
    clickedId: string | null
    createdAt: Date
  }, ExtArgs["result"]["marketplaceSearchHistory"]>
  composites: {}
}

export type MarketplaceSearchHistoryGetPayload<S extends boolean | null | undefined | MarketplaceSearchHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload, S>

export type MarketplaceSearchHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MarketplaceSearchHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MarketplaceSearchHistoryCountAggregateInputType | true
  }

export interface MarketplaceSearchHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MarketplaceSearchHistory'], meta: { name: 'MarketplaceSearchHistory' } }
  /**
   * Find zero or one MarketplaceSearchHistory that matches the filter.
   * @param {MarketplaceSearchHistoryFindUniqueArgs} args - Arguments to find a MarketplaceSearchHistory
   * @example
   * // Get one MarketplaceSearchHistory
   * const marketplaceSearchHistory = await prisma.marketplaceSearchHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MarketplaceSearchHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, MarketplaceSearchHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MarketplaceSearchHistoryClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MarketplaceSearchHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MarketplaceSearchHistoryFindUniqueOrThrowArgs} args - Arguments to find a MarketplaceSearchHistory
   * @example
   * // Get one MarketplaceSearchHistory
   * const marketplaceSearchHistory = await prisma.marketplaceSearchHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MarketplaceSearchHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MarketplaceSearchHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarketplaceSearchHistoryClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarketplaceSearchHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceSearchHistoryFindFirstArgs} args - Arguments to find a MarketplaceSearchHistory
   * @example
   * // Get one MarketplaceSearchHistory
   * const marketplaceSearchHistory = await prisma.marketplaceSearchHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MarketplaceSearchHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, MarketplaceSearchHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__MarketplaceSearchHistoryClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MarketplaceSearchHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceSearchHistoryFindFirstOrThrowArgs} args - Arguments to find a MarketplaceSearchHistory
   * @example
   * // Get one MarketplaceSearchHistory
   * const marketplaceSearchHistory = await prisma.marketplaceSearchHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MarketplaceSearchHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MarketplaceSearchHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MarketplaceSearchHistoryClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MarketplaceSearchHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceSearchHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MarketplaceSearchHistories
   * const marketplaceSearchHistories = await prisma.marketplaceSearchHistory.findMany()
   * 
   * // Get first 10 MarketplaceSearchHistories
   * const marketplaceSearchHistories = await prisma.marketplaceSearchHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const marketplaceSearchHistoryWithIdOnly = await prisma.marketplaceSearchHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MarketplaceSearchHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, MarketplaceSearchHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MarketplaceSearchHistory.
   * @param {MarketplaceSearchHistoryCreateArgs} args - Arguments to create a MarketplaceSearchHistory.
   * @example
   * // Create one MarketplaceSearchHistory
   * const MarketplaceSearchHistory = await prisma.marketplaceSearchHistory.create({
   *   data: {
   *     // ... data to create a MarketplaceSearchHistory
   *   }
   * })
   * 
   */
  create<T extends MarketplaceSearchHistoryCreateArgs>(args: Prisma.SelectSubset<T, MarketplaceSearchHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__MarketplaceSearchHistoryClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MarketplaceSearchHistories.
   * @param {MarketplaceSearchHistoryCreateManyArgs} args - Arguments to create many MarketplaceSearchHistories.
   * @example
   * // Create many MarketplaceSearchHistories
   * const marketplaceSearchHistory = await prisma.marketplaceSearchHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MarketplaceSearchHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, MarketplaceSearchHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MarketplaceSearchHistories and returns the data saved in the database.
   * @param {MarketplaceSearchHistoryCreateManyAndReturnArgs} args - Arguments to create many MarketplaceSearchHistories.
   * @example
   * // Create many MarketplaceSearchHistories
   * const marketplaceSearchHistory = await prisma.marketplaceSearchHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MarketplaceSearchHistories and only return the `id`
   * const marketplaceSearchHistoryWithIdOnly = await prisma.marketplaceSearchHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MarketplaceSearchHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MarketplaceSearchHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MarketplaceSearchHistory.
   * @param {MarketplaceSearchHistoryDeleteArgs} args - Arguments to delete one MarketplaceSearchHistory.
   * @example
   * // Delete one MarketplaceSearchHistory
   * const MarketplaceSearchHistory = await prisma.marketplaceSearchHistory.delete({
   *   where: {
   *     // ... filter to delete one MarketplaceSearchHistory
   *   }
   * })
   * 
   */
  delete<T extends MarketplaceSearchHistoryDeleteArgs>(args: Prisma.SelectSubset<T, MarketplaceSearchHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__MarketplaceSearchHistoryClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MarketplaceSearchHistory.
   * @param {MarketplaceSearchHistoryUpdateArgs} args - Arguments to update one MarketplaceSearchHistory.
   * @example
   * // Update one MarketplaceSearchHistory
   * const marketplaceSearchHistory = await prisma.marketplaceSearchHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MarketplaceSearchHistoryUpdateArgs>(args: Prisma.SelectSubset<T, MarketplaceSearchHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__MarketplaceSearchHistoryClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MarketplaceSearchHistories.
   * @param {MarketplaceSearchHistoryDeleteManyArgs} args - Arguments to filter MarketplaceSearchHistories to delete.
   * @example
   * // Delete a few MarketplaceSearchHistories
   * const { count } = await prisma.marketplaceSearchHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MarketplaceSearchHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, MarketplaceSearchHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarketplaceSearchHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceSearchHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MarketplaceSearchHistories
   * const marketplaceSearchHistory = await prisma.marketplaceSearchHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MarketplaceSearchHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, MarketplaceSearchHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MarketplaceSearchHistories and returns the data updated in the database.
   * @param {MarketplaceSearchHistoryUpdateManyAndReturnArgs} args - Arguments to update many MarketplaceSearchHistories.
   * @example
   * // Update many MarketplaceSearchHistories
   * const marketplaceSearchHistory = await prisma.marketplaceSearchHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MarketplaceSearchHistories and only return the `id`
   * const marketplaceSearchHistoryWithIdOnly = await prisma.marketplaceSearchHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MarketplaceSearchHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MarketplaceSearchHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MarketplaceSearchHistory.
   * @param {MarketplaceSearchHistoryUpsertArgs} args - Arguments to update or create a MarketplaceSearchHistory.
   * @example
   * // Update or create a MarketplaceSearchHistory
   * const marketplaceSearchHistory = await prisma.marketplaceSearchHistory.upsert({
   *   create: {
   *     // ... data to create a MarketplaceSearchHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MarketplaceSearchHistory we want to update
   *   }
   * })
   */
  upsert<T extends MarketplaceSearchHistoryUpsertArgs>(args: Prisma.SelectSubset<T, MarketplaceSearchHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__MarketplaceSearchHistoryClient<runtime.Types.Result.GetResult<Prisma.$MarketplaceSearchHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MarketplaceSearchHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceSearchHistoryCountArgs} args - Arguments to filter MarketplaceSearchHistories to count.
   * @example
   * // Count the number of MarketplaceSearchHistories
   * const count = await prisma.marketplaceSearchHistory.count({
   *   where: {
   *     // ... the filter for the MarketplaceSearchHistories we want to count
   *   }
   * })
  **/
  count<T extends MarketplaceSearchHistoryCountArgs>(
    args?: Prisma.Subset<T, MarketplaceSearchHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MarketplaceSearchHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MarketplaceSearchHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceSearchHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MarketplaceSearchHistoryAggregateArgs>(args: Prisma.Subset<T, MarketplaceSearchHistoryAggregateArgs>): Prisma.PrismaPromise<GetMarketplaceSearchHistoryAggregateType<T>>

  /**
   * Group by MarketplaceSearchHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MarketplaceSearchHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MarketplaceSearchHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MarketplaceSearchHistoryGroupByArgs['orderBy'] }
      : { orderBy?: MarketplaceSearchHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MarketplaceSearchHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMarketplaceSearchHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MarketplaceSearchHistory model
 */
readonly fields: MarketplaceSearchHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MarketplaceSearchHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MarketplaceSearchHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MarketplaceSearchHistory model
 */
export interface MarketplaceSearchHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"MarketplaceSearchHistory", 'String'>
  readonly userId: Prisma.FieldRef<"MarketplaceSearchHistory", 'String'>
  readonly query: Prisma.FieldRef<"MarketplaceSearchHistory", 'String'>
  readonly filters: Prisma.FieldRef<"MarketplaceSearchHistory", 'Json'>
  readonly resultCount: Prisma.FieldRef<"MarketplaceSearchHistory", 'Int'>
  readonly clickedId: Prisma.FieldRef<"MarketplaceSearchHistory", 'String'>
  readonly createdAt: Prisma.FieldRef<"MarketplaceSearchHistory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MarketplaceSearchHistory findUnique
 */
export type MarketplaceSearchHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * Filter, which MarketplaceSearchHistory to fetch.
   */
  where: Prisma.MarketplaceSearchHistoryWhereUniqueInput
}

/**
 * MarketplaceSearchHistory findUniqueOrThrow
 */
export type MarketplaceSearchHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * Filter, which MarketplaceSearchHistory to fetch.
   */
  where: Prisma.MarketplaceSearchHistoryWhereUniqueInput
}

/**
 * MarketplaceSearchHistory findFirst
 */
export type MarketplaceSearchHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * Filter, which MarketplaceSearchHistory to fetch.
   */
  where?: Prisma.MarketplaceSearchHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketplaceSearchHistories to fetch.
   */
  orderBy?: Prisma.MarketplaceSearchHistoryOrderByWithRelationInput | Prisma.MarketplaceSearchHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarketplaceSearchHistories.
   */
  cursor?: Prisma.MarketplaceSearchHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketplaceSearchHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketplaceSearchHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketplaceSearchHistories.
   */
  distinct?: Prisma.MarketplaceSearchHistoryScalarFieldEnum | Prisma.MarketplaceSearchHistoryScalarFieldEnum[]
}

/**
 * MarketplaceSearchHistory findFirstOrThrow
 */
export type MarketplaceSearchHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * Filter, which MarketplaceSearchHistory to fetch.
   */
  where?: Prisma.MarketplaceSearchHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketplaceSearchHistories to fetch.
   */
  orderBy?: Prisma.MarketplaceSearchHistoryOrderByWithRelationInput | Prisma.MarketplaceSearchHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MarketplaceSearchHistories.
   */
  cursor?: Prisma.MarketplaceSearchHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketplaceSearchHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketplaceSearchHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MarketplaceSearchHistories.
   */
  distinct?: Prisma.MarketplaceSearchHistoryScalarFieldEnum | Prisma.MarketplaceSearchHistoryScalarFieldEnum[]
}

/**
 * MarketplaceSearchHistory findMany
 */
export type MarketplaceSearchHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * Filter, which MarketplaceSearchHistories to fetch.
   */
  where?: Prisma.MarketplaceSearchHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MarketplaceSearchHistories to fetch.
   */
  orderBy?: Prisma.MarketplaceSearchHistoryOrderByWithRelationInput | Prisma.MarketplaceSearchHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MarketplaceSearchHistories.
   */
  cursor?: Prisma.MarketplaceSearchHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MarketplaceSearchHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MarketplaceSearchHistories.
   */
  skip?: number
  distinct?: Prisma.MarketplaceSearchHistoryScalarFieldEnum | Prisma.MarketplaceSearchHistoryScalarFieldEnum[]
}

/**
 * MarketplaceSearchHistory create
 */
export type MarketplaceSearchHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * The data needed to create a MarketplaceSearchHistory.
   */
  data: Prisma.XOR<Prisma.MarketplaceSearchHistoryCreateInput, Prisma.MarketplaceSearchHistoryUncheckedCreateInput>
}

/**
 * MarketplaceSearchHistory createMany
 */
export type MarketplaceSearchHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MarketplaceSearchHistories.
   */
  data: Prisma.MarketplaceSearchHistoryCreateManyInput | Prisma.MarketplaceSearchHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MarketplaceSearchHistory createManyAndReturn
 */
export type MarketplaceSearchHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many MarketplaceSearchHistories.
   */
  data: Prisma.MarketplaceSearchHistoryCreateManyInput | Prisma.MarketplaceSearchHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MarketplaceSearchHistory update
 */
export type MarketplaceSearchHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * The data needed to update a MarketplaceSearchHistory.
   */
  data: Prisma.XOR<Prisma.MarketplaceSearchHistoryUpdateInput, Prisma.MarketplaceSearchHistoryUncheckedUpdateInput>
  /**
   * Choose, which MarketplaceSearchHistory to update.
   */
  where: Prisma.MarketplaceSearchHistoryWhereUniqueInput
}

/**
 * MarketplaceSearchHistory updateMany
 */
export type MarketplaceSearchHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MarketplaceSearchHistories.
   */
  data: Prisma.XOR<Prisma.MarketplaceSearchHistoryUpdateManyMutationInput, Prisma.MarketplaceSearchHistoryUncheckedUpdateManyInput>
  /**
   * Filter which MarketplaceSearchHistories to update
   */
  where?: Prisma.MarketplaceSearchHistoryWhereInput
  /**
   * Limit how many MarketplaceSearchHistories to update.
   */
  limit?: number
}

/**
 * MarketplaceSearchHistory updateManyAndReturn
 */
export type MarketplaceSearchHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * The data used to update MarketplaceSearchHistories.
   */
  data: Prisma.XOR<Prisma.MarketplaceSearchHistoryUpdateManyMutationInput, Prisma.MarketplaceSearchHistoryUncheckedUpdateManyInput>
  /**
   * Filter which MarketplaceSearchHistories to update
   */
  where?: Prisma.MarketplaceSearchHistoryWhereInput
  /**
   * Limit how many MarketplaceSearchHistories to update.
   */
  limit?: number
}

/**
 * MarketplaceSearchHistory upsert
 */
export type MarketplaceSearchHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * The filter to search for the MarketplaceSearchHistory to update in case it exists.
   */
  where: Prisma.MarketplaceSearchHistoryWhereUniqueInput
  /**
   * In case the MarketplaceSearchHistory found by the `where` argument doesn't exist, create a new MarketplaceSearchHistory with this data.
   */
  create: Prisma.XOR<Prisma.MarketplaceSearchHistoryCreateInput, Prisma.MarketplaceSearchHistoryUncheckedCreateInput>
  /**
   * In case the MarketplaceSearchHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MarketplaceSearchHistoryUpdateInput, Prisma.MarketplaceSearchHistoryUncheckedUpdateInput>
}

/**
 * MarketplaceSearchHistory delete
 */
export type MarketplaceSearchHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
  /**
   * Filter which MarketplaceSearchHistory to delete.
   */
  where: Prisma.MarketplaceSearchHistoryWhereUniqueInput
}

/**
 * MarketplaceSearchHistory deleteMany
 */
export type MarketplaceSearchHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MarketplaceSearchHistories to delete
   */
  where?: Prisma.MarketplaceSearchHistoryWhereInput
  /**
   * Limit how many MarketplaceSearchHistories to delete.
   */
  limit?: number
}

/**
 * MarketplaceSearchHistory without action
 */
export type MarketplaceSearchHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MarketplaceSearchHistory
   */
  select?: Prisma.MarketplaceSearchHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MarketplaceSearchHistory
   */
  omit?: Prisma.MarketplaceSearchHistoryOmit<ExtArgs> | null
}
