
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PublisherBalance` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PublisherBalance
 * 
 */
export type PublisherBalanceModel = runtime.Types.Result.DefaultSelection<Prisma.$PublisherBalancePayload>

export type AggregatePublisherBalance = {
  _count: PublisherBalanceCountAggregateOutputType | null
  _avg: PublisherBalanceAvgAggregateOutputType | null
  _sum: PublisherBalanceSumAggregateOutputType | null
  _min: PublisherBalanceMinAggregateOutputType | null
  _max: PublisherBalanceMaxAggregateOutputType | null
}

export type PublisherBalanceAvgAggregateOutputType = {
  pendingBalance: runtime.Decimal | null
  approvedBalance: runtime.Decimal | null
  withdrawableBalance: runtime.Decimal | null
  lifetimeEarnings: runtime.Decimal | null
}

export type PublisherBalanceSumAggregateOutputType = {
  pendingBalance: runtime.Decimal | null
  approvedBalance: runtime.Decimal | null
  withdrawableBalance: runtime.Decimal | null
  lifetimeEarnings: runtime.Decimal | null
}

export type PublisherBalanceMinAggregateOutputType = {
  id: string | null
  publisherId: string | null
  pendingBalance: runtime.Decimal | null
  approvedBalance: runtime.Decimal | null
  withdrawableBalance: runtime.Decimal | null
  lifetimeEarnings: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PublisherBalanceMaxAggregateOutputType = {
  id: string | null
  publisherId: string | null
  pendingBalance: runtime.Decimal | null
  approvedBalance: runtime.Decimal | null
  withdrawableBalance: runtime.Decimal | null
  lifetimeEarnings: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PublisherBalanceCountAggregateOutputType = {
  id: number
  publisherId: number
  pendingBalance: number
  approvedBalance: number
  withdrawableBalance: number
  lifetimeEarnings: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PublisherBalanceAvgAggregateInputType = {
  pendingBalance?: true
  approvedBalance?: true
  withdrawableBalance?: true
  lifetimeEarnings?: true
}

export type PublisherBalanceSumAggregateInputType = {
  pendingBalance?: true
  approvedBalance?: true
  withdrawableBalance?: true
  lifetimeEarnings?: true
}

export type PublisherBalanceMinAggregateInputType = {
  id?: true
  publisherId?: true
  pendingBalance?: true
  approvedBalance?: true
  withdrawableBalance?: true
  lifetimeEarnings?: true
  createdAt?: true
  updatedAt?: true
}

export type PublisherBalanceMaxAggregateInputType = {
  id?: true
  publisherId?: true
  pendingBalance?: true
  approvedBalance?: true
  withdrawableBalance?: true
  lifetimeEarnings?: true
  createdAt?: true
  updatedAt?: true
}

export type PublisherBalanceCountAggregateInputType = {
  id?: true
  publisherId?: true
  pendingBalance?: true
  approvedBalance?: true
  withdrawableBalance?: true
  lifetimeEarnings?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PublisherBalanceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PublisherBalance to aggregate.
   */
  where?: Prisma.PublisherBalanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PublisherBalances to fetch.
   */
  orderBy?: Prisma.PublisherBalanceOrderByWithRelationInput | Prisma.PublisherBalanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PublisherBalanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PublisherBalances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PublisherBalances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PublisherBalances
  **/
  _count?: true | PublisherBalanceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PublisherBalanceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PublisherBalanceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PublisherBalanceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PublisherBalanceMaxAggregateInputType
}

export type GetPublisherBalanceAggregateType<T extends PublisherBalanceAggregateArgs> = {
      [P in keyof T & keyof AggregatePublisherBalance]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePublisherBalance[P]>
    : Prisma.GetScalarType<T[P], AggregatePublisherBalance[P]>
}




export type PublisherBalanceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PublisherBalanceWhereInput
  orderBy?: Prisma.PublisherBalanceOrderByWithAggregationInput | Prisma.PublisherBalanceOrderByWithAggregationInput[]
  by: Prisma.PublisherBalanceScalarFieldEnum[] | Prisma.PublisherBalanceScalarFieldEnum
  having?: Prisma.PublisherBalanceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PublisherBalanceCountAggregateInputType | true
  _avg?: PublisherBalanceAvgAggregateInputType
  _sum?: PublisherBalanceSumAggregateInputType
  _min?: PublisherBalanceMinAggregateInputType
  _max?: PublisherBalanceMaxAggregateInputType
}

export type PublisherBalanceGroupByOutputType = {
  id: string
  publisherId: string
  pendingBalance: runtime.Decimal
  approvedBalance: runtime.Decimal
  withdrawableBalance: runtime.Decimal
  lifetimeEarnings: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: PublisherBalanceCountAggregateOutputType | null
  _avg: PublisherBalanceAvgAggregateOutputType | null
  _sum: PublisherBalanceSumAggregateOutputType | null
  _min: PublisherBalanceMinAggregateOutputType | null
  _max: PublisherBalanceMaxAggregateOutputType | null
}

type GetPublisherBalanceGroupByPayload<T extends PublisherBalanceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PublisherBalanceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PublisherBalanceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PublisherBalanceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PublisherBalanceGroupByOutputType[P]>
      }
    >
  >



export type PublisherBalanceWhereInput = {
  AND?: Prisma.PublisherBalanceWhereInput | Prisma.PublisherBalanceWhereInput[]
  OR?: Prisma.PublisherBalanceWhereInput[]
  NOT?: Prisma.PublisherBalanceWhereInput | Prisma.PublisherBalanceWhereInput[]
  id?: Prisma.StringFilter<"PublisherBalance"> | string
  publisherId?: Prisma.StringFilter<"PublisherBalance"> | string
  pendingBalance?: Prisma.DecimalFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: Prisma.DecimalFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: Prisma.DecimalFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: Prisma.DecimalFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"PublisherBalance"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PublisherBalance"> | Date | string
  publisher?: Prisma.XOR<Prisma.PublisherScalarRelationFilter, Prisma.PublisherWhereInput>
}

export type PublisherBalanceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  publisherId?: Prisma.SortOrder
  pendingBalance?: Prisma.SortOrder
  approvedBalance?: Prisma.SortOrder
  withdrawableBalance?: Prisma.SortOrder
  lifetimeEarnings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  publisher?: Prisma.PublisherOrderByWithRelationInput
}

export type PublisherBalanceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  publisherId?: string
  AND?: Prisma.PublisherBalanceWhereInput | Prisma.PublisherBalanceWhereInput[]
  OR?: Prisma.PublisherBalanceWhereInput[]
  NOT?: Prisma.PublisherBalanceWhereInput | Prisma.PublisherBalanceWhereInput[]
  pendingBalance?: Prisma.DecimalFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: Prisma.DecimalFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: Prisma.DecimalFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: Prisma.DecimalFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"PublisherBalance"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"PublisherBalance"> | Date | string
  publisher?: Prisma.XOR<Prisma.PublisherScalarRelationFilter, Prisma.PublisherWhereInput>
}, "id" | "publisherId">

export type PublisherBalanceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  publisherId?: Prisma.SortOrder
  pendingBalance?: Prisma.SortOrder
  approvedBalance?: Prisma.SortOrder
  withdrawableBalance?: Prisma.SortOrder
  lifetimeEarnings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PublisherBalanceCountOrderByAggregateInput
  _avg?: Prisma.PublisherBalanceAvgOrderByAggregateInput
  _max?: Prisma.PublisherBalanceMaxOrderByAggregateInput
  _min?: Prisma.PublisherBalanceMinOrderByAggregateInput
  _sum?: Prisma.PublisherBalanceSumOrderByAggregateInput
}

export type PublisherBalanceScalarWhereWithAggregatesInput = {
  AND?: Prisma.PublisherBalanceScalarWhereWithAggregatesInput | Prisma.PublisherBalanceScalarWhereWithAggregatesInput[]
  OR?: Prisma.PublisherBalanceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PublisherBalanceScalarWhereWithAggregatesInput | Prisma.PublisherBalanceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PublisherBalance"> | string
  publisherId?: Prisma.StringWithAggregatesFilter<"PublisherBalance"> | string
  pendingBalance?: Prisma.DecimalWithAggregatesFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: Prisma.DecimalWithAggregatesFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: Prisma.DecimalWithAggregatesFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: Prisma.DecimalWithAggregatesFilter<"PublisherBalance"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"PublisherBalance"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"PublisherBalance"> | Date | string
}

export type PublisherBalanceCreateInput = {
  id?: string
  pendingBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  publisher: Prisma.PublisherCreateNestedOneWithoutBalanceInput
}

export type PublisherBalanceUncheckedCreateInput = {
  id?: string
  publisherId: string
  pendingBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PublisherBalanceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pendingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  publisher?: Prisma.PublisherUpdateOneRequiredWithoutBalanceNestedInput
}

export type PublisherBalanceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  publisherId?: Prisma.StringFieldUpdateOperationsInput | string
  pendingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PublisherBalanceCreateManyInput = {
  id?: string
  publisherId: string
  pendingBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PublisherBalanceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pendingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PublisherBalanceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  publisherId?: Prisma.StringFieldUpdateOperationsInput | string
  pendingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PublisherBalanceNullableScalarRelationFilter = {
  is?: Prisma.PublisherBalanceWhereInput | null
  isNot?: Prisma.PublisherBalanceWhereInput | null
}

export type PublisherBalanceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  publisherId?: Prisma.SortOrder
  pendingBalance?: Prisma.SortOrder
  approvedBalance?: Prisma.SortOrder
  withdrawableBalance?: Prisma.SortOrder
  lifetimeEarnings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PublisherBalanceAvgOrderByAggregateInput = {
  pendingBalance?: Prisma.SortOrder
  approvedBalance?: Prisma.SortOrder
  withdrawableBalance?: Prisma.SortOrder
  lifetimeEarnings?: Prisma.SortOrder
}

export type PublisherBalanceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  publisherId?: Prisma.SortOrder
  pendingBalance?: Prisma.SortOrder
  approvedBalance?: Prisma.SortOrder
  withdrawableBalance?: Prisma.SortOrder
  lifetimeEarnings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PublisherBalanceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  publisherId?: Prisma.SortOrder
  pendingBalance?: Prisma.SortOrder
  approvedBalance?: Prisma.SortOrder
  withdrawableBalance?: Prisma.SortOrder
  lifetimeEarnings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PublisherBalanceSumOrderByAggregateInput = {
  pendingBalance?: Prisma.SortOrder
  approvedBalance?: Prisma.SortOrder
  withdrawableBalance?: Prisma.SortOrder
  lifetimeEarnings?: Prisma.SortOrder
}

export type PublisherBalanceCreateNestedOneWithoutPublisherInput = {
  create?: Prisma.XOR<Prisma.PublisherBalanceCreateWithoutPublisherInput, Prisma.PublisherBalanceUncheckedCreateWithoutPublisherInput>
  connectOrCreate?: Prisma.PublisherBalanceCreateOrConnectWithoutPublisherInput
  connect?: Prisma.PublisherBalanceWhereUniqueInput
}

export type PublisherBalanceUncheckedCreateNestedOneWithoutPublisherInput = {
  create?: Prisma.XOR<Prisma.PublisherBalanceCreateWithoutPublisherInput, Prisma.PublisherBalanceUncheckedCreateWithoutPublisherInput>
  connectOrCreate?: Prisma.PublisherBalanceCreateOrConnectWithoutPublisherInput
  connect?: Prisma.PublisherBalanceWhereUniqueInput
}

export type PublisherBalanceUpdateOneWithoutPublisherNestedInput = {
  create?: Prisma.XOR<Prisma.PublisherBalanceCreateWithoutPublisherInput, Prisma.PublisherBalanceUncheckedCreateWithoutPublisherInput>
  connectOrCreate?: Prisma.PublisherBalanceCreateOrConnectWithoutPublisherInput
  upsert?: Prisma.PublisherBalanceUpsertWithoutPublisherInput
  disconnect?: Prisma.PublisherBalanceWhereInput | boolean
  delete?: Prisma.PublisherBalanceWhereInput | boolean
  connect?: Prisma.PublisherBalanceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PublisherBalanceUpdateToOneWithWhereWithoutPublisherInput, Prisma.PublisherBalanceUpdateWithoutPublisherInput>, Prisma.PublisherBalanceUncheckedUpdateWithoutPublisherInput>
}

export type PublisherBalanceUncheckedUpdateOneWithoutPublisherNestedInput = {
  create?: Prisma.XOR<Prisma.PublisherBalanceCreateWithoutPublisherInput, Prisma.PublisherBalanceUncheckedCreateWithoutPublisherInput>
  connectOrCreate?: Prisma.PublisherBalanceCreateOrConnectWithoutPublisherInput
  upsert?: Prisma.PublisherBalanceUpsertWithoutPublisherInput
  disconnect?: Prisma.PublisherBalanceWhereInput | boolean
  delete?: Prisma.PublisherBalanceWhereInput | boolean
  connect?: Prisma.PublisherBalanceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PublisherBalanceUpdateToOneWithWhereWithoutPublisherInput, Prisma.PublisherBalanceUpdateWithoutPublisherInput>, Prisma.PublisherBalanceUncheckedUpdateWithoutPublisherInput>
}

export type PublisherBalanceCreateWithoutPublisherInput = {
  id?: string
  pendingBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PublisherBalanceUncheckedCreateWithoutPublisherInput = {
  id?: string
  pendingBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PublisherBalanceCreateOrConnectWithoutPublisherInput = {
  where: Prisma.PublisherBalanceWhereUniqueInput
  create: Prisma.XOR<Prisma.PublisherBalanceCreateWithoutPublisherInput, Prisma.PublisherBalanceUncheckedCreateWithoutPublisherInput>
}

export type PublisherBalanceUpsertWithoutPublisherInput = {
  update: Prisma.XOR<Prisma.PublisherBalanceUpdateWithoutPublisherInput, Prisma.PublisherBalanceUncheckedUpdateWithoutPublisherInput>
  create: Prisma.XOR<Prisma.PublisherBalanceCreateWithoutPublisherInput, Prisma.PublisherBalanceUncheckedCreateWithoutPublisherInput>
  where?: Prisma.PublisherBalanceWhereInput
}

export type PublisherBalanceUpdateToOneWithWhereWithoutPublisherInput = {
  where?: Prisma.PublisherBalanceWhereInput
  data: Prisma.XOR<Prisma.PublisherBalanceUpdateWithoutPublisherInput, Prisma.PublisherBalanceUncheckedUpdateWithoutPublisherInput>
}

export type PublisherBalanceUpdateWithoutPublisherInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pendingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PublisherBalanceUncheckedUpdateWithoutPublisherInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pendingBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  approvedBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  withdrawableBalance?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  lifetimeEarnings?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PublisherBalanceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  publisherId?: boolean
  pendingBalance?: boolean
  approvedBalance?: boolean
  withdrawableBalance?: boolean
  lifetimeEarnings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publisher?: boolean | Prisma.PublisherDefaultArgs<ExtArgs>
}, ExtArgs["result"]["publisherBalance"]>

export type PublisherBalanceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  publisherId?: boolean
  pendingBalance?: boolean
  approvedBalance?: boolean
  withdrawableBalance?: boolean
  lifetimeEarnings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publisher?: boolean | Prisma.PublisherDefaultArgs<ExtArgs>
}, ExtArgs["result"]["publisherBalance"]>

export type PublisherBalanceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  publisherId?: boolean
  pendingBalance?: boolean
  approvedBalance?: boolean
  withdrawableBalance?: boolean
  lifetimeEarnings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  publisher?: boolean | Prisma.PublisherDefaultArgs<ExtArgs>
}, ExtArgs["result"]["publisherBalance"]>

export type PublisherBalanceSelectScalar = {
  id?: boolean
  publisherId?: boolean
  pendingBalance?: boolean
  approvedBalance?: boolean
  withdrawableBalance?: boolean
  lifetimeEarnings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PublisherBalanceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "publisherId" | "pendingBalance" | "approvedBalance" | "withdrawableBalance" | "lifetimeEarnings" | "createdAt" | "updatedAt", ExtArgs["result"]["publisherBalance"]>
export type PublisherBalanceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  publisher?: boolean | Prisma.PublisherDefaultArgs<ExtArgs>
}
export type PublisherBalanceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  publisher?: boolean | Prisma.PublisherDefaultArgs<ExtArgs>
}
export type PublisherBalanceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  publisher?: boolean | Prisma.PublisherDefaultArgs<ExtArgs>
}

export type $PublisherBalancePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PublisherBalance"
  objects: {
    publisher: Prisma.$PublisherPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    publisherId: string
    pendingBalance: runtime.Decimal
    approvedBalance: runtime.Decimal
    withdrawableBalance: runtime.Decimal
    lifetimeEarnings: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["publisherBalance"]>
  composites: {}
}

export type PublisherBalanceGetPayload<S extends boolean | null | undefined | PublisherBalanceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload, S>

export type PublisherBalanceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PublisherBalanceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PublisherBalanceCountAggregateInputType | true
  }

export interface PublisherBalanceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PublisherBalance'], meta: { name: 'PublisherBalance' } }
  /**
   * Find zero or one PublisherBalance that matches the filter.
   * @param {PublisherBalanceFindUniqueArgs} args - Arguments to find a PublisherBalance
   * @example
   * // Get one PublisherBalance
   * const publisherBalance = await prisma.publisherBalance.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PublisherBalanceFindUniqueArgs>(args: Prisma.SelectSubset<T, PublisherBalanceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PublisherBalanceClient<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PublisherBalance that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PublisherBalanceFindUniqueOrThrowArgs} args - Arguments to find a PublisherBalance
   * @example
   * // Get one PublisherBalance
   * const publisherBalance = await prisma.publisherBalance.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PublisherBalanceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PublisherBalanceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PublisherBalanceClient<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PublisherBalance that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublisherBalanceFindFirstArgs} args - Arguments to find a PublisherBalance
   * @example
   * // Get one PublisherBalance
   * const publisherBalance = await prisma.publisherBalance.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PublisherBalanceFindFirstArgs>(args?: Prisma.SelectSubset<T, PublisherBalanceFindFirstArgs<ExtArgs>>): Prisma.Prisma__PublisherBalanceClient<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PublisherBalance that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublisherBalanceFindFirstOrThrowArgs} args - Arguments to find a PublisherBalance
   * @example
   * // Get one PublisherBalance
   * const publisherBalance = await prisma.publisherBalance.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PublisherBalanceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PublisherBalanceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PublisherBalanceClient<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PublisherBalances that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublisherBalanceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PublisherBalances
   * const publisherBalances = await prisma.publisherBalance.findMany()
   * 
   * // Get first 10 PublisherBalances
   * const publisherBalances = await prisma.publisherBalance.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const publisherBalanceWithIdOnly = await prisma.publisherBalance.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PublisherBalanceFindManyArgs>(args?: Prisma.SelectSubset<T, PublisherBalanceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PublisherBalance.
   * @param {PublisherBalanceCreateArgs} args - Arguments to create a PublisherBalance.
   * @example
   * // Create one PublisherBalance
   * const PublisherBalance = await prisma.publisherBalance.create({
   *   data: {
   *     // ... data to create a PublisherBalance
   *   }
   * })
   * 
   */
  create<T extends PublisherBalanceCreateArgs>(args: Prisma.SelectSubset<T, PublisherBalanceCreateArgs<ExtArgs>>): Prisma.Prisma__PublisherBalanceClient<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PublisherBalances.
   * @param {PublisherBalanceCreateManyArgs} args - Arguments to create many PublisherBalances.
   * @example
   * // Create many PublisherBalances
   * const publisherBalance = await prisma.publisherBalance.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PublisherBalanceCreateManyArgs>(args?: Prisma.SelectSubset<T, PublisherBalanceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PublisherBalances and returns the data saved in the database.
   * @param {PublisherBalanceCreateManyAndReturnArgs} args - Arguments to create many PublisherBalances.
   * @example
   * // Create many PublisherBalances
   * const publisherBalance = await prisma.publisherBalance.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PublisherBalances and only return the `id`
   * const publisherBalanceWithIdOnly = await prisma.publisherBalance.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PublisherBalanceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PublisherBalanceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PublisherBalance.
   * @param {PublisherBalanceDeleteArgs} args - Arguments to delete one PublisherBalance.
   * @example
   * // Delete one PublisherBalance
   * const PublisherBalance = await prisma.publisherBalance.delete({
   *   where: {
   *     // ... filter to delete one PublisherBalance
   *   }
   * })
   * 
   */
  delete<T extends PublisherBalanceDeleteArgs>(args: Prisma.SelectSubset<T, PublisherBalanceDeleteArgs<ExtArgs>>): Prisma.Prisma__PublisherBalanceClient<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PublisherBalance.
   * @param {PublisherBalanceUpdateArgs} args - Arguments to update one PublisherBalance.
   * @example
   * // Update one PublisherBalance
   * const publisherBalance = await prisma.publisherBalance.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PublisherBalanceUpdateArgs>(args: Prisma.SelectSubset<T, PublisherBalanceUpdateArgs<ExtArgs>>): Prisma.Prisma__PublisherBalanceClient<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PublisherBalances.
   * @param {PublisherBalanceDeleteManyArgs} args - Arguments to filter PublisherBalances to delete.
   * @example
   * // Delete a few PublisherBalances
   * const { count } = await prisma.publisherBalance.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PublisherBalanceDeleteManyArgs>(args?: Prisma.SelectSubset<T, PublisherBalanceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PublisherBalances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublisherBalanceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PublisherBalances
   * const publisherBalance = await prisma.publisherBalance.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PublisherBalanceUpdateManyArgs>(args: Prisma.SelectSubset<T, PublisherBalanceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PublisherBalances and returns the data updated in the database.
   * @param {PublisherBalanceUpdateManyAndReturnArgs} args - Arguments to update many PublisherBalances.
   * @example
   * // Update many PublisherBalances
   * const publisherBalance = await prisma.publisherBalance.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PublisherBalances and only return the `id`
   * const publisherBalanceWithIdOnly = await prisma.publisherBalance.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PublisherBalanceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PublisherBalanceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PublisherBalance.
   * @param {PublisherBalanceUpsertArgs} args - Arguments to update or create a PublisherBalance.
   * @example
   * // Update or create a PublisherBalance
   * const publisherBalance = await prisma.publisherBalance.upsert({
   *   create: {
   *     // ... data to create a PublisherBalance
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PublisherBalance we want to update
   *   }
   * })
   */
  upsert<T extends PublisherBalanceUpsertArgs>(args: Prisma.SelectSubset<T, PublisherBalanceUpsertArgs<ExtArgs>>): Prisma.Prisma__PublisherBalanceClient<runtime.Types.Result.GetResult<Prisma.$PublisherBalancePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PublisherBalances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublisherBalanceCountArgs} args - Arguments to filter PublisherBalances to count.
   * @example
   * // Count the number of PublisherBalances
   * const count = await prisma.publisherBalance.count({
   *   where: {
   *     // ... the filter for the PublisherBalances we want to count
   *   }
   * })
  **/
  count<T extends PublisherBalanceCountArgs>(
    args?: Prisma.Subset<T, PublisherBalanceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PublisherBalanceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PublisherBalance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublisherBalanceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PublisherBalanceAggregateArgs>(args: Prisma.Subset<T, PublisherBalanceAggregateArgs>): Prisma.PrismaPromise<GetPublisherBalanceAggregateType<T>>

  /**
   * Group by PublisherBalance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PublisherBalanceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PublisherBalanceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PublisherBalanceGroupByArgs['orderBy'] }
      : { orderBy?: PublisherBalanceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PublisherBalanceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPublisherBalanceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PublisherBalance model
 */
readonly fields: PublisherBalanceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PublisherBalance.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PublisherBalanceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  publisher<T extends Prisma.PublisherDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PublisherDefaultArgs<ExtArgs>>): Prisma.Prisma__PublisherClient<runtime.Types.Result.GetResult<Prisma.$PublisherPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PublisherBalance model
 */
export interface PublisherBalanceFieldRefs {
  readonly id: Prisma.FieldRef<"PublisherBalance", 'String'>
  readonly publisherId: Prisma.FieldRef<"PublisherBalance", 'String'>
  readonly pendingBalance: Prisma.FieldRef<"PublisherBalance", 'Decimal'>
  readonly approvedBalance: Prisma.FieldRef<"PublisherBalance", 'Decimal'>
  readonly withdrawableBalance: Prisma.FieldRef<"PublisherBalance", 'Decimal'>
  readonly lifetimeEarnings: Prisma.FieldRef<"PublisherBalance", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"PublisherBalance", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"PublisherBalance", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PublisherBalance findUnique
 */
export type PublisherBalanceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceInclude<ExtArgs> | null
  /**
   * Filter, which PublisherBalance to fetch.
   */
  where: Prisma.PublisherBalanceWhereUniqueInput
}

/**
 * PublisherBalance findUniqueOrThrow
 */
export type PublisherBalanceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceInclude<ExtArgs> | null
  /**
   * Filter, which PublisherBalance to fetch.
   */
  where: Prisma.PublisherBalanceWhereUniqueInput
}

/**
 * PublisherBalance findFirst
 */
export type PublisherBalanceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceInclude<ExtArgs> | null
  /**
   * Filter, which PublisherBalance to fetch.
   */
  where?: Prisma.PublisherBalanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PublisherBalances to fetch.
   */
  orderBy?: Prisma.PublisherBalanceOrderByWithRelationInput | Prisma.PublisherBalanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PublisherBalances.
   */
  cursor?: Prisma.PublisherBalanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PublisherBalances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PublisherBalances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PublisherBalances.
   */
  distinct?: Prisma.PublisherBalanceScalarFieldEnum | Prisma.PublisherBalanceScalarFieldEnum[]
}

/**
 * PublisherBalance findFirstOrThrow
 */
export type PublisherBalanceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceInclude<ExtArgs> | null
  /**
   * Filter, which PublisherBalance to fetch.
   */
  where?: Prisma.PublisherBalanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PublisherBalances to fetch.
   */
  orderBy?: Prisma.PublisherBalanceOrderByWithRelationInput | Prisma.PublisherBalanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PublisherBalances.
   */
  cursor?: Prisma.PublisherBalanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PublisherBalances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PublisherBalances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PublisherBalances.
   */
  distinct?: Prisma.PublisherBalanceScalarFieldEnum | Prisma.PublisherBalanceScalarFieldEnum[]
}

/**
 * PublisherBalance findMany
 */
export type PublisherBalanceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceInclude<ExtArgs> | null
  /**
   * Filter, which PublisherBalances to fetch.
   */
  where?: Prisma.PublisherBalanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PublisherBalances to fetch.
   */
  orderBy?: Prisma.PublisherBalanceOrderByWithRelationInput | Prisma.PublisherBalanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PublisherBalances.
   */
  cursor?: Prisma.PublisherBalanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PublisherBalances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PublisherBalances.
   */
  skip?: number
  distinct?: Prisma.PublisherBalanceScalarFieldEnum | Prisma.PublisherBalanceScalarFieldEnum[]
}

/**
 * PublisherBalance create
 */
export type PublisherBalanceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceInclude<ExtArgs> | null
  /**
   * The data needed to create a PublisherBalance.
   */
  data: Prisma.XOR<Prisma.PublisherBalanceCreateInput, Prisma.PublisherBalanceUncheckedCreateInput>
}

/**
 * PublisherBalance createMany
 */
export type PublisherBalanceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PublisherBalances.
   */
  data: Prisma.PublisherBalanceCreateManyInput | Prisma.PublisherBalanceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PublisherBalance createManyAndReturn
 */
export type PublisherBalanceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * The data used to create many PublisherBalances.
   */
  data: Prisma.PublisherBalanceCreateManyInput | Prisma.PublisherBalanceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PublisherBalance update
 */
export type PublisherBalanceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceInclude<ExtArgs> | null
  /**
   * The data needed to update a PublisherBalance.
   */
  data: Prisma.XOR<Prisma.PublisherBalanceUpdateInput, Prisma.PublisherBalanceUncheckedUpdateInput>
  /**
   * Choose, which PublisherBalance to update.
   */
  where: Prisma.PublisherBalanceWhereUniqueInput
}

/**
 * PublisherBalance updateMany
 */
export type PublisherBalanceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PublisherBalances.
   */
  data: Prisma.XOR<Prisma.PublisherBalanceUpdateManyMutationInput, Prisma.PublisherBalanceUncheckedUpdateManyInput>
  /**
   * Filter which PublisherBalances to update
   */
  where?: Prisma.PublisherBalanceWhereInput
  /**
   * Limit how many PublisherBalances to update.
   */
  limit?: number
}

/**
 * PublisherBalance updateManyAndReturn
 */
export type PublisherBalanceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * The data used to update PublisherBalances.
   */
  data: Prisma.XOR<Prisma.PublisherBalanceUpdateManyMutationInput, Prisma.PublisherBalanceUncheckedUpdateManyInput>
  /**
   * Filter which PublisherBalances to update
   */
  where?: Prisma.PublisherBalanceWhereInput
  /**
   * Limit how many PublisherBalances to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PublisherBalance upsert
 */
export type PublisherBalanceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceInclude<ExtArgs> | null
  /**
   * The filter to search for the PublisherBalance to update in case it exists.
   */
  where: Prisma.PublisherBalanceWhereUniqueInput
  /**
   * In case the PublisherBalance found by the `where` argument doesn't exist, create a new PublisherBalance with this data.
   */
  create: Prisma.XOR<Prisma.PublisherBalanceCreateInput, Prisma.PublisherBalanceUncheckedCreateInput>
  /**
   * In case the PublisherBalance was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PublisherBalanceUpdateInput, Prisma.PublisherBalanceUncheckedUpdateInput>
}

/**
 * PublisherBalance delete
 */
export type PublisherBalanceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceInclude<ExtArgs> | null
  /**
   * Filter which PublisherBalance to delete.
   */
  where: Prisma.PublisherBalanceWhereUniqueInput
}

/**
 * PublisherBalance deleteMany
 */
export type PublisherBalanceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PublisherBalances to delete
   */
  where?: Prisma.PublisherBalanceWhereInput
  /**
   * Limit how many PublisherBalances to delete.
   */
  limit?: number
}

/**
 * PublisherBalance without action
 */
export type PublisherBalanceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PublisherBalance
   */
  select?: Prisma.PublisherBalanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PublisherBalance
   */
  omit?: Prisma.PublisherBalanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PublisherBalanceInclude<ExtArgs> | null
}
