
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SettlementApproval` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SettlementApproval
 * 
 */
export type SettlementApprovalModel = runtime.Types.Result.DefaultSelection<Prisma.$SettlementApprovalPayload>

export type AggregateSettlementApproval = {
  _count: SettlementApprovalCountAggregateOutputType | null
  _min: SettlementApprovalMinAggregateOutputType | null
  _max: SettlementApprovalMaxAggregateOutputType | null
}

export type SettlementApprovalMinAggregateOutputType = {
  id: string | null
  settlementId: string | null
  type: $Enums.SettlementApprovalType | null
  approvedBy: string | null
  roleAtTime: string | null
  approvedAt: Date | null
}

export type SettlementApprovalMaxAggregateOutputType = {
  id: string | null
  settlementId: string | null
  type: $Enums.SettlementApprovalType | null
  approvedBy: string | null
  roleAtTime: string | null
  approvedAt: Date | null
}

export type SettlementApprovalCountAggregateOutputType = {
  id: number
  settlementId: number
  type: number
  approvedBy: number
  roleAtTime: number
  approvedAt: number
  _all: number
}


export type SettlementApprovalMinAggregateInputType = {
  id?: true
  settlementId?: true
  type?: true
  approvedBy?: true
  roleAtTime?: true
  approvedAt?: true
}

export type SettlementApprovalMaxAggregateInputType = {
  id?: true
  settlementId?: true
  type?: true
  approvedBy?: true
  roleAtTime?: true
  approvedAt?: true
}

export type SettlementApprovalCountAggregateInputType = {
  id?: true
  settlementId?: true
  type?: true
  approvedBy?: true
  roleAtTime?: true
  approvedAt?: true
  _all?: true
}

export type SettlementApprovalAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SettlementApproval to aggregate.
   */
  where?: Prisma.SettlementApprovalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SettlementApprovals to fetch.
   */
  orderBy?: Prisma.SettlementApprovalOrderByWithRelationInput | Prisma.SettlementApprovalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SettlementApprovalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SettlementApprovals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SettlementApprovals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SettlementApprovals
  **/
  _count?: true | SettlementApprovalCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SettlementApprovalMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SettlementApprovalMaxAggregateInputType
}

export type GetSettlementApprovalAggregateType<T extends SettlementApprovalAggregateArgs> = {
      [P in keyof T & keyof AggregateSettlementApproval]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSettlementApproval[P]>
    : Prisma.GetScalarType<T[P], AggregateSettlementApproval[P]>
}




export type SettlementApprovalGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SettlementApprovalWhereInput
  orderBy?: Prisma.SettlementApprovalOrderByWithAggregationInput | Prisma.SettlementApprovalOrderByWithAggregationInput[]
  by: Prisma.SettlementApprovalScalarFieldEnum[] | Prisma.SettlementApprovalScalarFieldEnum
  having?: Prisma.SettlementApprovalScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SettlementApprovalCountAggregateInputType | true
  _min?: SettlementApprovalMinAggregateInputType
  _max?: SettlementApprovalMaxAggregateInputType
}

export type SettlementApprovalGroupByOutputType = {
  id: string
  settlementId: string
  type: $Enums.SettlementApprovalType
  approvedBy: string
  roleAtTime: string
  approvedAt: Date
  _count: SettlementApprovalCountAggregateOutputType | null
  _min: SettlementApprovalMinAggregateOutputType | null
  _max: SettlementApprovalMaxAggregateOutputType | null
}

type GetSettlementApprovalGroupByPayload<T extends SettlementApprovalGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SettlementApprovalGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SettlementApprovalGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SettlementApprovalGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SettlementApprovalGroupByOutputType[P]>
      }
    >
  >



export type SettlementApprovalWhereInput = {
  AND?: Prisma.SettlementApprovalWhereInput | Prisma.SettlementApprovalWhereInput[]
  OR?: Prisma.SettlementApprovalWhereInput[]
  NOT?: Prisma.SettlementApprovalWhereInput | Prisma.SettlementApprovalWhereInput[]
  id?: Prisma.StringFilter<"SettlementApproval"> | string
  settlementId?: Prisma.StringFilter<"SettlementApproval"> | string
  type?: Prisma.EnumSettlementApprovalTypeFilter<"SettlementApproval"> | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringFilter<"SettlementApproval"> | string
  roleAtTime?: Prisma.StringFilter<"SettlementApproval"> | string
  approvedAt?: Prisma.DateTimeFilter<"SettlementApproval"> | Date | string
  settlement?: Prisma.XOR<Prisma.SettlementScalarRelationFilter, Prisma.SettlementWhereInput>
}

export type SettlementApprovalOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  settlementId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  roleAtTime?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
  settlement?: Prisma.SettlementOrderByWithRelationInput
}

export type SettlementApprovalWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  settlementId_type?: Prisma.SettlementApprovalSettlementIdTypeCompoundUniqueInput
  AND?: Prisma.SettlementApprovalWhereInput | Prisma.SettlementApprovalWhereInput[]
  OR?: Prisma.SettlementApprovalWhereInput[]
  NOT?: Prisma.SettlementApprovalWhereInput | Prisma.SettlementApprovalWhereInput[]
  settlementId?: Prisma.StringFilter<"SettlementApproval"> | string
  type?: Prisma.EnumSettlementApprovalTypeFilter<"SettlementApproval"> | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringFilter<"SettlementApproval"> | string
  roleAtTime?: Prisma.StringFilter<"SettlementApproval"> | string
  approvedAt?: Prisma.DateTimeFilter<"SettlementApproval"> | Date | string
  settlement?: Prisma.XOR<Prisma.SettlementScalarRelationFilter, Prisma.SettlementWhereInput>
}, "id" | "settlementId_type">

export type SettlementApprovalOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  settlementId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  roleAtTime?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
  _count?: Prisma.SettlementApprovalCountOrderByAggregateInput
  _max?: Prisma.SettlementApprovalMaxOrderByAggregateInput
  _min?: Prisma.SettlementApprovalMinOrderByAggregateInput
}

export type SettlementApprovalScalarWhereWithAggregatesInput = {
  AND?: Prisma.SettlementApprovalScalarWhereWithAggregatesInput | Prisma.SettlementApprovalScalarWhereWithAggregatesInput[]
  OR?: Prisma.SettlementApprovalScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SettlementApprovalScalarWhereWithAggregatesInput | Prisma.SettlementApprovalScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SettlementApproval"> | string
  settlementId?: Prisma.StringWithAggregatesFilter<"SettlementApproval"> | string
  type?: Prisma.EnumSettlementApprovalTypeWithAggregatesFilter<"SettlementApproval"> | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringWithAggregatesFilter<"SettlementApproval"> | string
  roleAtTime?: Prisma.StringWithAggregatesFilter<"SettlementApproval"> | string
  approvedAt?: Prisma.DateTimeWithAggregatesFilter<"SettlementApproval"> | Date | string
}

export type SettlementApprovalCreateInput = {
  id?: string
  type: $Enums.SettlementApprovalType
  approvedBy: string
  roleAtTime: string
  approvedAt?: Date | string
  settlement: Prisma.SettlementCreateNestedOneWithoutApprovalsInput
}

export type SettlementApprovalUncheckedCreateInput = {
  id?: string
  settlementId: string
  type: $Enums.SettlementApprovalType
  approvedBy: string
  roleAtTime: string
  approvedAt?: Date | string
}

export type SettlementApprovalUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSettlementApprovalTypeFieldUpdateOperationsInput | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  roleAtTime?: Prisma.StringFieldUpdateOperationsInput | string
  approvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  settlement?: Prisma.SettlementUpdateOneRequiredWithoutApprovalsNestedInput
}

export type SettlementApprovalUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  settlementId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSettlementApprovalTypeFieldUpdateOperationsInput | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  roleAtTime?: Prisma.StringFieldUpdateOperationsInput | string
  approvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SettlementApprovalCreateManyInput = {
  id?: string
  settlementId: string
  type: $Enums.SettlementApprovalType
  approvedBy: string
  roleAtTime: string
  approvedAt?: Date | string
}

export type SettlementApprovalUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSettlementApprovalTypeFieldUpdateOperationsInput | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  roleAtTime?: Prisma.StringFieldUpdateOperationsInput | string
  approvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SettlementApprovalUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  settlementId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSettlementApprovalTypeFieldUpdateOperationsInput | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  roleAtTime?: Prisma.StringFieldUpdateOperationsInput | string
  approvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SettlementApprovalListRelationFilter = {
  every?: Prisma.SettlementApprovalWhereInput
  some?: Prisma.SettlementApprovalWhereInput
  none?: Prisma.SettlementApprovalWhereInput
}

export type SettlementApprovalOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SettlementApprovalSettlementIdTypeCompoundUniqueInput = {
  settlementId: string
  type: $Enums.SettlementApprovalType
}

export type SettlementApprovalCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  settlementId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  roleAtTime?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
}

export type SettlementApprovalMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  settlementId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  roleAtTime?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
}

export type SettlementApprovalMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  settlementId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  approvedBy?: Prisma.SortOrder
  roleAtTime?: Prisma.SortOrder
  approvedAt?: Prisma.SortOrder
}

export type SettlementApprovalCreateNestedManyWithoutSettlementInput = {
  create?: Prisma.XOR<Prisma.SettlementApprovalCreateWithoutSettlementInput, Prisma.SettlementApprovalUncheckedCreateWithoutSettlementInput> | Prisma.SettlementApprovalCreateWithoutSettlementInput[] | Prisma.SettlementApprovalUncheckedCreateWithoutSettlementInput[]
  connectOrCreate?: Prisma.SettlementApprovalCreateOrConnectWithoutSettlementInput | Prisma.SettlementApprovalCreateOrConnectWithoutSettlementInput[]
  createMany?: Prisma.SettlementApprovalCreateManySettlementInputEnvelope
  connect?: Prisma.SettlementApprovalWhereUniqueInput | Prisma.SettlementApprovalWhereUniqueInput[]
}

export type SettlementApprovalUncheckedCreateNestedManyWithoutSettlementInput = {
  create?: Prisma.XOR<Prisma.SettlementApprovalCreateWithoutSettlementInput, Prisma.SettlementApprovalUncheckedCreateWithoutSettlementInput> | Prisma.SettlementApprovalCreateWithoutSettlementInput[] | Prisma.SettlementApprovalUncheckedCreateWithoutSettlementInput[]
  connectOrCreate?: Prisma.SettlementApprovalCreateOrConnectWithoutSettlementInput | Prisma.SettlementApprovalCreateOrConnectWithoutSettlementInput[]
  createMany?: Prisma.SettlementApprovalCreateManySettlementInputEnvelope
  connect?: Prisma.SettlementApprovalWhereUniqueInput | Prisma.SettlementApprovalWhereUniqueInput[]
}

export type SettlementApprovalUpdateManyWithoutSettlementNestedInput = {
  create?: Prisma.XOR<Prisma.SettlementApprovalCreateWithoutSettlementInput, Prisma.SettlementApprovalUncheckedCreateWithoutSettlementInput> | Prisma.SettlementApprovalCreateWithoutSettlementInput[] | Prisma.SettlementApprovalUncheckedCreateWithoutSettlementInput[]
  connectOrCreate?: Prisma.SettlementApprovalCreateOrConnectWithoutSettlementInput | Prisma.SettlementApprovalCreateOrConnectWithoutSettlementInput[]
  upsert?: Prisma.SettlementApprovalUpsertWithWhereUniqueWithoutSettlementInput | Prisma.SettlementApprovalUpsertWithWhereUniqueWithoutSettlementInput[]
  createMany?: Prisma.SettlementApprovalCreateManySettlementInputEnvelope
  set?: Prisma.SettlementApprovalWhereUniqueInput | Prisma.SettlementApprovalWhereUniqueInput[]
  disconnect?: Prisma.SettlementApprovalWhereUniqueInput | Prisma.SettlementApprovalWhereUniqueInput[]
  delete?: Prisma.SettlementApprovalWhereUniqueInput | Prisma.SettlementApprovalWhereUniqueInput[]
  connect?: Prisma.SettlementApprovalWhereUniqueInput | Prisma.SettlementApprovalWhereUniqueInput[]
  update?: Prisma.SettlementApprovalUpdateWithWhereUniqueWithoutSettlementInput | Prisma.SettlementApprovalUpdateWithWhereUniqueWithoutSettlementInput[]
  updateMany?: Prisma.SettlementApprovalUpdateManyWithWhereWithoutSettlementInput | Prisma.SettlementApprovalUpdateManyWithWhereWithoutSettlementInput[]
  deleteMany?: Prisma.SettlementApprovalScalarWhereInput | Prisma.SettlementApprovalScalarWhereInput[]
}

export type SettlementApprovalUncheckedUpdateManyWithoutSettlementNestedInput = {
  create?: Prisma.XOR<Prisma.SettlementApprovalCreateWithoutSettlementInput, Prisma.SettlementApprovalUncheckedCreateWithoutSettlementInput> | Prisma.SettlementApprovalCreateWithoutSettlementInput[] | Prisma.SettlementApprovalUncheckedCreateWithoutSettlementInput[]
  connectOrCreate?: Prisma.SettlementApprovalCreateOrConnectWithoutSettlementInput | Prisma.SettlementApprovalCreateOrConnectWithoutSettlementInput[]
  upsert?: Prisma.SettlementApprovalUpsertWithWhereUniqueWithoutSettlementInput | Prisma.SettlementApprovalUpsertWithWhereUniqueWithoutSettlementInput[]
  createMany?: Prisma.SettlementApprovalCreateManySettlementInputEnvelope
  set?: Prisma.SettlementApprovalWhereUniqueInput | Prisma.SettlementApprovalWhereUniqueInput[]
  disconnect?: Prisma.SettlementApprovalWhereUniqueInput | Prisma.SettlementApprovalWhereUniqueInput[]
  delete?: Prisma.SettlementApprovalWhereUniqueInput | Prisma.SettlementApprovalWhereUniqueInput[]
  connect?: Prisma.SettlementApprovalWhereUniqueInput | Prisma.SettlementApprovalWhereUniqueInput[]
  update?: Prisma.SettlementApprovalUpdateWithWhereUniqueWithoutSettlementInput | Prisma.SettlementApprovalUpdateWithWhereUniqueWithoutSettlementInput[]
  updateMany?: Prisma.SettlementApprovalUpdateManyWithWhereWithoutSettlementInput | Prisma.SettlementApprovalUpdateManyWithWhereWithoutSettlementInput[]
  deleteMany?: Prisma.SettlementApprovalScalarWhereInput | Prisma.SettlementApprovalScalarWhereInput[]
}

export type EnumSettlementApprovalTypeFieldUpdateOperationsInput = {
  set?: $Enums.SettlementApprovalType
}

export type SettlementApprovalCreateWithoutSettlementInput = {
  id?: string
  type: $Enums.SettlementApprovalType
  approvedBy: string
  roleAtTime: string
  approvedAt?: Date | string
}

export type SettlementApprovalUncheckedCreateWithoutSettlementInput = {
  id?: string
  type: $Enums.SettlementApprovalType
  approvedBy: string
  roleAtTime: string
  approvedAt?: Date | string
}

export type SettlementApprovalCreateOrConnectWithoutSettlementInput = {
  where: Prisma.SettlementApprovalWhereUniqueInput
  create: Prisma.XOR<Prisma.SettlementApprovalCreateWithoutSettlementInput, Prisma.SettlementApprovalUncheckedCreateWithoutSettlementInput>
}

export type SettlementApprovalCreateManySettlementInputEnvelope = {
  data: Prisma.SettlementApprovalCreateManySettlementInput | Prisma.SettlementApprovalCreateManySettlementInput[]
  skipDuplicates?: boolean
}

export type SettlementApprovalUpsertWithWhereUniqueWithoutSettlementInput = {
  where: Prisma.SettlementApprovalWhereUniqueInput
  update: Prisma.XOR<Prisma.SettlementApprovalUpdateWithoutSettlementInput, Prisma.SettlementApprovalUncheckedUpdateWithoutSettlementInput>
  create: Prisma.XOR<Prisma.SettlementApprovalCreateWithoutSettlementInput, Prisma.SettlementApprovalUncheckedCreateWithoutSettlementInput>
}

export type SettlementApprovalUpdateWithWhereUniqueWithoutSettlementInput = {
  where: Prisma.SettlementApprovalWhereUniqueInput
  data: Prisma.XOR<Prisma.SettlementApprovalUpdateWithoutSettlementInput, Prisma.SettlementApprovalUncheckedUpdateWithoutSettlementInput>
}

export type SettlementApprovalUpdateManyWithWhereWithoutSettlementInput = {
  where: Prisma.SettlementApprovalScalarWhereInput
  data: Prisma.XOR<Prisma.SettlementApprovalUpdateManyMutationInput, Prisma.SettlementApprovalUncheckedUpdateManyWithoutSettlementInput>
}

export type SettlementApprovalScalarWhereInput = {
  AND?: Prisma.SettlementApprovalScalarWhereInput | Prisma.SettlementApprovalScalarWhereInput[]
  OR?: Prisma.SettlementApprovalScalarWhereInput[]
  NOT?: Prisma.SettlementApprovalScalarWhereInput | Prisma.SettlementApprovalScalarWhereInput[]
  id?: Prisma.StringFilter<"SettlementApproval"> | string
  settlementId?: Prisma.StringFilter<"SettlementApproval"> | string
  type?: Prisma.EnumSettlementApprovalTypeFilter<"SettlementApproval"> | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringFilter<"SettlementApproval"> | string
  roleAtTime?: Prisma.StringFilter<"SettlementApproval"> | string
  approvedAt?: Prisma.DateTimeFilter<"SettlementApproval"> | Date | string
}

export type SettlementApprovalCreateManySettlementInput = {
  id?: string
  type: $Enums.SettlementApprovalType
  approvedBy: string
  roleAtTime: string
  approvedAt?: Date | string
}

export type SettlementApprovalUpdateWithoutSettlementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSettlementApprovalTypeFieldUpdateOperationsInput | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  roleAtTime?: Prisma.StringFieldUpdateOperationsInput | string
  approvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SettlementApprovalUncheckedUpdateWithoutSettlementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSettlementApprovalTypeFieldUpdateOperationsInput | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  roleAtTime?: Prisma.StringFieldUpdateOperationsInput | string
  approvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SettlementApprovalUncheckedUpdateManyWithoutSettlementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumSettlementApprovalTypeFieldUpdateOperationsInput | $Enums.SettlementApprovalType
  approvedBy?: Prisma.StringFieldUpdateOperationsInput | string
  roleAtTime?: Prisma.StringFieldUpdateOperationsInput | string
  approvedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SettlementApprovalSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  settlementId?: boolean
  type?: boolean
  approvedBy?: boolean
  roleAtTime?: boolean
  approvedAt?: boolean
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["settlementApproval"]>

export type SettlementApprovalSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  settlementId?: boolean
  type?: boolean
  approvedBy?: boolean
  roleAtTime?: boolean
  approvedAt?: boolean
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["settlementApproval"]>

export type SettlementApprovalSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  settlementId?: boolean
  type?: boolean
  approvedBy?: boolean
  roleAtTime?: boolean
  approvedAt?: boolean
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}, ExtArgs["result"]["settlementApproval"]>

export type SettlementApprovalSelectScalar = {
  id?: boolean
  settlementId?: boolean
  type?: boolean
  approvedBy?: boolean
  roleAtTime?: boolean
  approvedAt?: boolean
}

export type SettlementApprovalOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "settlementId" | "type" | "approvedBy" | "roleAtTime" | "approvedAt", ExtArgs["result"]["settlementApproval"]>
export type SettlementApprovalInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}
export type SettlementApprovalIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}
export type SettlementApprovalIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  settlement?: boolean | Prisma.SettlementDefaultArgs<ExtArgs>
}

export type $SettlementApprovalPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SettlementApproval"
  objects: {
    settlement: Prisma.$SettlementPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    settlementId: string
    type: $Enums.SettlementApprovalType
    approvedBy: string
    roleAtTime: string
    approvedAt: Date
  }, ExtArgs["result"]["settlementApproval"]>
  composites: {}
}

export type SettlementApprovalGetPayload<S extends boolean | null | undefined | SettlementApprovalDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload, S>

export type SettlementApprovalCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SettlementApprovalFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SettlementApprovalCountAggregateInputType | true
  }

export interface SettlementApprovalDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SettlementApproval'], meta: { name: 'SettlementApproval' } }
  /**
   * Find zero or one SettlementApproval that matches the filter.
   * @param {SettlementApprovalFindUniqueArgs} args - Arguments to find a SettlementApproval
   * @example
   * // Get one SettlementApproval
   * const settlementApproval = await prisma.settlementApproval.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SettlementApprovalFindUniqueArgs>(args: Prisma.SelectSubset<T, SettlementApprovalFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SettlementApprovalClient<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SettlementApproval that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SettlementApprovalFindUniqueOrThrowArgs} args - Arguments to find a SettlementApproval
   * @example
   * // Get one SettlementApproval
   * const settlementApproval = await prisma.settlementApproval.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SettlementApprovalFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SettlementApprovalFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SettlementApprovalClient<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SettlementApproval that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlementApprovalFindFirstArgs} args - Arguments to find a SettlementApproval
   * @example
   * // Get one SettlementApproval
   * const settlementApproval = await prisma.settlementApproval.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SettlementApprovalFindFirstArgs>(args?: Prisma.SelectSubset<T, SettlementApprovalFindFirstArgs<ExtArgs>>): Prisma.Prisma__SettlementApprovalClient<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SettlementApproval that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlementApprovalFindFirstOrThrowArgs} args - Arguments to find a SettlementApproval
   * @example
   * // Get one SettlementApproval
   * const settlementApproval = await prisma.settlementApproval.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SettlementApprovalFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SettlementApprovalFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SettlementApprovalClient<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SettlementApprovals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlementApprovalFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SettlementApprovals
   * const settlementApprovals = await prisma.settlementApproval.findMany()
   * 
   * // Get first 10 SettlementApprovals
   * const settlementApprovals = await prisma.settlementApproval.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const settlementApprovalWithIdOnly = await prisma.settlementApproval.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SettlementApprovalFindManyArgs>(args?: Prisma.SelectSubset<T, SettlementApprovalFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SettlementApproval.
   * @param {SettlementApprovalCreateArgs} args - Arguments to create a SettlementApproval.
   * @example
   * // Create one SettlementApproval
   * const SettlementApproval = await prisma.settlementApproval.create({
   *   data: {
   *     // ... data to create a SettlementApproval
   *   }
   * })
   * 
   */
  create<T extends SettlementApprovalCreateArgs>(args: Prisma.SelectSubset<T, SettlementApprovalCreateArgs<ExtArgs>>): Prisma.Prisma__SettlementApprovalClient<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SettlementApprovals.
   * @param {SettlementApprovalCreateManyArgs} args - Arguments to create many SettlementApprovals.
   * @example
   * // Create many SettlementApprovals
   * const settlementApproval = await prisma.settlementApproval.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SettlementApprovalCreateManyArgs>(args?: Prisma.SelectSubset<T, SettlementApprovalCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SettlementApprovals and returns the data saved in the database.
   * @param {SettlementApprovalCreateManyAndReturnArgs} args - Arguments to create many SettlementApprovals.
   * @example
   * // Create many SettlementApprovals
   * const settlementApproval = await prisma.settlementApproval.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SettlementApprovals and only return the `id`
   * const settlementApprovalWithIdOnly = await prisma.settlementApproval.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SettlementApprovalCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SettlementApprovalCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SettlementApproval.
   * @param {SettlementApprovalDeleteArgs} args - Arguments to delete one SettlementApproval.
   * @example
   * // Delete one SettlementApproval
   * const SettlementApproval = await prisma.settlementApproval.delete({
   *   where: {
   *     // ... filter to delete one SettlementApproval
   *   }
   * })
   * 
   */
  delete<T extends SettlementApprovalDeleteArgs>(args: Prisma.SelectSubset<T, SettlementApprovalDeleteArgs<ExtArgs>>): Prisma.Prisma__SettlementApprovalClient<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SettlementApproval.
   * @param {SettlementApprovalUpdateArgs} args - Arguments to update one SettlementApproval.
   * @example
   * // Update one SettlementApproval
   * const settlementApproval = await prisma.settlementApproval.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SettlementApprovalUpdateArgs>(args: Prisma.SelectSubset<T, SettlementApprovalUpdateArgs<ExtArgs>>): Prisma.Prisma__SettlementApprovalClient<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SettlementApprovals.
   * @param {SettlementApprovalDeleteManyArgs} args - Arguments to filter SettlementApprovals to delete.
   * @example
   * // Delete a few SettlementApprovals
   * const { count } = await prisma.settlementApproval.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SettlementApprovalDeleteManyArgs>(args?: Prisma.SelectSubset<T, SettlementApprovalDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SettlementApprovals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlementApprovalUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SettlementApprovals
   * const settlementApproval = await prisma.settlementApproval.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SettlementApprovalUpdateManyArgs>(args: Prisma.SelectSubset<T, SettlementApprovalUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SettlementApprovals and returns the data updated in the database.
   * @param {SettlementApprovalUpdateManyAndReturnArgs} args - Arguments to update many SettlementApprovals.
   * @example
   * // Update many SettlementApprovals
   * const settlementApproval = await prisma.settlementApproval.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SettlementApprovals and only return the `id`
   * const settlementApprovalWithIdOnly = await prisma.settlementApproval.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SettlementApprovalUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SettlementApprovalUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SettlementApproval.
   * @param {SettlementApprovalUpsertArgs} args - Arguments to update or create a SettlementApproval.
   * @example
   * // Update or create a SettlementApproval
   * const settlementApproval = await prisma.settlementApproval.upsert({
   *   create: {
   *     // ... data to create a SettlementApproval
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SettlementApproval we want to update
   *   }
   * })
   */
  upsert<T extends SettlementApprovalUpsertArgs>(args: Prisma.SelectSubset<T, SettlementApprovalUpsertArgs<ExtArgs>>): Prisma.Prisma__SettlementApprovalClient<runtime.Types.Result.GetResult<Prisma.$SettlementApprovalPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SettlementApprovals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlementApprovalCountArgs} args - Arguments to filter SettlementApprovals to count.
   * @example
   * // Count the number of SettlementApprovals
   * const count = await prisma.settlementApproval.count({
   *   where: {
   *     // ... the filter for the SettlementApprovals we want to count
   *   }
   * })
  **/
  count<T extends SettlementApprovalCountArgs>(
    args?: Prisma.Subset<T, SettlementApprovalCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SettlementApprovalCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SettlementApproval.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlementApprovalAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SettlementApprovalAggregateArgs>(args: Prisma.Subset<T, SettlementApprovalAggregateArgs>): Prisma.PrismaPromise<GetSettlementApprovalAggregateType<T>>

  /**
   * Group by SettlementApproval.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SettlementApprovalGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SettlementApprovalGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SettlementApprovalGroupByArgs['orderBy'] }
      : { orderBy?: SettlementApprovalGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SettlementApprovalGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSettlementApprovalGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SettlementApproval model
 */
readonly fields: SettlementApprovalFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SettlementApproval.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SettlementApprovalClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  settlement<T extends Prisma.SettlementDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SettlementDefaultArgs<ExtArgs>>): Prisma.Prisma__SettlementClient<runtime.Types.Result.GetResult<Prisma.$SettlementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SettlementApproval model
 */
export interface SettlementApprovalFieldRefs {
  readonly id: Prisma.FieldRef<"SettlementApproval", 'String'>
  readonly settlementId: Prisma.FieldRef<"SettlementApproval", 'String'>
  readonly type: Prisma.FieldRef<"SettlementApproval", 'SettlementApprovalType'>
  readonly approvedBy: Prisma.FieldRef<"SettlementApproval", 'String'>
  readonly roleAtTime: Prisma.FieldRef<"SettlementApproval", 'String'>
  readonly approvedAt: Prisma.FieldRef<"SettlementApproval", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SettlementApproval findUnique
 */
export type SettlementApprovalFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalInclude<ExtArgs> | null
  /**
   * Filter, which SettlementApproval to fetch.
   */
  where: Prisma.SettlementApprovalWhereUniqueInput
}

/**
 * SettlementApproval findUniqueOrThrow
 */
export type SettlementApprovalFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalInclude<ExtArgs> | null
  /**
   * Filter, which SettlementApproval to fetch.
   */
  where: Prisma.SettlementApprovalWhereUniqueInput
}

/**
 * SettlementApproval findFirst
 */
export type SettlementApprovalFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalInclude<ExtArgs> | null
  /**
   * Filter, which SettlementApproval to fetch.
   */
  where?: Prisma.SettlementApprovalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SettlementApprovals to fetch.
   */
  orderBy?: Prisma.SettlementApprovalOrderByWithRelationInput | Prisma.SettlementApprovalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SettlementApprovals.
   */
  cursor?: Prisma.SettlementApprovalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SettlementApprovals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SettlementApprovals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SettlementApprovals.
   */
  distinct?: Prisma.SettlementApprovalScalarFieldEnum | Prisma.SettlementApprovalScalarFieldEnum[]
}

/**
 * SettlementApproval findFirstOrThrow
 */
export type SettlementApprovalFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalInclude<ExtArgs> | null
  /**
   * Filter, which SettlementApproval to fetch.
   */
  where?: Prisma.SettlementApprovalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SettlementApprovals to fetch.
   */
  orderBy?: Prisma.SettlementApprovalOrderByWithRelationInput | Prisma.SettlementApprovalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SettlementApprovals.
   */
  cursor?: Prisma.SettlementApprovalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SettlementApprovals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SettlementApprovals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SettlementApprovals.
   */
  distinct?: Prisma.SettlementApprovalScalarFieldEnum | Prisma.SettlementApprovalScalarFieldEnum[]
}

/**
 * SettlementApproval findMany
 */
export type SettlementApprovalFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalInclude<ExtArgs> | null
  /**
   * Filter, which SettlementApprovals to fetch.
   */
  where?: Prisma.SettlementApprovalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SettlementApprovals to fetch.
   */
  orderBy?: Prisma.SettlementApprovalOrderByWithRelationInput | Prisma.SettlementApprovalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SettlementApprovals.
   */
  cursor?: Prisma.SettlementApprovalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SettlementApprovals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SettlementApprovals.
   */
  skip?: number
  distinct?: Prisma.SettlementApprovalScalarFieldEnum | Prisma.SettlementApprovalScalarFieldEnum[]
}

/**
 * SettlementApproval create
 */
export type SettlementApprovalCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalInclude<ExtArgs> | null
  /**
   * The data needed to create a SettlementApproval.
   */
  data: Prisma.XOR<Prisma.SettlementApprovalCreateInput, Prisma.SettlementApprovalUncheckedCreateInput>
}

/**
 * SettlementApproval createMany
 */
export type SettlementApprovalCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SettlementApprovals.
   */
  data: Prisma.SettlementApprovalCreateManyInput | Prisma.SettlementApprovalCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SettlementApproval createManyAndReturn
 */
export type SettlementApprovalCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * The data used to create many SettlementApprovals.
   */
  data: Prisma.SettlementApprovalCreateManyInput | Prisma.SettlementApprovalCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SettlementApproval update
 */
export type SettlementApprovalUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalInclude<ExtArgs> | null
  /**
   * The data needed to update a SettlementApproval.
   */
  data: Prisma.XOR<Prisma.SettlementApprovalUpdateInput, Prisma.SettlementApprovalUncheckedUpdateInput>
  /**
   * Choose, which SettlementApproval to update.
   */
  where: Prisma.SettlementApprovalWhereUniqueInput
}

/**
 * SettlementApproval updateMany
 */
export type SettlementApprovalUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SettlementApprovals.
   */
  data: Prisma.XOR<Prisma.SettlementApprovalUpdateManyMutationInput, Prisma.SettlementApprovalUncheckedUpdateManyInput>
  /**
   * Filter which SettlementApprovals to update
   */
  where?: Prisma.SettlementApprovalWhereInput
  /**
   * Limit how many SettlementApprovals to update.
   */
  limit?: number
}

/**
 * SettlementApproval updateManyAndReturn
 */
export type SettlementApprovalUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * The data used to update SettlementApprovals.
   */
  data: Prisma.XOR<Prisma.SettlementApprovalUpdateManyMutationInput, Prisma.SettlementApprovalUncheckedUpdateManyInput>
  /**
   * Filter which SettlementApprovals to update
   */
  where?: Prisma.SettlementApprovalWhereInput
  /**
   * Limit how many SettlementApprovals to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SettlementApproval upsert
 */
export type SettlementApprovalUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalInclude<ExtArgs> | null
  /**
   * The filter to search for the SettlementApproval to update in case it exists.
   */
  where: Prisma.SettlementApprovalWhereUniqueInput
  /**
   * In case the SettlementApproval found by the `where` argument doesn't exist, create a new SettlementApproval with this data.
   */
  create: Prisma.XOR<Prisma.SettlementApprovalCreateInput, Prisma.SettlementApprovalUncheckedCreateInput>
  /**
   * In case the SettlementApproval was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SettlementApprovalUpdateInput, Prisma.SettlementApprovalUncheckedUpdateInput>
}

/**
 * SettlementApproval delete
 */
export type SettlementApprovalDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalInclude<ExtArgs> | null
  /**
   * Filter which SettlementApproval to delete.
   */
  where: Prisma.SettlementApprovalWhereUniqueInput
}

/**
 * SettlementApproval deleteMany
 */
export type SettlementApprovalDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SettlementApprovals to delete
   */
  where?: Prisma.SettlementApprovalWhereInput
  /**
   * Limit how many SettlementApprovals to delete.
   */
  limit?: number
}

/**
 * SettlementApproval without action
 */
export type SettlementApprovalDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SettlementApproval
   */
  select?: Prisma.SettlementApprovalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SettlementApproval
   */
  omit?: Prisma.SettlementApprovalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SettlementApprovalInclude<ExtArgs> | null
}
