// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import path from "node:path"
import dotenv from "dotenv"

// Load the monorepo-root .env.development so `pnpm db:generate` works from a
// fresh clone without needing the caller to export DATABASE_URL by hand.
// dotenv does not override variables already set in the shell.
dotenv.config({ path: path.resolve(__dirname, "../../.env.development") })

import { defineConfig, env } from "prisma/config"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
})
