export const ORDER_STATUS_LABELS: Record<string, string> = {
  DRAFT: "Draft",
  PENDING_PAYMENT: "Pending Payment",
  PAID: "Paid",
  SUBMITTED: "Submitted",
  ACCEPTED: "Accepted",
  CONTENT_REQUESTED: "Content Requested",
  CONTENT_CREATION: "Content Creation",
  CONTENT_READY: "Content Ready",
  CUSTOMER_REVIEW: "Customer Review",
  APPROVED: "Approved",
  PUBLISHED: "Published",
  VERIFIED: "Verified",
  DELIVERED: "Delivered",
  SETTLED: "Settled",
  COMPLETED: "Completed",
  CANCELLED: "Cancelled",
  REFUNDED: "Refunded",
  DISPUTED: "Disputed",
}
