export const MARKETPLACE_CATEGORY_NAMES = [
  "Agriculture & Farming",
  "Animals & Pets",
  "Artificial Intelligence & AI Tools",
  "Arts, Photography & Videography",
  "Astrology",
  "Automobiles & Cars",
  "Aviation & Aerospace",
  "Banking & Finance",
  "Beauty",
  "Blockchain, Crypto & Web3",
  "Books & Literature",
  "Business",
  "Casino (Gambling)",
  "CBD & Hemp",
  "Charity & Non-Profit",
  "Computers & Consumer Electronics",
  "Construction & Repairs",
  "Crafts and DIY",
  "Culture & Society",
  "Cybersecurity",
  "Digital Marketing & Advertising",
  "E-commerce",
  "Education",
  "Electric Vehicles (EV)",
  "Energy (Oil, Gas & Nuclear)",
  "Entertainment, Movies & TV",
  "Environment & Nature",
  "Fashion",
  "Fintech",
  "Food & Beverages",
  "Football (Soccer)",
  "For Men",
  "For Women",
  "Gaming",
  "Gardening and Lawn Care",
  "General",
  "Golf",
  "Graphics & Design",
  "Health & Fitness",
  "Hobbies & Leisure",
  "Home & Decor",
  "Home Improvement",
  "Home Services",
  "Human Resources (HR)",
  "Industrial Equipment & Machinery",
  "Insurance",
  "Internet & Telecom",
  "Jobs & Employment",
  "Kids & Children",
  "Legal",
  "Lifestyle",
  "Local & City Guides",
  "Magazines & Newspapers",
  "Manufacturing & Industry",
  "Meditation",
  "Mental Health",
  "Mobile",
  "Music & Instruments",
  "News, Media & Magazines",
  "Nutrition & Supplements",
  "Other (Miscellaneous)",
  "Outdoors",
  "Parenting & Family",
  "Personal Development & Motivation",
  "Pharmacy",
  "Politics",
  "Real Estate",
  "Relationships",
  "Renewable Energy & Solar",
  "Review Sites",
  "SaaS",
  "Science",
  "Senior & Elder Care",
  "Services & Consulting",
  "Shopping",
  "Social Media",
  "Software Development",
  "Spirituality",
  "Sports",
  "Startups & Entrepreneurship",
  "Technology & Gadgets",
  "Tourism & Travel",
  "Trading (Forex & Stocks)",
  "Transport & Logistics",
  "Web Development",
  "Wedding & Event Planning",
  "Yoga & Wellness",
] as const

// Primary publishing languages. A listing stores exactly one of these values;
// marketplace discovery may select several values to broaden a search.
export const MARKETPLACE_LANGUAGES = [
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Armenian",
  "Azerbaijani",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Bulgarian",
  "Catalan",
  "Chinese",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Estonian",
  "Filipino",
  "Finnish",
  "French",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hebrew",
  "Hindi",
  "Hungarian",
  "Icelandic",
  "Indonesian",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Korean",
  "Latin",
  "Latvian",
  "Lithuanian",
  "Macedonian",
  "Malay",
  "Malayalam",
  "Maltese",
  "Marathi",
  "Norwegian",
  "Oriya",
  "Persian",
  "Polish",
  "Portuguese (Brazil)",
  "Portuguese (Portugal)",
  "Punjabi",
  "Romanian",
  "Russian",
  "Serbian",
  "Slovak",
  "Slovenian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",
  "Welsh",
  "Yiddish",
  "Other",
] as const

export const MARKETPLACE_CATEGORY_LIMIT = 7

export const LISTING_LINK_TYPES = [
  "DOFOLLOW",
  "NOFOLLOW",
  "SPONSORED",
  "UGC",
] as const

export const LISTING_LINK_VALIDITIES = [
  "PERMANENT",
  "FIVE_YEARS",
  "ONE_YEAR",
  "SIX_MONTHS",
  "THREE_MONTHS",
] as const

export type MarketplaceLanguage = (typeof MARKETPLACE_LANGUAGES)[number]
export type ListingLinkType = (typeof LISTING_LINK_TYPES)[number]
export type ListingLinkValidity = (typeof LISTING_LINK_VALIDITIES)[number]

export const LISTING_LINK_TYPE_LABELS: Record<ListingLinkType, string> = {
  DOFOLLOW: "DoFollow",
  NOFOLLOW: "NoFollow",
  SPONSORED: "Sponsored",
  UGC: "UGC",
}

export const LISTING_LINK_VALIDITY_LABELS: Record<ListingLinkValidity, string> =
  {
    PERMANENT: "Permanent",
    FIVE_YEARS: "5 years",
    ONE_YEAR: "1 year",
    SIX_MONTHS: "6 months",
    THREE_MONTHS: "3 months",
  }
